<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';$user=academy_require_login();if(!academy_can_view_accounts($user)){http_response_code(403);exit('Δεν έχετε πρόσβαση στους λογαριασμούς Academy.');}$manage=academy_is_admin($user);require __DIR__.'/accounts-workflow.php';$error=null;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!$manage){http_response_code(403);exit('Η τεχνική πρόσβαση είναι μόνο για ανάγνωση.');}
    verify_csrf();try{academy_manage_account($user,academy_input('action'),$_POST);$_SESSION['notice']='Η αλλαγή αποθηκεύτηκε μόνο στην Academy. Η πρόοδος διατηρείται.';redirect_to('accounts.php');}catch(InvalidArgumentException $e){$error=$e->getMessage();}
}
$accounts=db()->query('SELECT id,name,email,role,active,(password_hash IS NOT NULL) AS has_local_password,(sso_subject IS NOT NULL) AS has_sso FROM '.academy_table('users').' ORDER BY active DESC,name')->fetchAll();render_header('Εκπαιδευόμενοι',$user);
?><section class="school-page-title"><span><?= $manage?'ΔΙΑΧΕΙΡΙΣΗ ACADEMY':'ΤΕΧΝΙΚΗ ΠΡΟΒΟΛΗ' ?></span><h1>Οι άνθρωποι της ομάδας</h1><p>Οι λογαριασμοί αυτοί δίνουν πρόσβαση μόνο στην εκπαίδευση. Καμία αλλαγή δεν μεταφέρεται στα CRM.</p><?php if($manage): ?><a href="<?= e(academy_url('index.php?view=team')) ?>">Δες την πρόοδο της ομάδας →</a><?php else: ?><p class="school-info">Τεχνική πρόσβαση μόνο για ανάγνωση ονομάτων, emails, ρόλων και κατάστασης. Χωρίς αλλαγές χρηστών, επαναφορές κωδικών ή αξιολογήσεις άλλων.</p><?php endif; ?></section>
<?php if($error): ?><div class="school-error" role="alert"><?= e($error) ?></div><?php endif; ?>
<?php if(academy_crm_enabled()): ?><section class="school-panel"><h2>Κοινοί λογαριασμοί με Energiaki CRM</h2><p>Οι ενεργοί χρήστες του CRM συνδέονται εδώ με το ίδιο email και τον ίδιο κωδικό. Η εκπαιδευτική καρτέλα εμφανίζεται στην πρώτη τους σύνδεση. Νέοι χρήστες και αλλαγές κωδικών γίνονται μόνο στο CRM.</p><p>Η απενεργοποίηση στο CRM διακόπτει και την πρόσβαση στην Academy. Τυχόν ξεχωριστή απενεργοποίηση παρακάτω αφορά μόνο την εκπαίδευση και διατηρεί την πρόοδο. Δεν αναιρεί απενεργοποίηση στο CRM.</p><?php if($manage): ?><a class="school-button" href="/crm/accounts.php?new=1">Νέος χρήστης στο Energiaki CRM →</a><?php endif; ?></section>
<?php elseif($manage): ?><details class="school-panel"><summary>+ Νέος εκπαιδευόμενος</summary><p>Δώσε τον προσωρινό κωδικό προσωπικά στον χρήστη, μέσω ασφαλούς καναλιού. Θα τον αλλάξει στην πρώτη σύνδεση. Δεν αποστέλλεται email αυτόματα.</p><form method="post" class="school-form school-form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="create"><label>Ονοματεπώνυμο<input name="name" maxlength="150" required autocomplete="off"></label><label>Email<input type="email" name="email" maxlength="254" required autocomplete="off"></label><label>Προσωρινός κωδικός<input type="password" name="password" minlength="12" maxlength="72" required autocomplete="new-password"></label><button class="school-button" type="submit">Δημιουργία λογαριασμού</button></form><p class="auth-note">Μελάς: Admin · Sophianos: Manager · Support: Technical (μόνο ανάγνωση λογαριασμών). Οι υπόλοιποι είναι εκπαιδευόμενοι.</p></details><?php endif; ?>
<section class="school-people"><?php foreach($accounts as $account): ?><article class="school-person"><header><div><h2><?= e($account['name']) ?></h2><p><?= e($account['email']) ?></p></div><span class="school-status"><?= $account['active']?'Ενεργός':'Ανενεργός' ?></span></header><p><?= e(academy_role_label($account['role'])) ?> · <?= academy_crm_enabled()?'Στοιχεία Energiaki CRM':($account['has_sso']?($account['has_local_password']?'Εταιρικό CRM + κωδικός Academy':'Μέσω εταιρικού CRM'):'Κωδικός Academy') ?></p><?php if($manage&&!academy_privileged_email($account['email'])): ?><form method="post" data-school-confirm="<?= $account['active']?'Θα διακοπεί η πρόσβαση αυτού του χρήστη μόνο στην Academy. Η πρόοδός του θα διατηρηθεί. Συνέχεια;':'Να επανενεργοποιηθεί η πρόσβαση στην Academy;' ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($account['id']) ?>"><input type="hidden" name="action" value="<?= $account['active']?'deactivate':'reactivate' ?>"><button class="school-button secondary" type="submit"><?= $account['active']?'Απενεργοποίηση':'Επανενεργοποίηση' ?></button></form><?php if(!academy_crm_enabled()&&$account['has_local_password']): ?><details><summary>Επαναφορά κωδικού</summary><form method="post" class="school-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($account['id']) ?>"><input type="hidden" name="action" value="reset"><label>Νέος προσωρινός κωδικός<input type="password" name="password" required minlength="12" maxlength="72" autocomplete="new-password"></label><button class="school-button" type="submit">Επαναφορά & λήξη συνεδριών</button></form></details><?php endif; endif; ?></article><?php endforeach; ?></section><?php render_footer(); ?>
