<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';$user=academy_require_login();require __DIR__.'/assessment-workflow.php';require_once __DIR__.'/grades-workflow.php';academy_call_schema();academy_assessment_schema();
$admin=academy_can_assess_training($user);$target=$user['id'];$error=null;
if($admin&&is_string($_GET['user_id']??null))$target=$_GET['user_id'];
if(!$admin&&isset($_GET['user_id'])&&$_GET['user_id']!==$user['id']){http_response_code(403);exit('Βλέπεις μόνο τη δική σου αξιολόγηση.');}
$q=db()->prepare('SELECT id,name,email FROM '.academy_table('users').' WHERE id=?');$q->execute([$target]);$learner=$q->fetch();if(!$learner){http_response_code(404);exit('Δεν βρέθηκε λογαριασμός.');}
$_SESSION['assessment_key']??=bin2hex(random_bytes(32));
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    verify_csrf();
    try{
        $key=academy_input('submission_key');if(!hash_equals($_SESSION['assessment_key'],$key))throw new InvalidArgumentException('Άνοιξε νέα φόρμα αξιολόγησης.');
        academy_assessment_save($user,$target,$_POST,$key);$_SESSION['assessment_key']=bin2hex(random_bytes(32));$_SESSION['notice']='Η αξιολόγηση αποθηκεύτηκε στο ιστορικό. Δεν άλλαξε πρόσβαση σε CRM.';redirect_to('assessment.php?user_id='.rawurlencode($target));
    }catch(InvalidArgumentException $e){http_response_code(422);$error=$e->getMessage();}
}
$q=db()->prepare('SELECT r.*,u.name assessor_name FROM '.academy_table('assessments').' r JOIN '.academy_table('users').' u ON u.id=r.assessor_id WHERE r.user_id=? ORDER BY r.created_at DESC,r.id DESC');$q->execute([$target]);$reviews=$q->fetchAll();
$people=$admin?db()->query('SELECT id,name,email FROM '.academy_table('users').' WHERE active=1 ORDER BY name')->fetchAll():[];
$simulations=academy_call_readiness(db(),academy_table_prefix(),$target);$gradeReport=academy_grade_report($user,$target);
render_header('Τελική αξιολόγηση & πρακτική',$user);
?>
<section class="ac-panel ac-lesson"><span class="ac-kicker">ΘΕΩΡΙΑ → ΠΡΑΚΤΙΚΗ → ΕΓΓΡΑΦΑ → ΕΓΚΡΙΣΗ CRM</span><h1>Τελική αξιολόγηση & πρακτική</h1><p>Ο τελικός βαθμός υπολογίζεται αυτόματα: quiz 10%, τελική εξέταση 70%, κλήσεις 20%. Η διοίκηση ελέγχει την ολοκλήρωση και αποφασίζει την έγκριση, χωρίς να αλλάζει αυθαίρετα τους βαθμούς. <?= e($learner['name']) ?></p><p>Sales Partner: 65/100. Διαδρομή Team Leader: 90/100. Για τελική αξιολόγηση απαιτούνται τουλάχιστον 3 επιτυχείς αυτόματες εικονικές κλήσεις από διαφορετικά σενάρια, με τουλάχιστον ένα από κάθε εταιρεία. Δεν απαιτούνται κλήσεις σε πραγματικούς πελάτες ή παρουσία εκπαιδευτή στις προσομοιώσεις. Σοβαρή παράβαση εμποδίζει έγκριση ανεξάρτητα από βαθμό.</p><p class="school-info">Η καταγραφή εδώ δεν αλλάζει ρόλο ή δικαιώματα σε κανένα CRM. Για νέους χρήστες, η επιτυχής ολοκλήρωση της Academy ξεκλειδώνει το επόμενο βήμα: έγγραφα, υπογραφές και αποδοχή πολιτικών. Η τελική ενεργοποίηση του πραγματικού CRM γίνεται χωριστά από τη διοίκηση στο Sales Partner Portal, αφού ολοκληρωθούν και τα έγγραφα. Οι εξαιρέσεις υπαρχόντων χρηστών παραμένουν.</p><p><a href="/crm/onboarding.php">Προσωπική διαδρομή πρόσβασης / έγγραφα →</a></p>
<?php if($admin): ?><form method="get" class="school-form"><label>Εκπαιδευόμενος<select name="user_id"><?php foreach($people as $person): ?><option value="<?= e($person['id']) ?>" <?= $person['id']===$target?'selected':'' ?>><?= e($person['name'].' · '.$person['email']) ?></option><?php endforeach; ?></select></label><button class="school-button">Προβολή</button></form><?php endif; ?>
<p class="school-info">Υπολογισμένος τελικός βαθμός: <strong><?= $gradeReport['total']===null?'Εκκρεμεί':number_format($gradeReport['total'],2,',','.').'/100' ?></strong>. <a href="<?= e(academy_url('grades.php?user_id='.rawurlencode($target))) ?>">Αναλυτική βαθμολογία →</a></p>
<?php if($error): ?><p class="school-error" role="alert"><?= e($error) ?></p><?php endif; ?>
<?php if($admin&&$target!==$user['id']): ?><details><summary>Νέα αξιολόγηση εκπαιδευτή</summary><form method="post" class="school-form"><?= csrf_field() ?><input type="hidden" name="submission_key" value="<?= e($_SESSION['assessment_key']) ?>">
<label>Διαδρομή<select name="target_track"><option value="sales_partner">Sales Partner · 65/100</option><option value="team_leader">Team Leader · 90/100</option></select></label>
<p>Η βαθμολογία προκύπτει από τις καταγεγραμμένες υποβολές. Δεν συμπληρώνεται χειροκίνητα. Η έγκριση αποθηκεύει στιγμιότυπο της ανάλυσης και των κλήσεων που συνυπολογίστηκαν.</p>
<label class="ac-choice"><input type="checkbox" name="critical_failure" value="1"><span>Σοβαρός λόγος απόρριψης: ψέμα, πλαστό lead, μη εξουσιοδοτημένη υπόσχεση, ψευδής τεχνική απάντηση, πίεση μετά από όχι ή ψευδή CRM στοιχεία.</span></label>
<p class="school-info">Η εικονική πρακτική ελέγχεται αυτόματα: <?= $simulations['ready']?'Ολοκληρωμένη':'Εκκρεμεί' ?>. Οι βαθμοί κάθε προσομοίωσης υπολογίζονται από το σύστημα· η συνολική ανασκόπηση της διοίκησης καταγράφεται εδώ.</p>
<p>Επιτυχή διαφορετικά σενάρια: <?= (int)$simulations['count'] ?>/5. <a href="<?= e(academy_url('supervised-calls.php?user_id='.rawurlencode($target))) ?>">Αναλυτική πρακτική και αποτελέσματα →</a></p>
<label>Αποτέλεσμα<select name="outcome"><?php foreach(academy_assessment_outcomes() as $key=>$label): ?><option value="<?= e($key) ?>"><?= e($label) ?></option><?php endforeach; ?></select></label>
<label>Τεκμηρίωση / ημερομηνίες πρακτικής / coaching<textarea name="evidence_notes" minlength="30" maxlength="5000" required placeholder="Περιέγραψε τις ασκήσεις, τις ημερομηνίες και όσα χρειάζονται βελτίωση. Όχι προσωπικά στοιχεία πελατών."></textarea></label><button class="school-button">Αποθήκευση αξιολόγησης</button></form></details><?php endif; ?>
<h2>Ιστορικό αξιολογήσεων</h2><?php if(!$reviews): ?><p>Δεν έχει καταχωριστεί ακόμη αξιολόγηση εκπαιδευτή.</p><?php endif; ?>
<?php foreach($reviews as $review): $scoreSnapshot=json_decode($review['scores_json'],true); ?><article class="ac-chapter"><h3><?= e(academy_assessment_outcomes()[$review['outcome']]??$review['outcome']) ?> · <?= number_format((float)($scoreSnapshot['weighted_total']??$review['total_score']),2,',','.') ?>/100</h3><p><?= e(format_datetime($review['created_at'])) ?> · <?= e($review['assessor_name']) ?> · <?= e($review['target_track']) ?> · βάση <?= (int)$review['threshold_score'] ?></p><p><?= (int)$review['rubric_version']>=3?'Αυτόματη εικονική πρακτική':'Ιστορικό role-play' ?>: <?= $review['roleplay_passed']?'Ναι':'Όχι' ?> · κλήσεις: <?= (int)$review['supervised_calls'] ?> · σοβαρή παράβαση: <?= $review['critical_failure']?'Ναι':'Όχι' ?></p><?php if((int)$review['rubric_version']>=4): ?><p>Σταθμισμένη αξιολόγηση 10% / 70% / 20% · αποθηκευμένο στιγμιότυπο.</p><ul><li>Quiz: <?= number_format((float)$scoreSnapshot['quiz_average'],2,',','.') ?>/100</li><li>Τελική εξέταση: <?= number_format((float)$scoreSnapshot['final_exam'],2,',','.') ?>/100</li><li>Όλες οι βαθμολογημένες κλήσεις: <?= number_format((float)$scoreSnapshot['calls_average'],2,',','.') ?>/100</li></ul><?php else: ?><p>Ιστορική αξιολόγηση με την προηγούμενη κλίμακα — δεν επανυπολογίστηκε.</p><ul><?php foreach($scoreSnapshot as $key=>$score): ?><li><?= e(academy_assessment_rubric()[$key][0]) ?>: <?= (int)$score ?>/<?= academy_assessment_rubric()[$key][1] ?></li><?php endforeach; ?></ul><?php endif; ?><p><?= nl2br(e($review['evidence_notes'])) ?></p></article><?php endforeach; ?>
<p class="ac-fineprint">Οι αξιολογήσεις δεν αντικαθίστανται σιωπηρά. Μια επανάληψη δημιουργεί νέα χρονολογημένη εγγραφή. Οι δύο εξουσιοδοτημένοι διαχειριστές βλέπουν την ομάδα· κάθε εκπαιδευόμενος μόνο τον εαυτό του.</p></section>
<?php render_footer(); ?>
