<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';$user=academy_require_login();require_once __DIR__.'/call-workflow.php';academy_call_schema();
$admin=academy_is_admin($user);$reviewer=academy_can_review_training($user);$target=$reviewer&&is_string($_GET['user_id']??null)?$_GET['user_id']:$user['id'];$error=null;
if(!$reviewer&&isset($_GET['user_id'])&&$_GET['user_id']!==$user['id']){http_response_code(403);exit('Βλέπεις μόνο τη δική σου πρακτική.');}
$q=db()->prepare('SELECT id,name FROM '.academy_table('users').' WHERE id=?');$q->execute([$target]);$learner=$q->fetch();if(!$learner){http_response_code(404);exit('Δεν βρέθηκε μαθητής.');}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    verify_csrf();
    try{
        $action=academy_input('action');
        if($action==='test_retake'&&$target===$user['id']){academy_call_test_retake($user,academy_input('scenario'));$id=academy_call_start($user,academy_input('scenario'),'assessment');redirect_to('call-run.php?id='.rawurlencode($id));}
        if($action==='start'&&$target===$user['id']){$id=academy_call_start($user,academy_input('scenario'),academy_input('mode'));redirect_to('call-run.php?id='.rawurlencode($id));}
        elseif($action==='grant')academy_call_grant($user,$target,academy_input('scenario'),academy_input('reason'));
        else throw new InvalidArgumentException('Μη έγκυρη ενέργεια. Οι παλιές κλήσεις είναι μόνο για ανάγνωση.');
        $_SESSION['notice']='Εγκρίθηκε μία επανεξέταση. Η πρώτη προσπάθεια παραμένει στο ιστορικό.';
        redirect_to('supervised-calls.php?user_id='.rawurlencode($target));
    }catch(InvalidArgumentException $e){http_response_code(422);$error=$e->getMessage();}
}
$state=academy_call_readiness(db(),academy_table_prefix(),$target);
$q=db()->prepare('SELECT * FROM '.academy_table('call_runs').' WHERE user_id=? ORDER BY created_at DESC,id DESC LIMIT 100');$q->execute([$target]);$history=$q->fetchAll();
$q=db()->prepare('SELECT g.*,u.name actor_name FROM '.academy_table('call_grants').' g JOIN '.academy_table('users').' u ON u.id=g.actor_id WHERE g.user_id=? ORDER BY g.created_at DESC');$q->execute([$target]);$grants=$q->fetchAll();
render_header('Εικονικές κλήσεις',$user);
?>
<div class="sim-shell">
<header class="sim-heading"><span class="ac-kicker">SALES SIMULATOR · ΧΩΡΙΣ ΠΡΑΓΜΑΤΙΚΟΥΣ ΠΕΛΑΤΕΣ</span><h1>Η επόμενη κλήση είναι δική σου.</h1><p>Διάβασε τη συνομιλία από τον πρώτο χαιρετισμό, επίλεξε πώς θα απαντήσεις και συμπλήρωσε την εκπαιδευτική καρτέλα. Οκτώ απαιτητικές αποφάσεις ανά σενάριο: ασαφής αρμοδιότητα, διαφορετικά μεγέθη, όροι πληρωμής, πίεση και όρια επικοινωνίας. Οι τέσσερις επιλογές μοιάζουν συχνά εύλογες, αλλά δεν είναι ισοδύναμες. Η συνομιλία γίνεται αποκλειστικά με κείμενο, χωρίς μικρόφωνο, ήχο, υπηρεσία τεχνητής νοημοσύνης ή χρέωση ανά κλήση.</p></header>
<?php if($admin): ?><form class="school-form" method="get"><label>Προβολή εκπαιδευόμενου<select name="user_id"><?php foreach(db()->query('SELECT id,name FROM '.academy_table('users').' WHERE active=1 ORDER BY name')->fetchAll() as $person): ?><option value="<?= e($person['id']) ?>" <?= $person['id']===$target?'selected':'' ?>><?= e($person['name']) ?></option><?php endforeach; ?></select></label><button class="school-button">Προβολή</button></form><?php endif; ?>
<?php if($error): ?><p class="school-error" role="alert"><?= e($error) ?></p><?php endif; ?>
<section class="sim-result <?= $state['ready']?'is-pass':'is-review' ?>"><div><span class="ac-kicker"><?= e($learner['name']) ?></span><h2><?= $state['ready']?'Η εικονική πρακτική ολοκληρώθηκε':'Από τη θεωρία στην πράξη' ?></h2><p>Για ολοκλήρωση χρειάζονται τουλάχιστον 3 διαφορετικά επιτυχή σενάρια από τα 5, με τουλάχιστον ένα από κάθε εταιρεία. Βάση ανά σενάριο: 65/100 και κανένα κρίσιμο λάθος.</p><p>Η εξάσκηση είναι ελεύθερη. Η βαθμολογούμενη προσπάθεια ξεκλειδώνει μετά την επιτυχή τελική εξέταση. Η τελική έγκριση πρόσβασης παραμένει στη διοίκηση.</p></div><strong class="sim-score"><?= (int)$state['count'] ?><small>/5</small></strong></section>
<?php if($target===$user['id']&&academy_can_test_retake($user)): ?><p class="school-info">ΠΡΟΣΩΠΙΚΗ ΔΟΚΙΜΗ SOPHIANOS: όλα τα σενάρια είναι διαθέσιμα αμέσως. Οι δοκιμές είναι επαναλήψιμες και δεν συνυπολογίζονται στον επίσημο βαθμό ή στην πιστοποίηση.</p><?php endif; ?>
<div class="sim-grid">
<?php foreach(academy_call_catalog() as $id=>$meta): $first=$state['first'][$id]??null;$last=$state['latest'][$id]??null; ?>
<article class="sim-card"><span class="sim-tag"><?= $meta['brand']==='melas'?'MELAS ENERGIAKI':'DISTILLOGIC' ?></span><h2><?= e($meta['title']) ?></h2><p><?= e($meta['summary']) ?></p><p class="sim-status"><?php if($first&&$first['status']==='submitted'): ?>Πρώτος βαθμός: <?= (int)$first['score'] ?>/100. <?= isset($state['passed'][$id])?'Η επιτυχία έχει καταγραφεί.':'Χρειάζεται ανασκόπηση.' ?><?php elseif($last): ?>Βαθμολογούμενη προσπάθεια σε εξέλιξη.<?php else: ?>Δεν έχει υποβληθεί βαθμολογούμενη προσπάθεια.<?php endif; ?></p>
<?php if($target===$user['id']): ?><div class="sim-form-actions"><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="start"><input type="hidden" name="scenario" value="<?= e($id) ?>"><input type="hidden" name="mode" value="guided"><button class="sim-secondary">Εξάσκηση</button></form><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="start"><input type="hidden" name="scenario" value="<?= e($id) ?>"><input type="hidden" name="mode" value="assessment"><button class="school-button"><?= academy_can_test_retake($user)?'Δοκιμή σεναρίου':($last?'Προσπάθεια / αποτέλεσμα':'Βαθμολογούμενη κλήση') ?></button></form></div>
<?php elseif($last): ?><a class="school-button" href="<?= e(academy_url('call-run.php?id='.$last['id'])) ?>">Προβολή προσπάθειας</a><?php endif; ?>
<?php if($target===$user['id']&&academy_can_test_retake($user)&&$last&&$last['status']==='submitted'): ?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="test_retake"><input type="hidden" name="scenario" value="<?= e($id) ?>"><p class="sim-fine">Προσωπικός έλεγχος Sophianos · διατήρηση πρώτου βαθμού.</p><button class="sim-secondary" type="submit">Νέα επανεξέταση δοκιμής</button></form><?php endif; ?>
<?php if($admin&&$target!==$user['id']&&$last&&$last['status']==='submitted'&&!isset($state['passed'][$id])): ?><details><summary>Έγκριση μίας επανεξέτασης</summary><form method="post" class="school-form"><?= csrf_field() ?><input type="hidden" name="action" value="grant"><input type="hidden" name="scenario" value="<?= e($id) ?>"><label>Αιτιολογία<textarea name="reason" required minlength="15" maxlength="2000"></textarea></label><button class="sim-secondary">Έγκριση επανεξέτασης</button></form></details><?php endif; ?>
</article><?php endforeach; ?></div>
<p class="sim-fine">Οι προσομοιώσεις γίνονται μόνο με κείμενο. Περιλαμβάνουν χαιρετισμό, σύσταση, διερεύνηση, αντιρρήσεις και κλείσιμο. Οι απαντήσεις σου καθορίζουν την πορεία της συζήτησης και ποια στοιχεία θα καταγραφούν στην εκπαιδευτική καρτέλα. Δεν αξιολογείται η φωνή ή η προφορά. Τα σενάρια είναι προκαθορισμένα, όχι ελεύθερη συνομιλία με τεχνητή νοημοσύνη.</p>
<p><a class="school-button" href="<?= e(academy_url('assessment.php'.($target===$user['id']?'':'?user_id='.rawurlencode($target)))) ?>">Τελική ανασκόπηση →</a></p>
<details class="sim-transcript"><summary>Ιστορικό προσομοιώσεων</summary><?php if(!$history): ?><p>Δεν υπάρχουν ακόμη προσπάθειες.</p><?php endif; ?><?php foreach($history as $row): ?><p><a href="<?= e(academy_url('call-run.php?id='.$row['id'])) ?>"><?= e(academy_call_catalog()[$row['scenario_id']]['title']??$row['scenario_id']) ?></a> · <?= $row['mode']==='test'?'Προσωπική δοκιμή':($row['mode']==='guided'?'Εξάσκηση':'Αξιολόγηση #'.(int)$row['attempt_number']) ?> · <?= e(format_datetime($row['created_at'])) ?> · <?= $row['score']!==null?(int)$row['score'].'/100':'Σε εξέλιξη' ?></p><?php endforeach; ?></details>
<?php if($grants): ?><details class="sim-transcript"><summary>Άδειες επανεξέτασης</summary><?php foreach($grants as $grant): ?><p><?= e(academy_call_catalog()[$grant['scenario_id']]['title']??$grant['scenario_id']) ?> · <?= e($grant['actor_name'].' · '.format_datetime($grant['created_at'])) ?> · <?= $grant['run_id']?'Χρησιμοποιήθηκε':'Διαθέσιμη' ?><br><?= e($grant['reason']) ?></p><?php endforeach; ?></details><?php endif; ?>
<?php $q=db()->prepare('SELECT c.*,u.name assessor_name FROM '.academy_table('supervised_calls').' c JOIN '.academy_table('users').' u ON u.id=c.assessor_id WHERE c.user_id=? ORDER BY c.occurred_at DESC');$q->execute([$target]);$legacy=$q->fetchAll();if($legacy): ?><details class="sim-transcript"><summary>Παλιές χειροκίνητες καταγραφές — ιστορικό</summary><p>Παραμένουν όπως καταχωρίστηκαν. Δεν χαρακτηρίζονται αναδρομικά ως αυτόματες προσομοιώσεις και δεν προσμετρώνται σε νέα αξιολόγηση.</p><?php foreach($legacy as $call): ?><article><h3><?= e($call['scenario']) ?> · <?= (int)$call['score'] ?>/100</h3><p><?= e(format_datetime($call['occurred_at']).' · '.$call['assessor_name']) ?></p><p><?= nl2br(e($call['feedback'])) ?></p></article><?php endforeach; ?></details><?php endif; ?>
</div><?php render_footer(); ?>
