<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';$user=require_login();ensure_lead_schema();$reviewer=can_view_all_sales_financials($user);$status=trim((string)($_GET['status']??''));$beneficiary=trim((string)($_GET['user_id']??''));
$where=[];$params=[];if(!$reviewer){$where[]='c.beneficiary_user_id=?';$params[]=$user['id'];}elseif($beneficiary!==''){$where[]='c.beneficiary_user_id=?';$params[]=$beneficiary;}if(in_array($status,['earned','payable','paid','cancelled'],true)){$where[]='c.status=?';$params[]=$status;}
$sql='SELECT c.*,l.submitted_by,l.contacts_released_at,l.lead_reference,l.company_name,u.name beneficiary_name,a.name approver_name FROM lead_commissions c JOIN sales_leads l ON l.id=c.lead_id JOIN users u ON u.id=c.beneficiary_user_id JOIN users a ON a.id=c.approved_by'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY c.created_at DESC';$q=db()->prepare($sql);$q->execute($params);$rows=$q->fetchAll();foreach($rows as &$row){if(!can_view_lead_identity($user,$row)){$row['company_name']='Προστατευμένο lead';$row['payment_reference']='';$row['notes']='';$row['cancellation_reason']='';$row['payout_reference']='';}}unset($row);
$totals=['earned'=>0.0,'payable'=>0.0,'paid'=>0.0,'cancelled'=>0.0];foreach($rows as $row)$totals[$row['status']]+=(float)$row['commission_amount'];$users=$reviewer?db()->query('SELECT id,name FROM users WHERE active=1 ORDER BY name')->fetchAll():[];
if(isset($_GET['export'])){header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="melas-commissions-'.date('Y-m-d').'.csv"');$out=fopen('php://output','wb');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,['Lead','Εταιρεία','Συνεργάτης','Τύπος','Βάση','Συντελεστής','Ποσό','Κατάσταση','Δημιουργία δικαιώματος','Πληρωμή','Ημερομηνία πληρωμής συνεργάτη','Αναφορά πληρωμής συνεργάτη','Ακύρωση','Αιτιολογία']);foreach($rows as $row)fputcsv($out,array_map('sales_csv_cell',[$row['lead_reference'],$row['company_name'],$row['beneficiary_name'],commission_type_label($row['commission_type']),$row['commission_type']==='panel_purchase'?$row['basis_quantity']:$row['basis_amount'],$row['rate'],number_format((float)$row['commission_amount'],2,'.',''),commission_status_label((string)$row['status']),$row['earned_at'],$row['paid_at'],$row['payout_date'],$row['payout_reference'],$row['cancelled_at'],$row['cancellation_reason']]),',','"','');fclose($out);exit;}
render_header('Προμήθειες',$user);
?>
<div class="page-heading"><div><span class="eyebrow">Commission ledger</span><h1>Προμήθειες συνεργατών</h1><p>Εγκεκριμένες, πληρωτέες και εξοφλημένες αμοιβές από qualified leads, panels και υπηρεσίες.</p></div><a class="button" href="<?= e(crm_url('commissions.php?'.http_build_query(array_merge($_GET,['export'=>1])))) ?>">Εξαγωγή CSV</a></div>
<div class="lead-stats commission-stats"><article><strong>€<?= e(number_format($totals['earned'],2,',','.')) ?></strong><span>Δεδουλευμένες</span></article><article><strong>€<?= e(number_format($totals['payable'],2,',','.')) ?></strong><span>Πληρωτέες</span></article><article><strong>€<?= e(number_format($totals['paid'],2,',','.')) ?></strong><span>Πληρωμένες</span></article><article><strong>€<?= e(number_format($totals['earned']+$totals['payable']+$totals['paid'],2,',','.')) ?></strong><span>Ενεργό σύνολο</span></article></div>
<form class="card search-card" method="get"><label>Κατάσταση<select name="status"><option value="">Όλες</option><option value="earned" <?= $status==='earned'?'selected':'' ?>>Δεδουλευμένες</option><option value="payable" <?= $status==='payable'?'selected':'' ?>>Πληρωτέες</option><option value="paid" <?= $status==='paid'?'selected':'' ?>>Πληρωμένες</option><option value="cancelled" <?= $status==='cancelled'?'selected':'' ?>>Ακυρωμένες</option></select></label><?php if($reviewer): ?><label>Συνεργάτης<select name="user_id"><option value="">Όλοι</option><?php foreach($users as $row): ?><option value="<?= e($row['id']) ?>" <?= $beneficiary===$row['id']?'selected':'' ?>><?= e($row['name']) ?></option><?php endforeach; ?></select></label><?php endif; ?><button class="button">Φιλτράρισμα</button></form>
<section class="card table-card"><div class="table-wrap"><table><thead><tr><th>Lead</th><th>Συνεργάτης</th><th>Τύπος</th><th>Βάση</th><th>Ποσό</th><th>Κατάσταση</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><a href="<?= e(crm_url('lead.php?id='.$row['lead_id'])) ?>"><strong><?= e($row['lead_reference']) ?></strong></a><br><?= e($row['company_name']) ?></td><td><?= e($row['beneficiary_name']) ?></td><td><?= e(commission_type_label($row['commission_type'])) ?></td><td><?= $row['commission_type']==='panel_purchase'?e(number_format((float)$row['basis_quantity'],0,',','.').' panels × €0,60'):($row['commission_type']==='service_revenue'?'€'.e(number_format((float)$row['basis_amount'],2,',','.')).' × '.e((string)$row['rate']).'%':'€'.e(number_format((float)$row['commission_amount'],2,',','.')).' qualified lead') ?></td><td><strong>€<?= e(number_format((float)$row['commission_amount'],2,',','.')) ?></strong></td><td><span class="commission-status status-<?= e($row['status']) ?>"><?= e(commission_status_label((string)$row['status'])) ?></span><?php if($row['status']==='paid'): ?><small><?= e(format_datetime($row['paid_at'])) ?></small><?php elseif($row['status']==='cancelled'&&$row['cancellation_reason']): ?><small><?= e($row['cancellation_reason']) ?></small><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php if(!$rows): ?><p class="empty-state">Δεν υπάρχουν προμήθειες σε αυτή την προβολή.</p><?php endif; ?></section>
<?php render_footer(); ?>
