<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
$user=require_login();ensure_customer_workspace_schema();
$id=trim((string)($_GET['id']??$_POST['id']??''));$existing=preg_match('/^[a-f0-9-]{36}$/i',$id)===1;$errors=[];$approvalEmail='melas@distillogic.gr';
$load=static function(string $documentId):array{$s=db()->prepare("SELECT d.*,c.name AS company_name,c.legal_name,c.email AS company_email,c.contact_name,c.contact_title,c.address,c.city,c.country,c.registration_number,c.vat_number FROM company_documents d JOIN companies c ON c.id=d.company_id WHERE d.id=? AND d.document_type='dpa' AND c.deleted_at IS NULL LIMIT 1");$s->execute([$documentId]);$r=$s->fetch();if(!$r){http_response_code(404);exit('Το DPA δεν βρέθηκε.');}return $r;};
$dpa=$existing?$load($id):null;$data=$dpa?(json_decode((string)$dpa['data_json'],true)?:[]):[];$companyId=(int)($dpa['company_id']??$_GET['company_id']??$_POST['company_id']??0);
$companies=db()->query("SELECT id,name,legal_name,email,contact_name,contact_title,address,city,country,postal_code,registration_number,vat_number FROM companies WHERE deleted_at IS NULL ORDER BY name")->fetchAll();$byId=[];foreach($companies as $row)$byId[(int)$row['id']]=$row;
$logo=static function():string{$site=rtrim((string)(crm_config()['app']['site_url']??'https://www.distillogic.gr'),'/');$path=dirname(__DIR__).'/assets/logo/distillogic-logo-light.svg';$content=is_file($path)?file_get_contents($path):false;return $content===false?$site.'/assets/logo/distillogic-logo-light.svg':'data:image/svg+xml;base64,'.base64_encode($content);};
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$action=(string)($_POST['action']??'save');
    contract_post_preflight($action,$errors,$dpa,'dpa',$user);
    if($dpa&&contract_action_requires_prerequisites($action)){$prerequisiteErrors=contract_prerequisite_errors((int)$dpa['company_id'],'dpa');if($prerequisiteErrors){$errors=array_merge($errors,$prerequisiteErrors);$action='blocked_by_contract_flow';}}
 if($action==='save'){
  $companyId=(int)($_POST['company_id']??0);$client=$byId[$companyId]??null;$email=trim((string)($_POST['client_email']??''));$confirm=trim((string)($_POST['client_email_confirm']??''));$effective=(string)($_POST['effective_date']??date('Y-m-d'));
  if(!$client)$errors[]='Επιλέξτε πελάτη.';if(!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Το email του πελάτη δεν είναι έγκυρο.';if(mb_strtolower($email)!==mb_strtolower($confirm))$errors[]='Τα δύο email του πελάτη δεν είναι ίδια.';if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$effective))$errors[]='Η ημερομηνία δεν είναι έγκυρη.';
  if(!$errors&&$client){$reference=$dpa?(string)$dpa['document_reference']:'DL-DPA-'.date('Ymd').'-'.$companyId.'-'.strtoupper(bin2hex(random_bytes(2)));$display=(new DateTimeImmutable($effective))->format('d/m/Y');
   $documentData=['dpa_reference'=>$reference,'version'=>trim((string)($_POST['version']??'1.0'))?:'1.0','effective_date'=>$effective,'effective_date_display'=>$display,'client_legal_name'=>trim((string)($_POST['client_legal_name']??''))?:((string)($client['legal_name']?:$client['name'])),'client_address'=>trim((string)($_POST['client_address']??'')),'client_registration'=>trim((string)($_POST['client_registration']??'')),'client_signer_name'=>trim((string)($_POST['client_signer_name']??'')),'client_signer_title'=>trim((string)($_POST['client_signer_title']??'')),'client_email'=>$email,'service_description'=>trim((string)($_POST['service_description']??'')),'processing_duration'=>trim((string)($_POST['processing_duration']??'')),'processing_purpose'=>trim((string)($_POST['processing_purpose']??'')),'processing_details'=>trim((string)($_POST['processing_details']??'')),'data_subjects'=>trim((string)($_POST['data_subjects']??'')),'personal_data_categories'=>trim((string)($_POST['personal_data_categories']??'')),'special_categories'=>trim((string)($_POST['special_categories']??'None expected'))?:'None expected','processing_frequency'=>trim((string)($_POST['processing_frequency']??'Continuous')),'retention_period'=>trim((string)($_POST['retention_period']??'')),'processing_country'=>trim((string)($_POST['processing_country']??'Greece / European Union')),'cloud_region'=>trim((string)($_POST['cloud_region']??'')),'other_location'=>trim((string)($_POST['other_location']??'N/A')),'security_measures'=>trim((string)($_POST['security_measures']??'')),'subprocessors'=>trim((string)($_POST['subprocessors']??'')),'international_transfers'=>trim((string)($_POST['international_transfers']??'None expected')),'client_security_contact'=>trim((string)($_POST['client_security_contact']??'')),'client_privacy_contact'=>trim((string)($_POST['client_privacy_contact']??'')),'distillogic_signer_name'=>'Spiros Melas','distillogic_signer_title'=>'Managing Director','distillogic_privacy_email'=>'melas@distillogic.gr','subprocessor_notice_days'=>'15','logo_url'=>$logo()];
   require_once __DIR__.'/dpa-template.php';$html=dpa_document_html($documentData);$file=preg_replace('/[^A-Za-z0-9._-]/','-',$reference.'-'.$documentData['client_legal_name']).'.doc';$json=json_encode($documentData,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
   if($dpa){$s=db()->prepare("UPDATE company_documents SET company_id=?,document_status='draft',title=?,file_name=?,mime_type='application/msword; charset=UTF-8',content=?,data_json=?,effective_date=?,client_signed_file_name=NULL,client_signed_pdf=NULL,client_signed_at=NULL,approval_code_hash=NULL,approval_code_expires_at=NULL,approval_attempts=0,approval_requested_at=NULL,approval_requested_by=NULL,approved_at=NULL,approval_confirmed_by=NULL,final_signed_file_name=NULL,final_signed_pdf=NULL,final_signed_at=NULL WHERE id=? AND document_type='dpa'");$s->execute([$companyId,'Data Processing Agreement - '.$documentData['client_legal_name'],$file,$html,$json,$effective,$id]);}
   else{$id=uuid_v4();$s=db()->prepare("INSERT INTO company_documents(id,company_id,created_by,document_type,document_status,document_reference,title,file_name,mime_type,content,data_json,effective_date) VALUES(?,?,?,'dpa','draft',?,?,?,'application/msword; charset=UTF-8',?,?,?)");$s->execute([$id,$companyId,$user['id'],$reference,'Data Processing Agreement - '.$documentData['client_legal_name'],$file,$html,$json,$effective]);}
   // Keep the manually maintained customer address separate from the document snapshot.
   db()->prepare('UPDATE companies SET legal_name=?,email=?,contact_name=?,contact_title=?,registration_number=? WHERE id=?')->execute([$documentData['client_legal_name'],$email,$documentData['client_signer_name']?:null,$documentData['client_signer_title']?:null,$documentData['client_registration']?:null,$companyId]);flash('success','Το DPA αποθηκεύτηκε ως draft.');redirect_to('dpa.php?id='.urlencode($id));
  }$data=$_POST;
 }
 if($dpa&&$action==='upload_client_signed'){$file=$_FILES['client_signed_pdf']??null;if($dpa['approved_at'])$errors[]='Το εγκεκριμένο DPA είναι κλειδωμένο.';elseif(!is_array($file)||(int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)$errors[]='Επιλέξτε το PDF που υπέγραψε ο πελάτης.';elseif((int)$file['size']<100||(int)$file['size']>15*1024*1024)$errors[]='Το PDF πρέπει να είναι έως 15 MB.';else{$tmp=(string)$file['tmp_name'];$content=is_uploaded_file($tmp)?file_get_contents($tmp):false;$mime=$content===false?'':(new finfo(FILEINFO_MIME_TYPE))->file($tmp);if($content===false||$mime!=='application/pdf'||substr($content,0,5)!=='%PDF-')$errors[]='Το αρχείο πρέπει να είναι πραγματικό PDF.';else{$name=preg_replace('/[^A-Za-z0-9._-]/','-',basename((string)$file['name']))?:'client-signed-dpa.pdf';db()->prepare("UPDATE company_documents SET document_status='client_signed',client_signed_file_name=?,client_signed_pdf=?,client_signed_at=NOW(),final_signed_file_name=NULL,final_signed_pdf=NULL,final_signed_at=NULL,approval_code_hash=NULL,approval_code_expires_at=NULL,approval_attempts=0,approved_at=NULL,approval_confirmed_by=NULL WHERE id=?")->execute([$name,$content,$id]);flash('success','Το client-signed DPA αποθηκεύτηκε. Ζητήστε CEO approval.');redirect_to('dpa.php?id='.urlencode($id));}}}
 if($dpa&&$action==='request_approval'){if(!$dpa['client_signed_pdf'])$errors[]='Ανεβάστε πρώτα το DPA που υπέγραψε ο πελάτης.';elseif($dpa['approved_at'])$errors[]='Το DPA έχει ήδη εγκριθεί.';else{$code=(string)random_int(100000,999999);$expires=(new DateTimeImmutable('+10 minutes'))->format('Y-m-d H:i:s');$mail='<div style="font-family:Arial;color:#10213a"><h2 style="color:#176afc">DPA approval</h2><p>CEO approval για <strong>'.e($dpa['document_reference']).'</strong> με <strong>'.e($dpa['company_name']).'</strong>.</p><p style="font-size:32px;font-weight:800;letter-spacing:8px;background:#eef5ff;padding:18px;text-align:center">'.e($code).'</p><p>Ο κωδικός λήγει σε 10 λεπτά.</p></div>';if(send_crm_email($approvalEmail,'DPA approval code - '.$dpa['document_reference'],$mail)){db()->prepare("UPDATE company_documents SET document_status='approval_pending',approval_code_hash=?,approval_code_expires_at=?,approval_attempts=0,approval_requested_at=NOW(),approval_requested_by=? WHERE id=?")->execute([password_hash($code,PASSWORD_DEFAULT),$expires,$user['id'],$id]);flash('success','Ο κωδικός στάλθηκε αποκλειστικά στο melas@distillogic.gr.');redirect_to('dpa.php?id='.urlencode($id));}$errors[]='Η αποστολή του κωδικού απέτυχε.';}}
 if($dpa&&$action==='verify_approval'){$code=preg_replace('/\D/','',(string)($_POST['approval_code']??''));if(strlen((string)$code)!==6)$errors[]='Ο κωδικός πρέπει να έχει 6 ψηφία.';elseif(!$dpa['approval_code_hash']||!$dpa['approval_code_expires_at'])$errors[]='Ζητήστε πρώτα κωδικό.';elseif(new DateTimeImmutable((string)$dpa['approval_code_expires_at'])<new DateTimeImmutable())$errors[]='Ο κωδικός έληξε.';elseif(!password_verify((string)$code,(string)$dpa['approval_code_hash'])){$errors[]='Ο κωδικός δεν είναι σωστός.';}else{db()->prepare("UPDATE company_documents SET document_status='approval_pending',approved_at=NOW(),approval_confirmed_by=?,approval_code_hash=NULL,approval_code_expires_at=NULL WHERE id=?")->execute([$user['id'],$id]);flash('success','Η έγκριση CEO επιβεβαιώθηκε. Δημιουργήστε τώρα την πλήρως υπογεγραμμένη έκδοση.');redirect_to('document-finalize.php?id='.urlencode($id));}}
 if($dpa&&$action==='send_final'){$d=json_decode((string)$dpa['data_json'],true)?:[];$email=trim((string)($d['client_email']??''));$confirm=trim((string)($_POST['send_email_confirm']??''));if(!$dpa['approved_at']||!$dpa['final_signed_pdf'])$errors[]='Δεν υπάρχει CEO-approved PDF.';elseif(!filter_var($email,FILTER_VALIDATE_EMAIL)||mb_strtolower($email)!==mb_strtolower($confirm))$errors[]='Πληκτρολογήστε ξανά σωστά το email του πελάτη.';else{$mail='<div style="font-family:Arial;color:#10213a"><h2 style="color:#176afc">Data Processing Agreement</h2><p>Dear '.e((string)($d['client_signer_name']??'Client')).',</p><p>Please find attached the approved Data Processing Agreement.</p><p>Reference: <strong>'.e($dpa['document_reference']).'</strong></p><p>DISTILLOGIC TECHNOLOGIES</p></div>';$attachment=[['filename'=>(string)$dpa['final_signed_file_name'],'mime'=>'application/pdf','content'=>(string)$dpa['final_signed_pdf']]];$sent=send_crm_email($email,'DISTILLOGIC Data Processing Agreement - '.$dpa['document_reference'],$mail,$attachment);$copy=send_crm_email($approvalEmail,'Copy: DISTILLOGIC DPA - '.$dpa['document_reference'],$mail,$attachment);if($sent&&$copy){db()->prepare("UPDATE company_documents SET document_status='sent' WHERE id=?")->execute([$id]);flash('success','Το εγκεκριμένο DPA στάλθηκε και στους δύο συμβαλλομένους.');redirect_to('dpa.php?id='.urlencode($id));}$errors[]='Η αποστολή δεν ολοκληρώθηκε και προς τις δύο διευθύνσεις.';}}
 if($existing&&!$errors){$dpa=$load($id);$data=json_decode((string)$dpa['data_json'],true)?:[];}
}
if(!$data){$c=$byId[$companyId]??null;$data=['effective_date'=>date('Y-m-d'),'version'=>'1.0','client_legal_name'=>$c?(string)($c['legal_name']?:$c['name']):'','client_address'=>$c?implode(', ',array_filter([(string)$c['address'],(string)$c['postal_code'],(string)$c['city']])):'','client_registration'=>$c['registration_number']??'','client_signer_name'=>$c['contact_name']??'','client_signer_title'=>$c['contact_title']??'','client_email'=>$c['email']??'','service_description'=>'','processing_duration'=>'Duration of the applicable Services','processing_purpose'=>'Processing necessary to provide the agreed software engineering and technology services.','processing_details'=>'Hosting, access, support, testing, integration, backup and deletion, as applicable.','data_subjects'=>'Client customers, employees, contractors and platform users, as applicable.','personal_data_categories'=>'Identity, contact, account, technical and business data actually required by the project.','special_categories'=>'None expected','processing_frequency'=>'Continuous','retention_period'=>'For the duration of the Services and according to documented Client instructions.','processing_country'=>'Greece / European Union','cloud_region'=>'','other_location'=>'N/A','security_measures'=>'Access control, encryption where appropriate, secure development, monitoring, backups and incident response.','subprocessors'=>'Only actual approved subprocessors should be listed.','international_transfers'=>'None expected','client_security_contact'=>'','client_privacy_contact'=>''];}
$contractPrerequisites=$dpa?contract_prerequisite_errors((int)$dpa['company_id'],'dpa'):[];$labels=['draft'=>'Draft','client_signed'=>'Client signed','approval_pending'=>'Pending CEO approval','approved_pdf'=>'CEO-approved PDF','sent'=>'Sent'];render_header($dpa?'DPA '.$dpa['document_reference']:'Νέο DPA',$user);
?>
<div class="page-heading"><div><p class="eyebrow">DATA PROCESSING AGREEMENT</p><h1><?= $dpa?e($dpa['document_reference']):'Νέο DPA' ?></h1><p>Client-specific GDPR συμφωνία Controller–Processor με annexes και ελεγχόμενη έγκριση.</p></div><div class="actions"><a class="button" href="<?= e(crm_url('dpas.php')) ?>">Όλα τα DPA</a><?php if($dpa): ?><a class="button primary" target="_blank" href="<?= e(crm_url('dpa-view.php?id='.urlencode($id))) ?>">Προβολή / Save PDF</a><?php endif; ?></div></div>
<?php if($errors): ?><div class="alert error"><?= e(implode(' ',array_unique($errors))) ?></div><?php endif; ?>
<?php if($contractPrerequisites): ?><div class="alert warning"><strong>Το signing flow είναι κλειδωμένο.</strong> <?= e(implode(' ',$contractPrerequisites)) ?> Μπορείτε μόνο να προετοιμάσετε το draft.</div><?php endif; ?>
<?php if($dpa&&$dpa['approved_at']&&$dpa['client_signed_pdf']&&!$dpa['final_signed_pdf']): ?><div class="alert info"><strong>Η CEO έγκριση ολοκληρώθηκε.</strong> Απομένει η τοποθέτηση της υπογραφής, της ημερομηνίας έγκρισης CEO και της σφραγίδας της DISTILLOGIC. <a class="button compact primary" href="<?= e(crm_url('document-finalize.php?id='.urlencode($id))) ?>">Δημιουργία Fully Signed PDF</a></div><?php endif; ?>
<?php if($dpa): ?><section class="card proposal-status-card"><div><span class="proposal-status proposal-status-<?= e($dpa['document_status']) ?>"><?= e($labels[$dpa['document_status']]??$dpa['document_status']) ?></span><h2><?= e($dpa['title']) ?></h2><p><?= e($dpa['company_name']) ?> · <?= e(format_datetime($dpa['updated_at'])) ?></p></div><div class="actions"><a class="button" href="<?= e(crm_url('customer.php?id='.(int)$dpa['company_id'])) ?>">Καρτέλα πελάτη</a><?php if($dpa['final_signed_pdf']): ?><a class="button primary" href="<?= e(crm_url('dpa-download.php?id='.urlencode($id).'&pdf=1')) ?>">Λήψη PDF</a><?php endif; ?></div></section><?php endif; ?>
<form method="post" class="stack proposal-editor"><?= csrf_field() ?><input type="hidden" name="action" value="save"><?php if($dpa): ?><input type="hidden" name="id" value="<?= e($id) ?>"><?php endif; ?><section class="card form-section"><header><h2>Συμβαλλόμενοι</h2><p>Επιβεβαιώστε το email δύο φορές πριν δημιουργηθεί το DPA.</p></header><div class="form-grid"><label>Πελάτης *<select name="company_id" required><?php foreach($companies as $company): ?><option value="<?= (int)$company['id'] ?>" <?= $companyId===(int)$company['id']?'selected':'' ?>><?= e($company['name']) ?></option><?php endforeach; ?></select></label><label>Effective date *<input type="date" name="effective_date" required value="<?= e($data['effective_date']??date('Y-m-d')) ?>"></label><label>Νομική επωνυμία *<input name="client_legal_name" required value="<?= e($data['client_legal_name']??'') ?>"></label><label>Registration / VAT<input name="client_registration" value="<?= e($data['client_registration']??'') ?>"></label><label class="field-full">Διεύθυνση<input name="client_address" value="<?= e($data['client_address']??'') ?>"></label><label>Υπογράφων πελάτη<input name="client_signer_name" value="<?= e($data['client_signer_name']??'') ?>"></label><label>Ιδιότητα<input name="client_signer_title" value="<?= e($data['client_signer_title']??'') ?>"></label><label>Email πελάτη *<input type="email" name="client_email" required value="<?= e($data['client_email']??'') ?>"></label><label>Επιβεβαίωση email *<input type="email" name="client_email_confirm" required autocomplete="off"></label></div></section>
<section class="card form-section"><header><h2>Annex 1 — Processing Details</h2></header><div class="form-grid"><label class="field-full">Service / project *<textarea name="service_description" required><?= e($data['service_description']??'') ?></textarea></label><label>Διάρκεια<input name="processing_duration" value="<?= e($data['processing_duration']??'') ?>"></label><label>Συχνότητα<input name="processing_frequency" value="<?= e($data['processing_frequency']??'') ?>"></label><label class="field-full">Σκοπός επεξεργασίας<textarea name="processing_purpose"><?= e($data['processing_purpose']??'') ?></textarea></label><label class="field-full">Φύση / εργασίες επεξεργασίας<textarea name="processing_details"><?= e($data['processing_details']??'') ?></textarea></label><label class="field-full">Κατηγορίες Data Subjects<textarea name="data_subjects"><?= e($data['data_subjects']??'') ?></textarea></label><label class="field-full">Κατηγορίες Personal Data<textarea name="personal_data_categories"><?= e($data['personal_data_categories']??'') ?></textarea></label><label class="field-full">Special categories<textarea name="special_categories"><?= e($data['special_categories']??'None expected') ?></textarea></label><label class="field-full">Retention period<textarea name="retention_period"><?= e($data['retention_period']??'') ?></textarea></label><label>Processing country<input name="processing_country" value="<?= e($data['processing_country']??'') ?>"></label><label>Cloud region<input name="cloud_region" value="<?= e($data['cloud_region']??'') ?>"></label></div></section>
<section class="card form-section"><header><h2>Security, subprocessors & transfers</h2></header><div class="form-grid"><label class="field-full">Technical & organisational measures<textarea name="security_measures"><?= e($data['security_measures']??'') ?></textarea></label><label class="field-full">Approved subprocessors<textarea name="subprocessors"><?= e($data['subprocessors']??'') ?></textarea></label><label class="field-full">International transfers / mechanism<textarea name="international_transfers"><?= e($data['international_transfers']??'None expected') ?></textarea></label><label>Client security contact<input name="client_security_contact" value="<?= e($data['client_security_contact']??'') ?>"></label><label>Client privacy / DPO contact<input name="client_privacy_contact" value="<?= e($data['client_privacy_contact']??'') ?>"></label></div><div class="actions"><button class="button primary"><?= $dpa?'Αποθήκευση νέας draft έκδοσης':'Δημιουργία DPA' ?></button></div></section></form>
<?php if($dpa): ?><section class="proposal-workflow"><article class="card signing-step <?= $dpa['client_signed_pdf']?'is-complete':'is-current' ?>"><div class="step-number">1</div><div><h2>Υπογραφή πελάτη</h2><p>Ανεβάστε το PDF που επέστρεψε υπογεγραμμένο.</p><form method="post" enctype="multipart/form-data"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($id) ?>"><input type="hidden" name="action" value="upload_client_signed"><input type="file" name="client_signed_pdf" accept="application/pdf,.pdf" required><button class="button primary" <?= $dpa['approved_at']?'disabled':'' ?>>Αποθήκευση client-signed PDF</button></form></div></article><article class="card signing-step <?= $dpa['approved_at']?'is-complete':($dpa['client_signed_pdf']?'is-current':'is-locked') ?>"><div class="step-number">2</div><div><h2>CEO Approval</h2><p>Ο 6ψήφιος κωδικός αποστέλλεται αποκλειστικά στο <strong>melas@distillogic.gr</strong>.</p><?php if(!$dpa['approved_at']): ?><form method="post"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($id) ?>"><button class="button primary" name="action" value="request_approval" <?= !$dpa['client_signed_pdf']?'disabled':'' ?>>Αποστολή κωδικού</button></form><form method="post" class="otp-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($id) ?>"><input type="hidden" name="action" value="verify_approval"><input name="approval_code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="000000" required><button class="button primary" <?= !$dpa['client_signed_pdf']?'disabled':'' ?>>Επιβεβαίωση CEO</button></form><?php else: ?><div class="step-success">✓ Εγκρίθηκε <?= e(format_datetime($dpa['approved_at'])) ?></div><?php endif; ?></div></article><article class="card signing-step <?= $dpa['approved_at']?'is-current':'is-locked' ?>"><div class="step-number">3</div><div><h2>Αποστολή και στους δύο συμβαλλομένους</h2><p>Επιβεβαιώστε το email του πελάτη: <strong><?= e($data['client_email']??'') ?></strong>. Αντίγραφο αποστέλλεται στο melas@distillogic.gr.</p><form method="post"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($id) ?>"><input type="hidden" name="action" value="send_final"><input type="email" name="send_email_confirm" required><button class="button primary" <?= !$dpa['approved_at']?'disabled':'' ?>>Αποστολή τελικού DPA</button></form></div></article></section><?php endif; ?>
<?php render_footer(); ?>
