<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';$user=require_login();ensure_lead_schema();$id=trim((string)($_GET['id']??''));$lead=load_lead($id);
if(!$lead){http_response_code(404);exit('Η ευκαιρία δεν βρέθηκε.');}if(!can_access_lead($user,$lead)){http_response_code(403);exit('Δεν έχετε πρόσβαση.');}
if(!can_edit_protected_lead($user,$lead)){http_response_code(403);exit('Μόνο ο αρχικός καταχωρητής μπορεί να συμπληρώσει ένα lead πριν την αποδοχή.');}
$data=json_decode((string)$lead['opportunity_data_json'],true)?:[];$errors=[];$statuses=lead_status_labels();$editableStages=['prospect','contacted','decision_maker_found','need_identified','qualification_in_progress','submitted'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$stage=(string)($_POST['status']??$lead['status']);if(!in_array($stage,$editableStages,true))$stage='submitted';$type=(string)($_POST['opportunity_type']??$lead['opportunity_type']);$email=strtolower(trim((string)($_POST['contact_email']??'')));$summary=trim((string)($_POST['conversation_summary']??''));
 if(trim((string)($_POST['company_name']??''))===''||trim((string)($_POST['country_region']??''))==='')$errors[]='Επωνυμία και περιοχή είναι υποχρεωτικά.';if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Το email δεν είναι έγκυρο.';
 if($stage==='submitted'){if(!sales_partner_ready($user))$errors[]='Η υποβολή για έγκριση απαιτεί εποπτευόμενη ή εγκεκριμένη εμπορική κατάσταση. Η πρόσβαση Academy παραμένει διαθέσιμη.';foreach(['contact_name','contact_title','contact_phone','contact_email','conversation_summary','next_step'] as $field)if(trim((string)($_POST[$field]??''))==='')$errors[]='Για υποβολή προς αξιολόγηση λείπουν υποχρεωτικά στοιχεία.';if(mb_strlen($summary)<80)$errors[]='Η σύνοψη πρέπει να έχει τουλάχιστον 80 χαρακτήρες.';if(!isset($_POST['contact_consent']))$errors[]='Απαιτείται συναίνεση επικοινωνίας.';}
 if(!$errors){foreach(['seller_authority','sale_intent_confirmed','panel_quantity','panel_watts','panel_brand','panel_model','panel_age','panel_technology','panel_condition','panel_location','availability_date','public_region','asking_price','asking_total_price','service_category','service_type','park_project','park_size','service_location','service_timing','decision_maker','rfq_available','incumbent_partner'] as $key)$data[$key]=trim((string)($_POST[$key]??''));synchronize_panel_prices($data);$follow=trim((string)($_POST['follow_up_at']??''));$follow=$follow!==''?(new DateTimeImmutable($follow))->format('Y-m-d H:i:s'):null;
  try{db()->beginTransaction();lead_registry_lock();$lock=db()->prepare('SELECT * FROM sales_leads WHERE id=? FOR UPDATE');$lock->execute([$id]);$fresh=$lock->fetch();if(!$fresh||!can_edit_protected_lead($user,$fresh))throw new RuntimeException('Το lead έχει ήδη γίνει αποδεκτό ή άλλαξε η πρόσβαση.');assert_lead_not_duplicate(trim((string)$_POST['company_name']),$email,$type,$id,$data);if(!isset(opportunity_type_labels()[$type]))throw new RuntimeException('Μη έγκυρος τύπος ευκαιρίας.');if($stage==='submitted'){$submissionErrors=lead_submission_errors($_POST,$data,$type);if($submissionErrors)throw new RuntimeException(implode(' ',$submissionErrors));}$q=db()->prepare('UPDATE sales_leads SET status=?,follow_up_at=?,follow_up_note=?,opportunity_type=?,company_name=?,website=?,country_region=?,contact_name=?,contact_title=?,contact_phone=?,contact_email=?,conversation_summary=?,next_step=?,next_step_other=?,contact_consent=?,lead_source=?,source_other=?,opportunity_data_json=? WHERE id=?');$q->execute([$stage,$follow,trim((string)($_POST['follow_up_note']??''))?:null,$type,trim((string)$_POST['company_name']),trim((string)($_POST['website']??''))?:null,trim((string)$_POST['country_region']),trim((string)($_POST['contact_name']??'')),trim((string)($_POST['contact_title']??'')),trim((string)($_POST['contact_phone']??'')),$email,$summary,trim((string)($_POST['next_step']??'')),trim((string)($_POST['next_step_other']??''))?:null,isset($_POST['contact_consent'])?1:0,trim((string)($_POST['lead_source']??'')),trim((string)($_POST['source_other']??''))?:null,json_encode($data,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),$id]);if($stage!==$lead['status']){$h=db()->prepare('INSERT INTO lead_status_history(id,lead_id,changed_by,old_status,new_status,note) VALUES(?,?,?,?,?,?)');$h->execute([uuid_v4(),$id,$user['id'],$lead['status'],$stage,'Συμπλήρωση / επανυποβολή στοιχείων']);}
   if(isset($_FILES['attachments'])&&is_array($_FILES['attachments']['name']))foreach($_FILES['attachments']['name'] as $i=>$name){$error=$_FILES['attachments']['error'][$i]??UPLOAD_ERR_NO_FILE;if($error===UPLOAD_ERR_NO_FILE)continue;if($error!==UPLOAD_ERR_OK||($_FILES['attachments']['size'][$i]??0)>8*1024*1024)throw new RuntimeException('Κάθε αρχείο πρέπει να είναι έως 8 MB.');$tmp=$_FILES['attachments']['tmp_name'][$i];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($tmp)?:'application/octet-stream';$allowed=['application/pdf','image/jpeg','image/png','image/webp','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/csv','message/rfc822'];if(!in_array($mime,$allowed,true))throw new RuntimeException('Μη επιτρεπόμενος τύπος αρχείου.');$a=db()->prepare('INSERT INTO lead_attachments(id,lead_id,uploaded_by,file_name,mime_type,size_bytes,file_content) VALUES(?,?,?,?,?,?,?)');$a->execute([uuid_v4(),$id,$user['id'],basename((string)$name),$mime,(int)$_FILES['attachments']['size'][$i],file_get_contents($tmp)]);}
   lead_record_event(load_lead($id),$user,'owner_updated','Συμπλήρωση / επανυποβολή από τον αρχικό καταχωρητή.');db()->commit();flash('success','Τα στοιχεία της ευκαιρίας ενημερώθηκαν.');redirect_to('lead.php?id='.$id);
  }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();error_log('Lead edit: '.$e->getMessage());$errors[]=$e instanceof RuntimeException?$e->getMessage():'Η ενημέρωση απέτυχε.';}
 }
}
$lead=array_merge($lead,$_POST);$data=array_merge($data,array_intersect_key($_POST,$data));if(!in_array((string)($lead['status']??''),$editableStages,true))$lead['status']='submitted';render_header('Επεξεργασία ευκαιρίας',$user);
?>
<div class="page-heading"><div><span class="eyebrow"><?= e($lead['lead_reference']) ?></span><h1>Επεξεργασία ευκαιρίας</h1><p>Συμπληρώστε τις πληροφορίες που λείπουν και επανυποβάλετε όταν η ευκαιρία είναι έτοιμη.</p></div><a class="button" href="<?= e(crm_url('lead.php?id='.$id)) ?>">Πίσω</a></div><?php if($errors): ?><div class="alert error"><?= e(implode(' ',array_unique($errors))) ?></div><?php endif; ?>
<form method="post" enctype="multipart/form-data" class="stack"><?= csrf_field() ?><section class="card form-section"><header><h2>Pipeline και εταιρεία</h2></header><div class="form-grid"><label>Στάδιο<select name="status"><?php foreach($editableStages as $key): ?><option value="<?= e($key) ?>" <?= ($lead['status']??'')===$key?'selected':'' ?>><?= e($statuses[$key]) ?></option><?php endforeach; ?></select></label><label>Τύπος<select name="opportunity_type"><?php foreach(opportunity_type_labels() as $key=>$label): ?><option value="<?= e($key) ?>" <?= $lead['opportunity_type']===$key?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label>Επωνυμία *<input name="company_name" required value="<?= e($lead['company_name']) ?>"></label><label>Website<input name="website" value="<?= e($lead['website']??'') ?>"></label><label>Γενική περιφέρεια (ορατή στην αξιολόγηση)<select name="public_region"><option value="">Δεν έχει οριστεί</option><?php foreach(lead_public_regions() as $key=>$label): ?><option value="<?= e($key) ?>" <?= ($data['public_region']??'')===$key?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label>Περιοχή *<input name="country_region" required value="<?= e($lead['country_region']) ?>"></label><label>Πηγή<input name="lead_source" value="<?= e($lead['lead_source']) ?>"></label></div></section>
<section class="card form-section"><header><h2>Επαφή και συζήτηση</h2></header><div class="form-grid"><label>Όνομα επαφής<input name="contact_name" value="<?= e($lead['contact_name']) ?>"></label><label>Ρόλος<input name="contact_title" value="<?= e($lead['contact_title']) ?>"></label><label>Τηλέφωνο<input name="contact_phone" value="<?= e($lead['contact_phone']) ?>"></label><label>Email<input type="email" name="contact_email" value="<?= e($lead['contact_email']) ?>"></label><label class="field-full">Σύνοψη<textarea name="conversation_summary"><?= e($lead['conversation_summary']) ?></textarea></label><label>Επόμενο βήμα<input name="next_step" value="<?= e($lead['next_step']) ?>"></label><label>Διευκρίνιση<input name="next_step_other" value="<?= e($lead['next_step_other']??'') ?>"></label><label>Follow-up<input type="datetime-local" name="follow_up_at" value="<?= !empty($lead['follow_up_at'])?e((new DateTimeImmutable($lead['follow_up_at']))->format('Y-m-d\TH:i')):'' ?>"></label><label>Σημείωση follow-up<input name="follow_up_note" value="<?= e($lead['follow_up_note']??'') ?>"></label><label class="field-full check-label"><input type="checkbox" name="contact_consent" value="1" <?= !empty($lead['contact_consent'])?'checked':'' ?>><span>Ο υπεύθυνος γνωρίζει και περιμένει επικοινωνία από τη MELAS ENERGIAKI.</span></label></div></section>
<section class="card form-section"><header><h2>Τεχνικά στοιχεία</h2></header><div class="form-grid"><?php foreach(['seller_authority'=>'Ιδιότητα πωλητή','sale_intent_confirmed'=>'Πρόθεση πώλησης','panel_quantity'=>'Ποσότητα','panel_watts'=>'Watt','panel_brand'=>'Μάρκα','panel_model'=>'Μοντέλο','panel_age'=>'Έτος / ηλικία','panel_technology'=>'Τεχνολογία','panel_condition'=>'Κατάσταση','panel_location'=>'Τοποθεσία panels','availability_date'=>'Διαθεσιμότητα','asking_price'=>'Ζητούμενη τιμή ανά πάνελ (€)','asking_total_price'=>'Ζητούμενη συνολική τιμή (€)','service_category'=>'Κατηγορία υπηρεσίας 01–11','service_type'=>'Ακριβής υπηρεσία','park_project'=>'Πάρκο / έργο','park_size'=>'Μέγεθος έργου','service_location'=>'Τοποθεσία υπηρεσίας','service_timing'=>'Χρονοδιάγραμμα','decision_maker'=>'Decision maker','rfq_available'=>'RFQ','incumbent_partner'=>'Υφιστάμενος συνεργάτης'] as $key=>$label): ?><label><?= e($label) ?><input <?= in_array($key,['panel_quantity','panel_watts','asking_price','asking_total_price'],true)?'type="number" min="0" step="'.($key==='panel_quantity'?'1':'0.01').'"':'' ?> name="<?= e($key) ?>" value="<?= e($data[$key]??'') ?>"></label><?php endforeach; ?><label class="field-full">Νέα αρχεία<input type="file" name="attachments[]" multiple></label></div></section><div class="actions"><button class="button primary">Αποθήκευση αλλαγών</button></div></form>
<script>(()=>{const q=document.querySelector('[name="panel_quantity"]'),u=document.querySelector('[name="asking_price"]'),t=document.querySelector('[name="asking_total_price"]');if(!q||!u||!t)return;let source=u;const calculate=()=>{const qty=parseFloat(q.value);if(!(qty>0))return;if(source===t&&parseFloat(t.value)>=0)u.value=(parseFloat(t.value)/qty).toFixed(2);else if(parseFloat(u.value)>=0)t.value=(parseFloat(u.value)*qty).toFixed(2)};u.addEventListener('input',()=>{source=u;calculate()});t.addEventListener('input',()=>{source=t;calculate()});q.addEventListener('input',calculate)})();</script>
<?php render_footer(); ?>
