<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
require_once __DIR__.'/contact-operations.php';
$user=require_login();ensure_lead_schema();contact_ops_schema();
$type=(string)($_GET['type']??'lead');$id=(string)($_GET['id']??'');
try {$subject=contact_ops_subject($user,$type,$id);}catch(Throwable){http_response_code(403);exit('Η επαφή δεν είναι διαθέσιμη για τον λογαριασμό σας.');}
$error=null;
if ($_SERVER['REQUEST_METHOD']==='POST') {
    verify_csrf();
    try {
        if (($_POST['action']??'')==='signals' && $type==='lead') contact_ops_save_signals($user,$id,$_POST);
        elseif (($_POST['action']??'')==='followup' && $type==='lead') contact_ops_followup($user,$id,$_POST);
        else contact_ops_update($user,$type,$id,$_POST);
        flash('success','Η ενέργεια καταγράφηκε. Δεν στάλθηκε μήνυμα στον πελάτη.');
        redirect_to('lead-operations.php?type='.urlencode($type).'&id='.urlencode($id));
    }catch(Throwable $e){$error=$e->getMessage();}
}
$state=contact_ops_state($subject);$manager=can_view_all_sales_financials($user);
$q=db()->prepare('SELECT e.*,u.name actor FROM crm_contact_events e LEFT JOIN users u ON u.id=e.actor_id WHERE subject_type=? AND subject_id=? ORDER BY e.id DESC LIMIT 30');$q->execute([$type,$id]);$events=$q->fetchAll();
render_header('Έλεγχος & επόμενο βήμα',$user);
?>
<link rel="stylesheet" href="<?= e(crm_url('operations-v33.css')) ?>">
<div class="page-heading"><div><span class="eyebrow">MELAS · Εσωτερική οργάνωση</span><h1><?= e($subject['name']) ?></h1><p>Η κατοχύρωση, η αξιολόγηση του lead και οι προμήθειες παραμένουν ανεξάρτητες από αυτόν τον έλεγχο.</p></div><a class="button" href="<?= e(crm_url(($type==='lead'?'lead.php':'customer.php').'?id='.urlencode($id))) ?>">← Καρτέλα</a></div>
<?php if($error): ?><div class="alert error" role="alert"><?= e($error) ?></div><?php endif; ?>
<section class="card ops-state <?= $state['blocked']?'ops-blocked':($state['cleared']?'ops-clear':'') ?>"><h2><?= $state['blocked']?'Μην επικοινωνήσεις · ενεργός αποκλεισμός':($state['cleared']?'Καταχωρισμένος έλεγχος τηλεφωνικής επικοινωνίας':'Εκκρεμεί έλεγχος επικοινωνίας') ?></h2><p>Ο αποκλεισμός DNC (Do Not Contact — να μη γίνει προωθητική επικοινωνία) ισχύει κεντρικά για τα καταχωρισμένα τηλέφωνα και email. Δεν είναι απλώς «δεν ενδιαφέρεται». Η ένδειξη ελέγχου αφορά τηλεφωνική επικοινωνία, όχι άδεια για email ή μαζικές αποστολές.</p><?php if($state['cleared']): ?><p>Ισχύς έως <?= e(format_datetime($state['check']['expires_at'])) ?>.</p><?php endif; ?><p class="muted">Χρησιμοποίησε κωδικό χώρας στα διεθνή τηλέφωνα. Η αντιστοίχιση αφορά τα καταχωρισμένα στοιχεία, όχι εξωτερική αναγνώριση εταιρείας. Δεν υπάρχει σύνδεση με εξωτερικά μητρώα ούτε αυτόματο τηλεφωνικό κέντρο. Η ένδειξη βασίζεται σε τεκμηριωμένο ανθρώπινο έλεγχο. Δεν μπορεί να εμποδίσει κλήση έξω από το CRM.</p></section>
<div class="ops-grid">
<?php if($type==='lead'): $sq=db()->prepare('SELECT * FROM crm_lead_signals WHERE lead_id=?');$sq->execute([$id]);$saved=$sq->fetch()?:[];$signals=json_decode($saved['signals_json']??'{}',true);$scores=contact_ops_score($signals); ?>
<section class="card"><h2>Fit & intent · καταλληλότητα και πρόθεση</h2><p>Οργανωτική κλίμακα 4 ενδείξεων ανά άξονα. Κάθε «ναι» μετρά 25 μονάδες. Το «άγνωστο» δεν θεωρείται αρνητική απάντηση, αλλά δεν προσθέτει μονάδες. Δεν υπάρχει αυτόματη απόφαση, εμπορικό όριο ή έγκριση προμήθειας.</p><form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="signals"><?php foreach(contact_ops_rubric() as $group=>$criteria): ?><fieldset><legend><?= $group==='fit'?'Καταλληλότητα':'Πρόθεση' ?>: <?= $scores[$group]['score'] ?>/100 · <?= $scores[$group]['known'] ?>/4 γνωστά</legend><?php foreach($criteria as $key=>$label): $field=$group.'_'.$key; ?><label><?= e($label) ?><select name="<?= e($field) ?>"><?php foreach(['unknown'=>'Άγνωστο / δεν ελέγχθηκε','yes'=>'Ναι — υπάρχει τεκμήριο','no'=>'Όχι'] as $value=>$text): ?><option value="<?= $value ?>" <?= ($signals[$field]??'unknown')===$value?'selected':'' ?>><?= e($text) ?></option><?php endforeach; ?></select></label><?php endforeach; ?></fieldset><?php endforeach; ?><label>Συνοπτικά τεκμήρια<textarea name="evidence" required minlength="10" maxlength="1000"><?= e($saved['evidence']??'') ?></textarea></label><button class="button primary">Αποθήκευση & υπολογισμός</button></form></section>
<?php endif; ?>
<?php if($type==='lead'): $lead=$subject['row'];$indicators=contact_ops_lead_indicators($lead); ?>
<section class="card"><h2>Πληρότητα πληροφοριών · <?= $indicators['percent'] ?>%</h2><progress max="100" value="<?= $indicators['percent'] ?>" aria-label="Πληρότητα πληροφοριών"></progress><ul><?php foreach($indicators['checks'] as $label=>$complete): ?><li><?= $complete?'✓':'○' ?> <?= e($label) ?></li><?php endforeach; ?></ul><p><?= e($indicators['intent']) ?></p><p class="muted">Δείκτης οργάνωσης, όχι εμπορικό fit score, επιβεβαίωση αλήθειας ή έγκριση των €80. Τα κριτήρια ποσότητας και υπηρεσίας αξιολογούνται από τον υπεύθυνο.</p></section>
<?php if(lead_is_owner($user,$lead)): ?><section class="card"><h2>Το επόμενο βήμα μου</h2><p>Εσωτερική εργασία ή follow-up. Σε αποκλεισμένη επαφή προγραμμάτισε μόνο εσωτερικό έλεγχο, όχι νέα προωθητική επικοινωνία.</p><form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="followup"><label>Ημερομηνία και ώρα<input name="follow_up_at" type="datetime-local" required value="<?= e($lead['follow_up_at']?date('Y-m-d\TH:i',strtotime($lead['follow_up_at'])):'') ?>"></label><label>Συγκεκριμένη ενέργεια<textarea name="follow_up_note" required minlength="5" maxlength="500"><?= e($lead['follow_up_note']??'') ?></textarea></label><button class="button primary">Αποθήκευση υπενθύμισης</button></form></section><?php endif; endif; ?>
<section class="card"><h2>Καταγραφή αντίρρησης</h2><p>Αν η επαφή ζήτησε να μη δέχεται προωθητικές επικοινωνίες, καταχώρισέ το άμεσα. Εφαρμόζεται σε όλα τα στοιχεία επικοινωνίας αυτής της καρτέλας και στις ίδιες τιμές άλλων καρτελών.</p><form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="block"><label>Τεκμηρίωση αιτήματος<textarea name="note" required minlength="10" maxlength="1000" placeholder="Πότε και με ποιον τρόπο ζητήθηκε η διακοπή; Χωρίς άσχετα προσωπικά δεδομένα."></textarea></label><button class="button">Καταχώριση κεντρικού αποκλεισμού</button></form></section>
<?php if($manager): ?><section class="card"><h2>Έλεγχος υπευθύνου</h2><p>Καταχώρισε την πηγή, ημερομηνία και αποτέλεσμα του πραγματικού ελέγχου των απαιτούμενων μητρώων/αντιρρήσεων ή του συγκεκριμένου αιτήματος της επαφής. Η εταιρεία παραμένει υπεύθυνη για τη νομιμότητα.</p><form method="post" class="stack"><?= csrf_field() ?><label>Ενέργεια<select name="action"><option value="clearance">Καταγραφή ελέγχου για κλήση</option><option value="revoke">Ανάκληση ελέγχου</option><option value="unblock">Άρση αποκλεισμού με νέο τεκμήριο</option></select></label><label>Λήξη ελέγχου (μόνο για νέο έλεγχο, έως 30 ημέρες)<input type="datetime-local" name="expires_at"></label><label>Τεκμηρίωση<textarea name="note" required minlength="10" maxlength="1000"></textarea></label><label class="ops-check"><input type="checkbox" name="confirmed" value="1"><span>Έλεγξα τα τεκμήρια. Η άρση αποκλεισμού δεν αποτελεί νέα άδεια επικοινωνίας· ακολουθεί ξεχωριστός έλεγχος.</span></label><button class="button primary">Καταχώριση απόφασης</button></form></section><?php endif; ?>
</div>
<section class="card"><h2>Ιστορικό ενεργειών</h2><?php if(!$events): ?><p>Δεν έχουν καταγραφεί ενέργειες.</p><?php endif; ?><?php foreach($events as $event): ?><article class="ops-event"><strong><?= e(['block'=>'Αποκλεισμός','unblock'=>'Άρση αποκλεισμού','clearance'=>'Έλεγχος κλήσης','revoke'=>'Ανάκληση ελέγχου','followup'=>'Επόμενο βήμα','signals'=>'Αξιολόγηση ενδείξεων'][$event['action']]??$event['action']) ?></strong><small><?= e($event['actor']??'Λογαριασμός') ?> · <?= e(format_datetime($event['created_at'])) ?></small><p><?= nl2br(e($event['note'])) ?></p></article><?php endforeach; ?></section>
<?php render_footer(); ?>
