<?php
declare(strict_types=1);

function nda_document_html(array $data): string
{
    $v = static fn(string $key, string $fallback = ''): string => e((string)($data[$key] ?? $fallback));
    $sections = [
        ['1. PURPOSE', 'The Parties wish to evaluate, discuss, negotiate and potentially enter into a commercial and/or technical cooperation relating to software engineering and development, systems integration, application modernisation, cloud, platform, data and artificial intelligence engineering, quality engineering, application management, project or work-package delivery, subcontracting, dedicated teams, staff augmentation, managed services, technical consulting, architecture, tender or framework cooperation, and related technology and professional services (the “Purpose”). Confidential Information shall be used solely for the Purpose.'],
        ['2. DEFINITION OF CONFIDENTIAL INFORMATION', '“Confidential Information” means any non-public information disclosed by one Party (the “Disclosing Party”) to the other (the “Receiving Party”), orally, visually, electronically, digitally, in writing, through demonstrations, meetings, system access or otherwise. It includes business plans, strategy, pricing, proposals, budgets, forecasts, customers, suppliers and tenders; software, architecture, source or object code, algorithms, APIs, schemas, infrastructure, credentials, security information, documentation, prototypes and know-how; project scope, requirements, schedules, risks and releases; personnel, CVs, profiles, availability and assessments; and personal data. Information is confidential where a reasonable business person would understand it to be confidential, whether or not marked as such.'],
        ['3. OBLIGATIONS OF THE RECEIVING PARTY', 'The Receiving Party shall use Confidential Information solely for the Purpose; protect it with no less than reasonable care; disclose it only as permitted by this Agreement; restrict access to persons with a legitimate need to know; copy it only where reasonably necessary; not commercially exploit it without a subsequent written agreement; maintain appropriate safeguards; and promptly notify the Disclosing Party of unauthorised access, loss, disclosure or misuse.'],
        ['4. PERMITTED RECIPIENTS', 'Confidential Information may be disclosed where necessary to directors, officers, employees, authorised contractors, approved subcontractors and professional advisers (“Permitted Recipients”). They must have a need to know, be informed of the confidential nature of the information and be bound by obligations no less protective than this Agreement. The Receiving Party remains responsible for breaches by its Permitted Recipients to the extent permitted by law.'],
        ['5. EXCLUSIONS', 'Confidential Information does not include information the Receiving Party can demonstrate was lawfully possessed before disclosure; becomes public without breach; is lawfully obtained from a third party without confidentiality restrictions; is independently developed without use of the Confidential Information; or is approved for public disclosure in writing. The Receiving Party bears the burden of establishing an exclusion.'],
        ['6. PERSONNEL, CV AND RESOURCE PROTECTION', 'Any CV, candidate or engineering profile, capability matrix, professional history, availability, assessment or commercial resource information disclosed by DISTILLOGIC is Confidential Information and may be used only to evaluate or perform an engagement with DISTILLOGIC. The Client shall not use it to bypass DISTILLOGIC or independently establish a commercial or employment relationship with introduced personnel, except as agreed in writing. Detailed non-solicitation or transfer terms may be agreed separately.'],
        ['7. PERSONAL DATA AND DATA PROTECTION', 'Each Party shall process personal data only as necessary for the Purpose, lawfully, fairly and transparently, in accordance with applicable data protection law, Regulation (EU) 2016/679 (GDPR) where applicable, and relevant Greek law. Appropriate technical and organisational measures shall be applied. Data shall not be collected unnecessarily, retained longer than required, disclosed to unauthorised persons or used for unrelated purposes. A separate Data Processing Agreement shall be entered into where legally required.'],
        ['8. SECURITY', 'Each Party shall take commercially reasonable security measures appropriate to the sensitivity of the information, including where suitable access controls, authentication, encryption, secure transfer, restricted repositories, secrets management, logging, endpoint and backup security. Neither Party is required to disclose credentials or grant access beyond what is reasonably necessary for the Purpose.'],
        ['9. COMPULSORY DISCLOSURE', 'A legally required disclosure is not a breach provided that, where legally permitted, the Receiving Party promptly notifies the Disclosing Party, reasonably cooperates in seeking protective treatment, discloses only the minimum legally required portion and requests confidential treatment where available.'],
        ['10. RETURN OR DESTRUCTION', 'Upon written request, or when discussions end where reasonably appropriate, the Receiving Party shall return or securely destroy Confidential Information and confirm destruction if requested. One archival copy may be retained for legal, regulatory, compliance, insurance, audit or dispute purposes. Information in automated backups need not be immediately deleted where technically impractical. Retained copies remain protected and shall be deleted under normal retention schedules.'],
        ['11. OWNERSHIP AND NO LICENCE', 'All Confidential Information remains the property of the Disclosing Party or its owner. Disclosure does not transfer ownership or grant any licence or right in source code, patents, copyright, trademarks, databases or other intellectual property, except as expressly agreed in writing.'],
        ['12. PRE-EXISTING INTELLECTUAL PROPERTY', 'Each Party retains ownership of intellectual property, methodologies, tools, software, frameworks, libraries, know-how, templates and materials developed before the engagement or independently of the other Party’s Confidential Information. Ownership of project deliverables shall be governed by the applicable commercial agreement or Statement of Work.'],
        ['13. NO REVERSE ENGINEERING OR UNAUTHORISED USE', 'Except where authorised in writing or permitted by mandatory law, neither Party shall use Confidential Information to reverse engineer software, reproduce proprietary systems, recreate proprietary architecture, derive source code, build competing functionality substantially based on disclosed confidential materials, or circumvent technical protection measures.'],
        ['14. NO REPRESENTATION OR WARRANTY', 'Confidential Information is supplied for evaluation and discussion. Unless agreed otherwise in writing, the Disclosing Party makes no representation or warranty regarding accuracy, completeness, fitness for purpose or future commercial availability. Each Party shall conduct its own evaluation.'],
        ['15. NO OBLIGATION TO TRANSACT', 'Nothing obliges either Party to award or accept a project or proposal, purchase or provide services, enter a partnership, employ personnel, subcontract work or enter any transaction. Either Party may terminate discussions at any time, subject to continuing confidentiality obligations.'],
        ['16. PUBLICITY AND USE OF NAME', 'Without prior written consent, neither Party may announce negotiations, issue a press release, use the other Party’s name, trademarks or logos, claim it as a client, supplier, partner or reference, or publish a related case study, except where disclosure is required by law.'],
        ['17. TERM', 'This Agreement remains in force for three (3) years from the Effective Date unless replaced by a subsequent written agreement.'],
        ['18. SURVIVAL', 'Confidentiality obligations survive termination or expiry for five (5) years from disclosure. Trade secrets remain protected for as long as they qualify as trade secrets under applicable law.'],
        ['19. TRADE SECRETS', 'Nothing limits protection available under applicable law for trade secrets, confidential know-how, proprietary business information or proprietary technical information.'],
        ['20. REMEDIES', 'Unauthorised disclosure or misuse may cause serious and irreparable harm. The affected Party may seek injunctive relief, interim measures, damages, compensation or any other remedy available by law. No predetermined contractual penalty is created unless separately agreed in writing.'],
        ['21. LIMITATION OF THE NDA', 'This Agreement governs confidentiality only. It does not establish scope, pricing, payment, service levels, milestones, warranties, acceptance, change management, personnel rates, liability caps, service credits or intellectual-property transfer for deliverables. These matters require separate commercial agreements.'],
        ['22. RELATIONSHIP OF THE PARTIES', 'Nothing creates a partnership, joint venture, agency, employment, fiduciary or exclusive relationship. Each Party acts as an independent contracting entity.'],
        ['23. ASSIGNMENT', 'Neither Party may assign this Agreement without prior written consent, except as part of a merger, restructuring, sale of substantially all relevant assets or acquisition, provided the successor assumes the obligations.'],
        ['24. NOTICES', 'Formal notices shall be in writing and may be sent by registered mail, courier or email to the authorised corporate contacts listed below. An electronic notice is deemed received when successful delivery can reasonably be demonstrated, subject to applicable law.'],
        ['25. GOVERNING LAW', 'This Agreement is governed by the laws of Greece, without prejudice to mandatory provisions of applicable law.'],
        ['26. JURISDICTION', 'Unless agreed otherwise in writing, the competent courts of Patras, Greece have exclusive jurisdiction, subject to mandatory jurisdictional rules.'],
        ['27. GOOD-FAITH RESOLUTION', 'Before formal proceedings, the Parties shall, where reasonably practicable, attempt in good faith to resolve disputes through authorised business or legal representatives. Either Party may still seek urgent interim or injunctive relief.'],
        ['28. ENTIRE AGREEMENT', 'This Agreement is the entire agreement concerning confidentiality for the Purpose and supersedes earlier oral or written confidentiality understandings concerning the same subject matter.'],
        ['29. AMENDMENTS', 'Any amendment must be in writing and agreed by authorised representatives of both Parties.'],
        ['30. WAIVER', 'Failure or delay to exercise a right is not a waiver. A waiver is effective only if expressly made in writing.'],
        ['31. SEVERABILITY', 'If any provision is invalid, unlawful or unenforceable, it shall be limited to the minimum extent necessary where possible, and the remaining provisions continue in force.'],
        ['32. COUNTERPARTS', 'This Agreement may be executed in counterparts, each deemed an original and all together constituting one agreement.'],
        ['33. ELECTRONIC SIGNATURES', 'This Agreement may be signed electronically where permitted by law. Electronic signatures and exchanged signed copies may be treated as valid counterparts of the original.'],
        ['34. AUTHORITY TO SIGN', 'Each signatory represents that they are authorised to bind the Party on whose behalf they sign.'],
    ];

    ob_start();
    ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><title><?= $v('document_reference') ?> — Mutual NDA</title>
<style>
@page{size:A4;margin:17mm 16mm 18mm}*{box-sizing:border-box}body{margin:0;color:#152235;background:#fff;font:10.4pt/1.48 Arial,Helvetica,sans-serif}.document{max-width:178mm;margin:auto}.brand{display:flex;align-items:center;justify-content:space-between;border-bottom:3px solid #1468ff;padding:0 0 12px;margin-bottom:24px}.brand img{width:210px;max-height:58px;object-fit:contain;object-position:left center}.brand-meta{text-align:right;font-size:9pt;color:#64748b}.confidential{color:#1468ff;font-weight:800;letter-spacing:.12em}.cover{min-height:242mm;display:flex;flex-direction:column}.cover h1{font-size:27pt;line-height:1.05;margin:44mm 0 8px;color:#07182e}.cover h2{font-size:15pt;margin:0;color:#1468ff}.cover .parties{margin-top:28mm;padding:20px;border:1px solid #cbd8e8;border-radius:12px;background:#f6f9fd}.cover .footer-note{margin-top:auto;border-top:1px solid #cbd8e8;padding-top:12px;color:#64748b;font-size:8.8pt}.page-break{break-before:page}.intro{margin-bottom:16px}.party-box{margin:12px 0;padding:14px 16px;border-left:4px solid #1468ff;background:#f4f8ff}.section{break-inside:avoid-page;margin:0 0 13px}.section h3{margin:0 0 5px;padding:7px 10px;border-radius:5px;background:#07182e;color:#fff;font-size:10.3pt;letter-spacing:.025em}.section p{margin:0;text-align:justify}.contacts{width:100%;border-collapse:collapse;margin:10px 0 16px}.contacts th{background:#07182e;color:#fff;text-align:left;padding:8px}.contacts td{border:1px solid #cbd8e8;padding:8px;vertical-align:top}.signature-page{break-before:page;min-height:250mm;display:flex;flex-direction:column}.signature-page h2{font-size:20pt;color:#07182e;border-bottom:3px solid #1468ff;padding-bottom:9px}.signature-intro{margin-bottom:24px}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:18px}.signature-card{border:1px solid #afbed0;border-radius:10px;padding:17px;min-height:188mm;display:flex;flex-direction:column}.signature-card h3{background:#07182e;color:#fff;margin:-17px -17px 18px;padding:12px 17px;border-radius:9px 9px 0 0}.line{height:31px;border-bottom:1px solid #596b80;margin:2px 0 10px}.signature-space{height:68px;border:1px dashed #7890aa;border-radius:8px;margin:4px 0 12px;display:flex;align-items:center;justify-content:center;color:#718399;font-size:8.7pt;font-weight:700}.stamp-space{margin-top:auto;height:72px;border:1px dashed #7890aa;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#718399;font-size:8.7pt;font-weight:700}.small{font-size:8.7pt;color:#64748b}.doc-footer{margin-top:20px;text-align:center;color:#64748b;font-size:8.5pt}@media print{.document{max-width:none}.section h3,.contacts th,.signature-card h3{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
.brand{gap:20px;padding-bottom:14px}.brand img{display:block;width:300px;max-width:58%;height:auto;max-height:none}.brand-meta{flex:0 0 auto;color:#526177}
.signature-page{min-height:0}.signatures,.signature-card{break-inside:avoid;page-break-inside:avoid}.signature-card{min-height:150mm}.stamp-space{margin-top:18px}.signature-intro{margin-bottom:16px}.doc-footer{margin-top:14px}
.section{break-inside:auto;page-break-inside:auto}.section h3{break-after:avoid;page-break-after:avoid}.section p{orphans:3;widows:3}.party-box,.contacts tr,.signatures,.signature-card{break-inside:avoid;page-break-inside:avoid}.contacts thead{display:table-header-group}.contacts tr{break-after:auto}.document>*+*{clear:both}
</style></head><body><main class="document">
<section class="cover"><div class="brand"><img src="<?= $v('logo_url') ?>" alt="DISTILLOGIC TECHNOLOGIES"><div class="brand-meta"><span class="confidential">CONFIDENTIAL</span><br><?= $v('document_reference') ?><br>Version 1.0 · <?= $v('document_date') ?></div></div><h1>MUTUAL<br>NON-DISCLOSURE<br>AGREEMENT</h1><h2>DISTILLOGIC TECHNOLOGIES × <?= $v('client_legal_name') ?></h2><div class="parties"><strong>Effective date</strong><br><?= $v('effective_date_display') ?><br><br><strong>Purpose</strong><br>Confidential evaluation and discussion of a potential technology and professional-services cooperation.</div><div class="footer-note"><strong>DISTILLOGIC TECHNOLOGIES</strong><br>Software Engineering &amp; Technology Delivery<br><br>This commercial template should be reviewed by qualified legal counsel before first execution, material amendment, foreign-law use or a high-value transaction.</div></section>
<section class="page-break"><div class="brand"><img src="<?= $v('logo_url') ?>" alt="DISTILLOGIC TECHNOLOGIES"><div class="brand-meta"><span class="confidential">CONFIDENTIAL</span><br><?= $v('document_reference') ?></div></div><p class="intro">This Mutual Non-Disclosure Agreement (the “Agreement”) is entered into as of <strong><?= $v('effective_date_display') ?></strong> by and between:</p><div class="party-box"><strong><?= $v('distillogic_legal_name') ?></strong>, trading as DISTILLOGIC TECHNOLOGIES, organised and existing under the laws of Greece, having its registered office at <?= $v('distillogic_address') ?>, VAT/Tax Identification Number <?= $v('distillogic_vat', '—') ?>, GEMI / Registration Number <?= $v('distillogic_gemi', '—') ?>, duly represented by <?= $v('distillogic_signatory_name') ?>, <?= $v('distillogic_signatory_title') ?> (“DISTILLOGIC”).</div><div class="party-box"><strong><?= $v('client_legal_name') ?></strong>, a company organised and existing under the laws of <?= $v('client_country') ?>, having its registered office at <?= $v('client_address') ?>, registration / VAT number <?= $v('client_registration') ?>, duly represented by <?= $v('client_representative_name') ?>, <?= $v('client_representative_title') ?> (“Client”).</div><p>DISTILLOGIC and the Client are each a “Party” and collectively the “Parties”.</p>
<?php foreach ($sections as [$heading, $body]): ?><section class="section"><h3><?= e($heading) ?></h3><p><?= e($body) ?></p></section><?php if ($heading === '24. NOTICES'): ?><table class="contacts"><thead><tr><th>DISTILLOGIC TECHNOLOGIES</th><th>CLIENT</th></tr></thead><tbody><tr><td><?= $v('distillogic_signatory_name') ?><br><?= $v('distillogic_signatory_title') ?><br><?= $v('distillogic_email') ?></td><td><?= $v('client_representative_name') ?><br><?= $v('client_representative_title') ?><br><?= $v('client_email') ?></td></tr></tbody></table><?php endif; ?><?php endforeach; ?></section>
<style>.bilateral-signatures{align-items:stretch}.bilateral-signatures .signature-card{height:158mm;min-height:158mm;display:flex;flex-direction:column}.signature-identity{min-height:54mm}.signature-controls{margin-top:auto}.signature-controls strong{display:block;margin:0 0 4px}.bilateral-signatures .signature-space{height:62px;margin:0 0 10px}.date-space{height:31px;border-bottom:1px solid #596b80;margin:0 0 10px;display:flex;align-items:center;color:#1468ff;font-weight:700}.bilateral-signatures .stamp-space{height:70px;margin:0}</style>
<section class="signature-page"><div class="brand"><img src="<?= $v('logo_url') ?>" alt="DISTILLOGIC TECHNOLOGIES"><div class="brand-meta"><span class="confidential">CONFIDENTIAL</span><br><?= $v('document_reference') ?></div></div><h2>SIGNATURES</h2><p class="signature-intro">The authorised representatives below agree to the terms of this Mutual Non-Disclosure Agreement.</p><div class="signatures bilateral-signatures"><div class="signature-card"><h3>For DISTILLOGIC</h3><div class="signature-identity"><strong>Legal Entity</strong><div><?= $v('distillogic_legal_name') ?></div><br><strong>Trading Name</strong><div>DISTILLOGIC TECHNOLOGIES</div><br><strong>Name</strong><div><?= $v('distillogic_signatory_name') ?></div><br><strong>Title</strong><div><?= $v('distillogic_signatory_title') ?></div></div><div class="signature-controls"><strong>Signature</strong><div class="signature-space">AUTHORISED SIGNATURE PLACEHOLDER</div><strong>Date</strong><div class="date-space"></div><strong>Stamp</strong><div class="stamp-space">COMPANY STAMP PLACEHOLDER</div></div></div><div class="signature-card"><h3>For the Client</h3><div class="signature-identity"><strong>Company</strong><div><?= $v('client_legal_name') ?></div><br><strong>Name</strong><div><?= $v('client_representative_name') ?></div><br><strong>Title</strong><div><?= $v('client_representative_title') ?></div></div><div class="signature-controls"><strong>Signature</strong><div class="signature-space">AUTHORISED SIGNATURE PLACEHOLDER</div><strong>Date</strong><div class="date-space"></div><strong>Stamp</strong><div class="stamp-space">COMPANY STAMP PLACEHOLDER</div></div></div></div><div class="doc-footer">DISTILLOGIC TECHNOLOGIES · Software Engineering &amp; Technology Delivery · <?= $v('document_reference') ?></div></section>
</main></body></html>
    <?php
    return (string)ob_get_clean();
}
