<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';$user=require_login();ensure_lead_schema();$manager=can_view_all_sales_financials($user);$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();try{
    match(sales_text($_POST,'action',1,30)){
      'read'=>sales_notification_read($user,sales_text($_POST,'event_key',64,64)),
      'activity'=>sales_activity_record($user,$_POST),
      'target'=>sales_target_save($user,$_POST),
      'grant'=>sales_staff_grant($user,$_POST),
      'email'=>db()->prepare('INSERT INTO sales_notification_preferences(user_id,email_enabled) VALUES(?,?) ON DUPLICATE KEY UPDATE email_enabled=VALUES(email_enabled)')->execute([$user['id'],($_POST['enabled']??'')==='1'?1:0]),
      default=>throw new InvalidArgumentException('Μη έγκυρη ενέργεια.')
    };flash('success','Η ενέργεια καταγράφηκε.');redirect_to('operations.php');
 }catch(Throwable $e){$error=$e instanceof InvalidArgumentException?$e->getMessage():'Η ενέργεια δεν ολοκληρώθηκε.';}
}
$month=is_string($_GET['month']??null)?$_GET['month']:date('Y-m');try{$report=sales_activity_report($user,$month);}catch(InvalidArgumentException){http_response_code(400);exit('Μη έγκυρος μήνας.');}
$feed=sales_notification_feed($user);$q=db()->prepare('SELECT email_enabled FROM sales_notification_preferences WHERE user_id=?');$q->execute([$user['id']]);$preference=$q->fetchColumn();
render_header('Εσωτερικές εργασίες',$user);
?>
<div class="page-heading"><div><h1>Εσωτερικές εργασίες</h1><p>Ενημερώσεις, πραγματικές εμπορικές ενέργειες και στόχοι ομάδας — χωρίς αυτόματη επικοινωνία με πελάτες.</p></div><a class="button" href="<?= e(crm_url('sales-portal.php')) ?>">Sales Portal</a></div>
<?php if($error): ?><p class="alert error"><?= e($error) ?></p><?php endif; ?>
<section class="card form-section"><h2>Οι ειδοποιήσεις μου</h2>
<?php foreach($feed as $notice): ?><article class="card"><a href="<?= e(crm_url($notice['url'])) ?>"><?= e($notice['label']) ?></a><?php if($notice['read']): ?><p>Αναγνωσμένη</p><?php else: ?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="read"><input type="hidden" name="event_key" value="<?= e($notice['key']) ?>"><button class="button small">Σημείωση ως αναγνωσμένη</button></form><?php endif; ?></article><?php endforeach; ?>
<?php if(!$feed): ?><p>Δεν υπάρχουν τρέχουσες ειδοποιήσεις.</p><?php endif; ?>
<form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="email"><label class="checkbox-row"><input type="checkbox" name="enabled" value="1" <?= $preference===false||$preference?'checked':'' ?>> Ημερήσιο email για μη αναγνωσμένες ενημερώσεις στο εταιρικό μου email</label><p>Μόνο διευθύνσεις @distillogic.gr / @melasenergiaki.gr. Απαιτείται η προγραμματισμένη εργασία του Plesk. Δεν στέλνονται κωδικοί, στοιχεία πελατών ή ποσά.</p><button class="button">Αποθήκευση προτίμησης</button></form></section>
<section class="card form-section"><h2>Καταγραφή πραγματικής ενέργειας</h2><p>Μία καταγραφή ανά πραγματική ενέργεια. Μην καταχωρίζετε δοκιμαστικές κλήσεις Academy εδώ. Οι αριθμοί δεν προκύπτουν αυτόματα από το πλήθος leads.</p><form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="activity"><input type="hidden" name="submission_id" value="<?= e(uuid_v4()) ?>"><label>Ενέργεια<select name="event_kind"><?php foreach(sales_activity_kinds() as $k=>$v): ?><option value="<?= e($k) ?>"><?= e($v) ?></option><?php endforeach; ?></select></label><label>Ημερομηνία<input name="happened_on" type="date" required value="<?= e(date('Y-m-d')) ?>" max="<?= e(date('Y-m-d')) ?>"></label><label>Σύντομη τεκμηρίωση (χωρίς τηλέφωνα ή εμπιστευτικά στοιχεία)<textarea name="note" minlength="10" maxlength="1000" required></textarea></label><button class="button primary">Καταγραφή</button></form></section>
<section class="card form-section"><h2>Μηνιαία δραστηριότητα και στόχοι</h2><form method="get"><label>Μήνας<input name="month" type="month" value="<?= e($month) ?>" required></label><button class="button">Εμφάνιση</button></form><p>Πραγματοποιημένες ενέργειες / στόχος. Η ίδια υπόθεση μπορεί να έχει περισσότερες κλήσεις· αυτοί οι αριθμοί δεν είναι ποσοστά μετατροπής μοναδικών πελατών.</p><div class="table-wrap"><table><thead><tr><th>Πρόσωπο</th><?php foreach(sales_activity_kinds() as $label): ?><th><?= e($label) ?></th><?php endforeach; ?></tr></thead><tbody><?php foreach($report as $row): ?><tr><td><?= e($row['name']) ?></td><?php foreach(sales_activity_kinds() as $kind=>$label): ?><td><?= (int)($row['actual'][$kind]??0) ?> / <?= isset($row['targets'][$kind])?(int)$row['targets'][$kind]:'—' ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div>
<?php if(sales_staff_can($user,'sales_manager')): ?><form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="target"><h3>Ορισμός στόχου</h3><label>Μέλος<select name="user_id"><?php foreach($report as $row): ?><option value="<?= e($row['id']) ?>"><?= e($row['name']) ?></option><?php endforeach; ?></select></label><label>Μήνας<input name="period_month" type="month" required value="<?= e($month) ?>"></label><label>Μέτρηση<select name="event_kind"><?php foreach(sales_activity_kinds() as $key=>$label): ?><option value="<?= e($key) ?>"><?= e($label) ?></option><?php endforeach; ?></select></label><label>Στόχος<input type="number" name="target_count" required min="0" max="100000"></label><button class="button">Αποθήκευση στόχου</button></form><?php endif; ?></section>
<?php if($manager): ?><section class="card form-section"><h2>Ξεχωριστές αρμοδιότητες</h2><p><a class="button" href="<?= e(crm_url('test-data-cleanup.php')) ?>">Έλεγχος και καθάρισμα δοκιμών Melas</a></p><p>Sales Manager: στόχοι της δικής του ομάδας. Trainer: εκπαιδευτική εποπτεία. Examiner: αξιολόγηση εκπαιδευομένων. Δεν αλλάζουν ρόλο CRM, πρόσβαση σε οικονομικά, έγκριση προμηθειών ή δικαίωμα προβολής ιστορικού συνδέσεων.</p><form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="grant"><label>Ενεργός λογαριασμός<select name="user_id"><?php foreach(db()->query('SELECT id,name FROM users WHERE active=1 ORDER BY name')->fetchAll() as $u): ?><option value="<?= e($u['id']) ?>"><?= e($u['name']) ?></option><?php endforeach; ?></select></label><label>Αρμοδιότητα<select name="capability"><option value="sales_manager">Sales Manager</option><option value="trainer">Trainer</option><option value="examiner">Examiner</option></select></label><label class="checkbox-row"><input type="checkbox" name="enabled" value="1"> Ενεργοποίηση (χωρίς επιλογή: ανάκληση)</label><label>Ο κωδικός μου<input type="password" name="actor_password" required autocomplete="current-password"></label><button class="button">Καταγραφή αρμοδιότητας</button></form><h3>Ενεργές αναθέσεις</h3><?php foreach(db()->query('SELECT c.capability,u.name FROM sales_staff_capabilities c JOIN users u ON u.id=c.user_id ORDER BY u.name,c.capability')->fetchAll() as $row): ?><p><?= e($row['name'].' · '.$row['capability']) ?></p><?php endforeach; ?><p>Αιτήσεις για εκκαθάριση μετά από 3 μήνες: <?= sales_applicant_retention(false) ?>. Η συντήρηση δεν διαγράφει λογαριασμούς, βαθμούς, μισθοδοσία ή συμβάσεις.</p></section><?php endif; ?>
<?php render_footer(); ?>
