<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';$user=current_user()??onboarding_session_user();
if(!$user)redirect_to('login.php');
$manage=can_manage_accounts($user)&&personnel_access_allowed($user);
personnel_schema();$draft=true;$reference='DL-HR-TEMPLATE';
if(isset($_GET['template'])){
    if(!$manage){http_response_code(403);exit('Δεν έχετε πρόσβαση.');}
    $q=db()->prepare('SELECT * FROM personnel_templates WHERE id=?');$q->execute([(string)$_GET['template']]);$t=$q->fetch();if(!$t){http_response_code(404);exit;}
    $data=['title'=>$t['title'],'body'=>$t['body'],'name'=>'[ΟΝΟΜΑ / ΕΠΩΝΥΜΙΑ]','email'=>'[EMAIL]','terms'=>'[Συμπληρώνονται τα ειδικά στοιχεία και οι όροι πριν από την έκδοση.]','template_id'=>$t['id']];
    $reference.='-'.substr($t['id'],0,8);
    if(str_starts_with($t['title'],'MELAS'))$data['brand']='MELAS ENERGEIAKI';
}else{
    try{$doc=personnel_document((string)($_GET['id']??''));}catch(InvalidArgumentException $error){http_response_code(404);exit;}
    $data=json_decode($doc['snapshot'],true,512,JSON_THROW_ON_ERROR);$reference=$doc['reference'];$draft=false;
    if(!$manage&&$doc['user_id']!==$user['id']){http_response_code(404);exit('Το έγγραφο δεν βρέθηκε.');}
}
$melas=($data['brand']??'')==='MELAS ENERGEIAKI';$policy=in_array($doc['kind']??$t['kind']??'',['commission_policy','crm_rules'],true);
header('Cache-Control: private, no-store');
?><!doctype html><html lang="el"><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><title><?= e($reference.' — '.$data['title']) ?></title><style>
@page{size:A4;margin:16mm}*{box-sizing:border-box}body{font:11pt/1.5 Arial,sans-serif;color:#15243b;background:white;margin:0}.sheet{max-width:178mm;margin:auto}header{display:flex;align-items:center;justify-content:space-between;border-bottom:2px solid #1769ff;padding-bottom:12px;gap:15px}header img{width:190px;max-height:65px}header small{font-size:9pt;text-align:right}h1{font-size:22pt;line-height:1.25;margin:24px 0 12px}h2{font-size:12pt;background:#1769ff;color:white;padding:7px 10px;border-radius:7px;break-after:avoid}p{margin:8px 0 14px;overflow-wrap:anywhere}.notice{border:1px solid #aac3ed;border-radius:9px;background:#f0f5ff;padding:12px;font-size:10pt}.terms{white-space:pre-wrap}.signatures{break-before:page;break-inside:avoid}.sign-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.sign-card{display:grid;grid-template-rows:52px 1fr;border:1px solid #aebfda;border-radius:12px;overflow:hidden}.sign-title{background:#1769ff;color:white;font-weight:bold;padding:12px}.sign-body{padding:16px;display:flex;flex-direction:column}.identity{min-height:185px;flex:1;overflow-wrap:anywhere}.identity p{margin:0 0 13px}.slot{flex-shrink:0;height:76px;border:1px dashed #7898c5;border-radius:9px;margin:8px 0 15px}.date{flex-shrink:0;height:43px;border-bottom:1px solid #526b8b;margin:4px 0 15px}.stamp{height:84px}footer{font-size:8pt;color:#536781;border-top:1px solid #b9c9df;margin-top:20px;padding-top:10px}.print-button{padding:12px 20px;margin:12px;background:#1769ff;color:white;border:0;border-radius:8px;cursor:pointer}@media print{.print-button{display:none}body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}@media screen{body{background:#edf2f8}.sheet{background:white;padding:25px;max-width:850px;margin:20px auto}.signatures{margin-top:40px}}@media screen and (max-width:600px){.sign-grid{grid-template-columns:1fr}header{flex-direction:column;align-items:flex-start}}
</style></head><body><button class="print-button" onclick="window.print()">Εκτύπωση / Αποθήκευση ως PDF</button><main class="sheet"><header><img src="<?= e(crm_url($melas?'assets/melas-energiaki-logo.png':'../assets/logo/distillogic-logo-light.svg')) ?>" alt="<?= $melas?'MELAS ENERGEIAKI':'DISTILLOGIC TECHNOLOGIES' ?>"><small>PERSONNEL · CONFIDENTIAL<br><?= e($reference) ?></small></header>
<h1><?= e($data['title']) ?></h1>
<?php if($draft): ?><p class="notice"><strong>ΠΡΟΣΧΕΔΙΟ / ΥΠΟΔΕΙΓΜΑ — ΟΧΙ ΓΙΑ ΥΠΟΓΡΑΦΗ.</strong> Απαιτούνται έλεγχος περιεχομένου από τη διοίκηση και νομικούς συμβούλους, συμπλήρωση όλων των ειδικών όρων και έκδοση από την καρτέλα προσώπου.</p><?php endif; ?>
<p><strong>Πρόσωπο:</strong> <?= e($data['name']) ?><br><strong>Email:</strong> <?= e($data['email']) ?><br><strong>Έκδοση προτύπου:</strong> <?= e($data['template_id']) ?></p>
<h2>ΕΙΔΙΚΑ ΣΤΟΙΧΕΙΑ ΚΑΙ ΟΡΟΙ</h2><p class="terms"><?= e($data['terms']) ?></p>
<?php foreach(preg_split('/\n\s*\n/u',$data['body']) as $section): $lines=explode("\n",$section,2); ?><section><?php if(count($lines)===2): ?><h2><?= e($lines[0]) ?></h2><p><?= nl2br(e($lines[1])) ?></p><?php else: ?><p><?= e($section) ?></p><?php endif; ?></section><?php endforeach; ?>
<?php if(!$policy): ?><section class="signatures"><h2>ΥΠΟΓΡΑΦΕΣ ΣΥΜΒΑΛΛΟΜΕΝΩΝ</h2><p>Οι υπογραφές αφορούν το πλήρες έγγραφο <?= e($reference) ?>, περιλαμβανομένων των ειδικών όρων. Η εταιρεία υπογράφει μετά το πρόσωπο.</p><div class="sign-grid">
<div class="sign-card"><div class="sign-title">For <?= $melas?'MELAS ENERGEIAKI':'DISTILLOGIC' ?></div><div class="sign-body"><div class="identity"><p><strong>Legal Entity</strong><br><?= $melas?'Όπως ορίζεται στα Ειδικά στοιχεία και όρους':'S. D. MELAS TRADING BUSINESS' ?></p><p><strong>Trading Name</strong><br><?= $melas?'MELAS ENERGEIAKI':'DISTILLOGIC TECHNOLOGIES' ?></p><p><strong>Name / Title</strong><br><?= $melas?'Νόμιμος εκπρόσωπος όπως ορίζεται στα Ειδικά στοιχεία':'Spiros Melas / Managing Director' ?></p></div><strong>Signature</strong><div class="slot"></div><strong>Date</strong><div class="date"></div><strong>Stamp</strong><div class="slot stamp"></div></div></div>
<div class="sign-card"><div class="sign-title">For the Individual / Partner</div><div class="sign-body"><div class="identity"><p><strong>Name / Legal Entity</strong><br><?= e($data['name']) ?></p><p><strong>Email</strong><br><?= e($data['email']) ?></p><p>Ιδιότητα / εκπροσώπηση: όπως ορίζεται στα ειδικά στοιχεία.</p></div><strong>Signature</strong><div class="slot"></div><strong>Date</strong><div class="date"></div><strong>Stamp (where applicable)</strong><div class="slot stamp"></div></div></div>
</div></section><?php else: ?><p class="notice">Η ανάγνωση και αποδοχή αυτής της έκδοσης καταγράφονται από το ίδιο το πρόσωπο στη σελίδα υποδοχής. Δεν αντικαθιστούν τις υπογραφές της σύμβασης και του NDA.</p><?php endif; ?><footer><?= $melas?'MELAS ENERGEIAKI':'DISTILLOGIC TECHNOLOGIES' ?> · <?= e($reference) ?> · Confidential personnel document</footer></main></body></html>
