<?php
declare(strict_types=1);

function engineering_profile_html(array $data): string
{
    $e=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
    $text=static function(string $key,string $fallback='Not specified')use($data,$e):string{$v=trim((string)($data[$key]??''));return nl2br($e($v!==''?$v:$fallback));};
    $list=static function(string $key)use($data,$e):string{$lines=preg_split('/\R+/',trim((string)($data[$key]??'')))?:[];$lines=array_values(array_filter(array_map('trim',$lines)));if(!$lines)return '<p class="muted">Not specified</p>';return '<ul>'.implode('',array_map(static fn($line)=>'<li>'.$e($line).'</li>',$lines)).'</ul>';};
    $block=static function(string $title,string $key)use($text):string{return '<div class="detail"><h3>'.htmlspecialchars($title,ENT_QUOTES,'UTF-8').'</h3><p>'.$text($key).'</p></div>';};
    $logo=(string)($data['logo_url']??'');
    $html='<!doctype html><html><head><meta charset="utf-8"><title>'.$e($data['profile_id']??'Engineering Profile').'</title><style>@page{size:A4;margin:16mm 16mm 18mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#142238;margin:0;font-size:10pt;line-height:1.42}.header{display:flex;align-items:center;justify-content:space-between;border-bottom:3px solid #176afc;padding-bottom:10px;margin-bottom:18px}.logo{width:165px;max-height:60px;object-fit:contain;object-position:left}.conf{color:#176afc;font-weight:800;letter-spacing:.12em;font-size:8pt}.hero{background:#071a33;color:#fff;padding:20px 22px;border-radius:14px;margin-bottom:15px}.hero h1{font-size:25pt;margin:0 0 5px}.hero p{margin:0;color:#bcd5ff;font-size:13pt}.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:14px}.fact{background:#f3f7fd;border:1px solid #c5d4e8;padding:8px;border-radius:8px}.fact b{display:block;color:#176afc;font-size:7.5pt;text-transform:uppercase}.fact span{font-weight:700}.section{margin:0 0 14px;break-inside:avoid}.section h2{font-size:12pt;color:#fff;background:#071a33;padding:7px 10px;margin:0 0 8px}.section h3,.detail h3{color:#176afc;font-size:9pt;text-transform:uppercase;margin:5px 0 2px}.section p,.detail p{margin:2px 0 6px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.detail{border:1px solid #c5d4e8;background:#f7faff;padding:8px;break-inside:avoid}.skills{display:grid;grid-template-columns:1fr 1fr;gap:7px}.skills .detail{min-height:55px}ul{margin:4px 0 6px;padding-left:18px}li{margin-bottom:2px}.experience{white-space:pre-line;border-left:3px solid #176afc;padding-left:11px}.notice{border:1px solid #c5d4e8;background:#f3f7fd;padding:10px;color:#45566d}.muted{color:#5a6b82}.footer{border-top:1px solid #c5d4e8;margin-top:18px;padding-top:8px;color:#5a6b82;font-size:8pt}@media print{.section{break-inside:avoid}.page-break{break-before:page}}</style></head><body><header class="header">';
    $html.='<style>.section{break-inside:auto!important;page-break-inside:auto!important}.section h2,.section h3,.detail h3{break-after:avoid;page-break-after:avoid}.section p,.detail p{orphans:3;widows:3}.grid,.skills{align-items:start}.detail,.fact,.notice{break-inside:avoid;page-break-inside:avoid;min-width:0;overflow-wrap:anywhere}.footer{margin-top:16px}</style>';
    if($logo!=='')$html.='<img class="logo" src="'.$e($logo).'" alt="DISTILLOGIC">';
    $html.='<span class="conf">COMMERCIAL CONFIDENTIAL</span></header><section class="hero"><h1>ENGINEERING PROFILE</h1><p>'.$text('primary_role').'</p></section><div class="facts"><div class="fact"><b>Profile ID</b><span>'.$text('profile_id').'</span></div><div class="fact"><b>Seniority</b><span>'.$text('seniority').'</span></div><div class="fact"><b>Location</b><span>'.$text('location').'</span></div><div class="fact"><b>Availability</b><span>'.$text('availability').'</span></div><div class="fact"><b>Engagement</b><span>'.$text('engagement_model').'</span></div><div class="fact"><b>Experience</b><span>'.$text('years_experience').'</span></div></div>';
    $html.='<section class="section"><h2>PROFESSIONAL SUMMARY</h2><p>'.$text('professional_summary').'</p><h3>Core Capabilities</h3>'.$list('core_capabilities').'</section>';
    $html.='<section class="section"><h2>TECHNICAL SKILLS</h2><div class="skills">';
    foreach(['languages'=>'Programming Languages','backend'=>'Backend','frontend'=>'Frontend','databases'=>'Databases','cloud'=>'Cloud','devops'=>'DevOps & Infrastructure','integration'=>'Integration','data_ai'=>'Data / AI','testing'=>'Testing','tools'=>'Tools']as$key=>$label)$html.=$block($label,$key);
    $html.='</div></section>';
    $html.='<section class="section"><h2>PROFESSIONAL EXPERIENCE</h2><div class="experience">'.$text('professional_experience').'</div></section>';
    $html.='<section class="section"><h2>SELECTED PROJECT EXPERIENCE</h2><div class="experience">'.$text('project_experience').'</div></section>';
    $html.='<section class="section"><h2>ENGINEERING & DELIVERY EXPERIENCE</h2><div class="grid">'.$block('Architecture & Engineering','architecture_experience').$block('Delivery Experience','delivery_experience').$block('Leadership','leadership_experience').$block('Industry Experience','industry_experience').'</div></section>';
    $html.='<section class="section"><h2>EDUCATION, CERTIFICATIONS & LANGUAGES</h2><div class="grid">'.$block('Education','education').$block('Certifications','certifications').$block('Languages','spoken_languages').$block('Availability & Travel','availability_details').'</div></section>';
    $html.='<section class="section"><h2>CLIENT ENGAGEMENT SUITABILITY</h2>'.$list('engagement_suitability').'<h3>Recommended DISTILLOGIC positioning</h3><p>'.$text('positioning').'</p></section>';
    $html.='<section class="section"><h2>PROFILE CONFIDENTIALITY</h2><p class="notice">This profile is provided solely to evaluate the individual’s suitability for a potential DISTILLOGIC engagement. It may not be distributed beyond authorised Client personnel, published, used for unrelated recruitment or provided to third parties without appropriate authorisation. Prior professional experience does not represent that the referenced organisation was a client of DISTILLOGIC TECHNOLOGIES.</p></section>';
    return $html.'<footer class="footer">DISTILLOGIC TECHNOLOGIES · Software Engineering &amp; Technology Delivery · '.$text('profile_id').'</footer></body></html>';
}
