<?php
declare(strict_types=1);

require __DIR__.'/bootstrap.php';
require __DIR__.'/profile-template.php';
$user=require_login();ensure_customer_workspace_schema();
if(!in_array($user['role'],['admin','manager'],true)){http_response_code(403);exit('Η πρόσβαση στα Engineering Profiles επιτρέπεται μόνο στη διοίκηση.');}
$id=trim((string)($_GET['id']??$_POST['id']??''));$isExisting=preg_match('/^[a-f0-9-]{36}$/i',$id)===1;$errors=[];
$load=static function(string $profileId):array{$s=db()->prepare('SELECT * FROM engineering_profiles WHERE id=? LIMIT 1');$s->execute([$profileId]);$r=$s->fetch();if(!$r){http_response_code(404);exit('Το Engineering Profile δεν βρέθηκε.');}return $r;};
$profile=$isExisting?$load($id):null;$data=$profile?(json_decode((string)$profile['data_json'],true)?:[]):[];
$companies=db()->query("SELECT id,name,legal_name FROM companies WHERE deleted_at IS NULL ORDER BY name")->fetchAll();
$companyId=(int)($_GET['company_id']??$_POST['company_id']??($profile['company_id']??0));
$verificationLabels=[
 'cv_reviewed'=>'CV reviewed','history_reviewed'=>'Professional history reviewed','technologies_reviewed'=>'Technologies reviewed','seniority_confirmed'=>'Seniority confirmed','availability_confirmed'=>'Availability confirmed','language_confirmed'=>'Language level confirmed','certifications_verified'=>'Certifications verified where applicable','sensitive_removed'=>'Client-sensitive information removed','candidate_consent'=>'Candidate consent obtained where required','client_shareable'=>'Client Shareable status confirmed',
];
$groups=[
 'Professional positioning'=>['professional_summary'=>'Professional summary','core_capabilities'=>'Core capabilities — one per line'],
 'Technical skills'=>['languages'=>'Programming languages','backend'=>'Backend','frontend'=>'Frontend','databases'=>'Databases','cloud'=>'Cloud','devops'=>'DevOps & infrastructure','integration'=>'Integration','data_ai'=>'Data / AI','testing'=>'Testing','tools'=>'Tools'],
 'Experience'=>['professional_experience'=>'Professional experience — Role / Company or industry / Dates / Responsibilities / Technologies','project_experience'=>'Selected project experience — Project / Industry / Role / Overview / Contribution / Technologies','architecture_experience'=>'Architecture & engineering experience','delivery_experience'=>'Delivery experience','leadership_experience'=>'Leadership experience','industry_experience'=>'Relevant industry experience'],
 'Education & availability'=>['education'=>'Education','certifications'=>'Certifications — only valid and verified','spoken_languages'=>'Languages and level','availability_details'=>'Availability, preferred engagement, travel and relocation'],
 'Client suitability'=>['engagement_suitability'=>'Suitable engagement types — one per line','positioning'=>'Recommended DISTILLOGIC positioning'],
];
$allKeys=[];foreach($groups as$group)foreach($group as$key=>$_)$allKeys[]=$key;
$logo=static function():string{$path=dirname(__DIR__).'/assets/logo/distillogic-logo-light.svg';$content=is_file($path)?file_get_contents($path):false;return $content===false?'':'data:image/svg+xml;base64,'.base64_encode($content);};
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$companyId=(int)($_POST['company_id']??0);$internalName=trim(mb_substr((string)($_POST['internal_name']??''),0,180));$primaryRole=trim(mb_substr((string)($_POST['primary_role']??''),0,180));$seniority=(string)($_POST['seniority']??'Senior');$allowedSeniorities=['Mid','Senior','Lead','Architect'];$status=(string)($_POST['profile_status']??'draft');$allowedStatuses=['draft','verified','shareable'];$verification=array_values(array_intersect(array_keys($verificationLabels),(array)($_POST['verification']??[])));
 if($internalName==='')$errors[]='Το εσωτερικό όνομα του engineer είναι υποχρεωτικό.';if($primaryRole==='')$errors[]='Ο κύριος ρόλος είναι υποχρεωτικός.';if(!in_array($seniority,$allowedSeniorities,true))$errors[]='Το seniority δεν είναι έγκυρο.';if(!in_array($status,$allowedStatuses,true))$errors[]='Η κατάσταση δεν είναι έγκυρη.';if($status==='shareable'&&count($verification)!==count($verificationLabels))$errors[]='Για Client Shareable κατάσταση πρέπει να ολοκληρωθούν όλοι οι έλεγχοι.';
 if(!$errors){$roleCode=strtoupper(preg_replace('/[^A-Za-z0-9]+/','-',trim($primaryRole))?:'ENG');$profileCode=$profile?(string)$profile['profile_id']:'DL-'.$roleCode.'-'.strtoupper(bin2hex(random_bytes(2)));$profileData=['profile_id'=>$profileCode,'internal_name'=>$internalName,'primary_role'=>$primaryRole,'seniority'=>$seniority,'profile_status'=>$status,'location'=>trim((string)($_POST['location']??'')),'availability'=>trim((string)($_POST['availability']??'')),'engagement_model'=>trim((string)($_POST['engagement_model']??'')),'years_experience'=>trim((string)($_POST['years_experience']??'')),'verification'=>$verification,'logo_url'=>$logo()];foreach($allKeys as$key)$profileData[$key]=trim(mb_substr((string)($_POST[$key]??''),0,20000));$html=engineering_profile_html($profileData);
  if($profile){db()->prepare('UPDATE engineering_profiles SET company_id=?,internal_name=?,primary_role=?,seniority=?,profile_status=?,data_json=?,content=? WHERE id=?')->execute([$companyId?:null,$internalName,$primaryRole,$seniority,$status,json_encode($profileData,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$html,$id]);}else{$id=uuid_v4();db()->prepare('INSERT INTO engineering_profiles (id,company_id,created_by,profile_id,internal_name,primary_role,seniority,profile_status,data_json,content) VALUES (?,?,?,?,?,?,?,?,?,?)')->execute([$id,$companyId?:null,$user['id'],$profileCode,$internalName,$primaryRole,$seniority,$status,json_encode($profileData,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$html]);}
  flash('success','Το Engineering Profile αποθηκεύτηκε. Το προσωπικό όνομα παραμένει μόνο μέσα στο CRM.');redirect_to('profile.php?id='.urlencode($id));
 }
 $data=array_merge($data,$_POST);$data['verification']=$verification;
}
if(!$data)$data=['seniority'=>'Senior','profile_status'=>'draft','engagement_model'=>'Remote / Hybrid','availability'=>'To be confirmed','certifications'=>'No certifications currently listed.','verification'=>[]];
$selectedVerification=(array)($data['verification']??[]);$statusLabels=['draft'=>'Draft - internal','verified'=>'Verified - internal','shareable'=>'Client Shareable'];
render_header($profile?'Engineering Profile '.$profile['profile_id']:'Νέο Engineering Profile',$user);
?>
<div class="page-heading"><div><p class="eyebrow">ENGINEERING CAPABILITY</p><h1><?= $profile?e($profile['profile_id']):'Νέο Engineering Profile' ?></h1><p>Client-facing προφίλ 2–4 σελίδων, χωρίς προσωπικά στοιχεία επικοινωνίας.</p></div><div class="actions"><a class="button" href="<?= e(crm_url('profiles.php')) ?>">Όλα τα profiles</a><?php if($profile): ?><a class="button primary" target="_blank" href="<?= e(crm_url('profile-view.php?id='.urlencode($id))) ?>">Προβολή / PDF</a><?php endif; ?></div></div>
<div class="alert info"><strong>Privacy control:</strong> Το εσωτερικό όνομα χρησιμοποιείται μόνο για αναζήτηση στο CRM και δεν εμφανίζεται στο client-facing profile.</div><?php if($errors): ?><div class="alert error"><?= e(implode(' ',array_unique($errors))) ?></div><?php endif; ?>
<form method="post" class="stack proposal-editor"><?= csrf_field() ?><?php if($profile): ?><input type="hidden" name="id" value="<?= e($id) ?>"><?php endif; ?>
<section class="card form-section"><header><h2>1. Profile control</h2><p>Η σύνδεση με πελάτη χρησιμοποιείται μόνο για την οργάνωση του CRM και δεν εμφανίζεται στο client-facing PDF.</p></header><div class="form-grid"><label>Σύνδεση με πελάτη<select name="company_id"><option value="0">Χωρίς συγκεκριμένο πελάτη</option><?php foreach($companies as$company): ?><option value="<?= (int)$company['id'] ?>" <?= $companyId===(int)$company['id']?'selected':'' ?>><?= e($company['legal_name']?:$company['name']) ?></option><?php endforeach; ?></select></label><label>Εσωτερικό όνομα engineer *<input name="internal_name" required value="<?= e($data['internal_name']??'') ?>"></label><label>Primary role *<input name="primary_role" required value="<?= e($data['primary_role']??'') ?>" placeholder="Senior Backend Engineer"></label><label>Seniority<select name="seniority"><?php foreach(['Mid','Senior','Lead','Architect']as$v): ?><option <?= ($data['seniority']??'')===$v?'selected':'' ?>><?= e($v) ?></option><?php endforeach; ?></select></label><label>Κατάσταση<select name="profile_status"><?php foreach($statusLabels as$v=>$label): ?><option value="<?= e($v) ?>" <?= ($data['profile_status']??'draft')===$v?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label>Location<input name="location" value="<?= e($data['location']??'') ?>"></label><label>Availability<input name="availability" value="<?= e($data['availability']??'') ?>"></label><label>Engagement model<input name="engagement_model" value="<?= e($data['engagement_model']??'') ?>"></label><label>Years of experience<input name="years_experience" value="<?= e($data['years_experience']??'') ?>" placeholder="8+ years"></label></div></section>
<?php $number=2;foreach($groups as$title=>$fields): ?><section class="card form-section"><header><h2><?= $number++ ?>. <?= e($title) ?></h2></header><div class="form-grid"><?php foreach($fields as$key=>$label): ?><label class="field-full"><?= e($label) ?><textarea name="<?= e($key) ?>" rows="4"><?= e($data[$key]??'') ?></textarea></label><?php endforeach; ?></div></section><?php endforeach; ?>
<section class="card form-section"><header><h2><?= $number ?>. Profile verification</h2><p>Όλα τα checks απαιτούνται πριν γίνει Client Shareable.</p></header><div class="proposal-section-picker"><?php foreach($verificationLabels as$key=>$label): ?><label><input type="checkbox" name="verification[]" value="<?= e($key) ?>" <?= in_array($key,$selectedVerification,true)?'checked':'' ?>><span><?= e($label) ?></span></label><?php endforeach; ?></div><div class="actions"><button class="button primary" type="submit"><?= $profile?'Αποθήκευση profile':'Δημιουργία profile' ?></button></div></section></form>
<?php render_footer(); ?>
