<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
$user=require_login();ensure_lead_schema();$manager=can_view_all_sales_financials($user);
$error=null;$tabs=['overview'=>'Η εικόνα μου','pipeline'=>'Pipeline','requests'=>'Αιτήματα','teams'=>'Ομάδες','overrides'=>'Team Leader αμοιβές','toolkit'=>'Sales toolkit'];
$tabs['development']='Πορεία συνεργάτη';$tabs['ownership']='Πελατολόγιο';
$tabs['recurring']='Επαναλαμβανόμενες υπηρεσίες';
if($manager)$tabs['applicants']='Υποψηφιότητες';
$tab=is_string($_GET['tab']??null)?$_GET['tab']:'overview';if(!isset($tabs[$tab])){http_response_code(404);exit('Δεν βρέθηκε.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try {
        match(sales_text($_POST,'action',1,40)){
            'create_team'=>sales_create_team($user,$_POST),
            'assign_team'=>sales_assign_team($user,$_POST),
            'close_team'=>sales_close_team($user,$_POST),
            'pay_override'=>sales_pay_override($user,$_POST),
            'pipeline'=>sales_update_pipeline($user,$_POST),
            'request'=>sales_create_request($user,$_POST),
            'resolve'=>sales_resolve_request($user,$_POST),
            'partner_stage'=>sales_update_partner($user,$_POST),
            'account_owner'=>sales_assign_account($user,$_POST),
            'publish_toolkit'=>sales_publish_toolkit($user,$_POST),
            'acknowledge'=>sales_acknowledge_toolkit($user,sales_text($_POST,'version_id',1,36)),
            'create_recurring'=>sales_create_recurring($user,$_POST),
            'recurring_receipt'=>sales_recurring_receipt($user,$_POST),
            'close_recurring'=>sales_close_recurring($user,$_POST),
            'review_applicant'=>sales_review_applicant($user,$_POST),
            default=>throw new InvalidArgumentException('Μη έγκυρη ενέργεια.'),
        };
        flash('success','Η ενέργεια καταγράφηκε.');redirect_to('sales-portal.php?tab='.$tab);
    }catch(Throwable $e){$error=$e instanceof PDOException?'Η αποθήκευση δεν ολοκληρώθηκε. Επικοινωνήστε με τον διαχειριστή.':$e->getMessage();if($e instanceof PDOException)error_log($e->getMessage());}
}
$memberIds=sales_member_ids($user);$scope=array_values(array_unique(array_merge([$user['id']],$memberIds)));
$params=$manager?[]:$scope;$where=$manager?'1=1':'l.submitted_by IN ('.implode(',',array_fill(0,count($scope),'?')).')';
$leads=sales_page_query('SELECT l.*,u.name submitter_name,p.stage pipeline_stage,p.temperature,p.priority,p.last_contact_at FROM sales_leads l JOIN users u ON u.id=l.submitted_by LEFT JOIN sales_lead_pipeline p ON p.lead_id=l.id WHERE '.$where.' ORDER BY l.updated_at DESC,l.id DESC',$params,'leads');
$myLeads=array_values(array_filter($leads,fn($l)=>$l['submitted_by']===$user['id']));
$q=db()->prepare("SELECT status,COALESCE(SUM(commission_amount),0) total FROM lead_commissions WHERE beneficiary_user_id=? GROUP BY status");$q->execute([$user['id']]);$totals=$q->fetchAll(PDO::FETCH_KEY_PAIR);
$users=$manager?db()->query('SELECT id,name,email FROM users WHERE active=1 ORDER BY name')->fetchAll():[];
render_header('Sales Partner Portal',$user);
?>
<div class="page-heading"><div><span class="eyebrow">MELAS · SALES OPERATIONS</span><h1><?= e($tabs[$tab]) ?></h1><p>Η εργασία, η εκπαίδευση και τα επόμενα βήματά σου. Για νέους χρήστες: Academy πρώτα, μετά υπογραφές και τελική έγκριση CRM.</p></div><a class="button primary" href="<?= e(crm_url('new-lead.php')) ?>">Νέα ευκαιρία</a></div>
<p class="actions"><a class="button" href="operations.php">Εσωτερικές εργασίες / στόχοι</a><a class="button" href="settlements.php">Μηνιαίες εκκαθαρίσεις</a><a class="button" href="toolkit-files.php">Αρχεία πωλήσεων</a></p><nav class="portal-tabs" aria-label="Sales portal"><?php foreach($tabs as $key=>$label): ?><a class="button <?= $tab===$key?'primary':'' ?>" <?= $tab===$key?'aria-current="page"':'' ?> href="<?= e(crm_url('sales-portal.php?tab='.$key)) ?>"><?= e($label) ?></a><?php endforeach; ?></nav>
<?php if($error): ?><div class="alert error" role="alert"><?= e($error) ?></div><?php endif; ?>
<?php if($tab==='overview'): ?>
<section class="card form-section"><h2><?= $manager?'Συνολική εμπορική εικόνα':($memberIds?'Η ομάδα μου και οι ευκαιρίες μου':'Οι ευκαιρίες μου') ?></h2><p>Πλήθος ανά εμπορικό στάδιο, χωρίς περιορισμό στις 200 πρόσφατες εγγραφές. Η «Συμφωνία» δεν αποτελεί απόδειξη αγοράς ή πληρωμής.</p><div class="lead-stats"><?php $metrics=sales_pipeline_metrics($user);foreach(sales_pipeline_stages() as $key=>$label): ?><article><strong><?= (int)($metrics[$key]??0) ?></strong><span><?= e($label) ?></span></article><?php endforeach; ?></div><a class="button" href="<?= e(crm_url('sales-accounting.php')) ?>"><?= $manager?'Αναφορά λογιστηρίου (συνεργάτες + TL)':'Οι δικές μου αμοιβές — CSV' ?></a></section>
<section class="card form-section"><h2>Οι δικές μου προμήθειες</h2><div class="lead-stats"><article><strong>€<?= e(number_format((float)($totals['paid']??0),2,',','.')) ?></strong><span>Καταχωρισμένες εξοφλήσεις</span></article><article><strong>€<?= e(number_format((float)($totals['payable']??0)+(float)($totals['earned']??0),2,',','.')) ?></strong><span>Εκκρεμείς αμοιβές</span></article></div><a href="<?= e(crm_url('commissions.php')) ?>">Ανάλυση και CSV</a></section>
<section class="card form-section"><h2>Επόμενες ενέργειες και ειδοποιήσεις</h2><p>Οι υπενθυμίσεις εμφανίζονται εδώ και μπορούν να αποστέλλονται στο εταιρικό email μέσω της προγραμματισμένης εργασίας. Αναγνωσμένες / μη αναγνωσμένες και προτιμήσεις: <a href="operations.php">Εσωτερικές εργασίες</a>.</p>
<?php $notices=sales_notifications($user);foreach($notices as $notice): ?><p><a href="<?= e(crm_url($notice['url'])) ?>"><?= e($notice['label']) ?></a></p><?php endforeach;if(!$notices): ?><p class="muted">Δεν υπάρχουν τρέχουσες υπενθυμίσεις ή οικονομικές ενημερώσεις.</p><?php endif; ?>
<a class="button" href="/academy/">Συνέχεια εκπαίδευσης</a></section>
<section class="card form-section"><h2>Επανεξέταση κατοχύρωσης</h2><p>Ευκαιρίες χωρίς ενημέρωση για 30 ημέρες χρειάζονται έλεγχο, όχι αυτόματη αφαίρεση δικαιωμάτων. Προγραμματισμένο μελλοντικό follow-up εξαιρείται.</p>
<?php foreach($leads as $l):if(strtotime($l['updated_at'])>time()-30*86400||($l['follow_up_at']&&strtotime($l['follow_up_at'])>time())||in_array($l['status'],['won','lost','rejected'],true))continue; ?><p><?= e($l['lead_reference'].' · '.$l['submitter_name']) ?> <a href="<?= e(crm_url('sales-portal.php?tab=requests')) ?>">Αίτημα επανεξέτασης</a></p><?php endforeach; ?></section>
<?php elseif($tab==='pipeline'): ?>
<section class="card form-section"><h2>Εμπορική πορεία</h2><p>Τα στάδια πώλησης δεν εγκρίνουν αμοιβές και δεν αποκαλύπτουν προστατευμένες επαφές. Η λίστα έχει σελίδες των 50 εγγραφών.</p>
<?php sales_page_controls('leads');foreach($leads as $l):$own=$l['submitted_by']===$user['id']; ?>
<details class="card"><summary><?= e($l['lead_reference'].' · '.$l['submitter_name'].' · '.(sales_pipeline_stages()[$l['pipeline_stage']??'contacted']??'')) ?></summary>
<?php if($manager||$own): ?><form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="pipeline"><input type="hidden" name="lead_id" value="<?= e($l['id']) ?>">
<label>Στάδιο<select name="stage"><?php foreach(sales_pipeline_stages() as $key=>$label): ?><option value="<?= e($key) ?>" <?= ($l['pipeline_stage']??'contacted')===$key?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label>
<label>Θερμοκρασία<select name="temperature"><?php foreach(['hot','warm','cold'] as $key): ?><option <?= ($l['temperature']??'warm')===$key?'selected':'' ?>><?= e($key) ?></option><?php endforeach; ?></select></label>
<label>Προτεραιότητα<select name="priority"><?php foreach(['low','normal','high'] as $key): ?><option <?= ($l['priority']??'normal')===$key?'selected':'' ?>><?= e($key) ?></option><?php endforeach; ?></select></label>
<label>Επόμενο συγκεκριμένο βήμα<input name="next_step" required maxlength="500" value="<?= e($own||!empty($l['contacts_released_at'])?($l['next_step_other']?:$l['next_step']):'') ?>"></label>
<label>Ημερομηνία follow-up<input type="datetime-local" name="follow_up_at" required value="<?= e($l['follow_up_at']?date('Y-m-d\TH:i',strtotime($l['follow_up_at'])):'') ?>"></label>
<label class="check-label"><input type="checkbox" name="contact_completed" value="1"><span>Πραγματοποιήθηκε επικοινωνία σήμερα</span></label><button class="button primary">Αποθήκευση επόμενου βήματος</button></form>
<?php else: ?><p>Προβολή ομάδας: η κατοχύρωση παραμένει στον δημιουργό. Η ενημέρωση γίνεται από αυτόν ή τη διοίκηση.</p><?php endif; ?></details><?php endforeach; ?></section>
<?php elseif($tab==='requests'): ?>
<form class="card form-section stack" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="request"><h2>Νέο αίτημα</h2>
<label>Κατηγορία<select name="kind"><?php foreach(sales_request_kinds() as $key=>$label): ?><option value="<?= e($key) ?>"><?= e($label) ?></option><?php endforeach; ?></select></label>
<label>Lead (προαιρετικό)<select name="lead_id"><option value="">Χωρίς συσχέτιση</option><?php foreach($leads as $l):if(!$manager&&$l['submitted_by']!==$user['id'])continue; ?><option value="<?= e($l['id']) ?>"><?= e($l['lead_reference']) ?></option><?php endforeach; ?></select></label>
<label>Θέμα<input name="subject" required minlength="5" maxlength="200"></label><label>Περιγραφή, στοιχεία, ερώτημα και επιθυμητή απόφαση<textarea name="body" required minlength="20" maxlength="6000" rows="5"></textarea></label>
<label>Προτεραιότητα<select name="priority"><option value="normal">Κανονική</option><option value="high">Υψηλή</option><option value="low">Χαμηλή</option></select></label><button class="button primary">Υποβολή αιτήματος</button></form>
<?php $requestRows=sales_page_query('SELECT r.*,u.name requester_name FROM sales_requests r JOIN users u ON u.id=r.requester_id'.($manager?'':' WHERE r.requester_id=?').' ORDER BY r.updated_at DESC,r.id DESC',$manager?[]:[$user['id']],'requests');sales_page_controls('requests');foreach($requestRows as $r): ?>
<section class="card form-section"><h2><?= e($r['subject']) ?></h2><p><?= e($r['requester_name'].' · '.sales_request_kinds()[$r['kind']].' · '.$r['status']) ?></p><p><?= nl2br(e($r['body'])) ?></p><?php if($r['response']): ?><h3>Απάντηση</h3><p><?= nl2br(e($r['response'])) ?></p><?php endif; ?>
<?php if($manager): ?><form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="resolve"><input type="hidden" name="request_id" value="<?= e($r['id']) ?>"><label>Απόφαση<select name="status"><option value="in_progress">Υπό εξέταση</option><option value="approved">Εγκρίνεται</option><option value="declined">Δεν εγκρίνεται</option><option value="resolved">Ολοκληρώθηκε</option></select></label><label>Τεκμηρίωση<textarea name="response" required minlength="10" maxlength="6000"></textarea></label><button class="button">Καταγραφή απάντησης</button></form><?php endif; ?></section><?php endforeach; ?>
<?php elseif($tab==='teams'): ?>
<?php $q=db()->prepare('SELECT t.*,u.name leader_name FROM sales_teams t JOIN users u ON u.id=t.leader_id'.($manager?'':' WHERE t.leader_id=? OR EXISTS(SELECT 1 FROM sales_team_memberships m WHERE m.team_id=t.id AND m.user_id=? AND m.ends_at IS NULL)'));$q->execute($manager?[]:[$user['id'],$user['id']]);$teams=$q->fetchAll();foreach($teams as $t): ?><section class="card form-section"><h2><?= e($t['name']) ?></h2><p>Team Leader: <?= e($t['leader_name']) ?></p><?php $q=db()->prepare('SELECT u.name,m.starts_at FROM sales_team_memberships m JOIN users u ON u.id=m.user_id WHERE m.team_id=? AND m.ends_at IS NULL');$q->execute([$t['id']]);foreach($q->fetchAll() as $m): ?><p><?= e($m['name']) ?> · από <?= e(format_datetime($m['starts_at'])) ?></p><?php endforeach; ?>
<?php if($manager&&$t['active']): ?><form class="stack" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="close_team"><input type="hidden" name="team_id" value="<?= e($t['id']) ?>"><label>Αιτιολογία κλεισίματος ομάδας<textarea name="reason" minlength="20" maxlength="3000" required></textarea></label><button class="button">Κλείσιμο ομάδας — διατήρηση δεδουλευμένων</button></form><?php elseif(!$t['active']): ?><p>Η ομάδα έχει κλείσει.</p><?php endif; ?>
</section><?php endforeach; ?>
<?php if($manager): ?><form class="card form-section stack" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="create_team"><h2>Νέα ομάδα</h2><label>Όνομα<input name="name" required minlength="3" maxlength="150"></label><label>Team Leader<select name="leader_id"><?php foreach($users as $u): ?><option value="<?= e($u['id']) ?>"><?= e($u['name'].' · '.$u['email']) ?></option><?php endforeach; ?></select></label><button class="button">Δημιουργία ομάδας</button></form>
<form class="card form-section stack" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="assign_team"><h2>Τοποθέτηση / αλλαγή ομάδας</h2><p>Ισχύει από τώρα. Δεν αλλάζει παλιές προμήθειες.</p><label>Συνεργάτης<select name="user_id"><?php foreach($users as $u): ?><option value="<?= e($u['id']) ?>"><?= e($u['name']) ?></option><?php endforeach; ?></select></label><label>Ομάδα<select name="team_id"><option value="">Αποχώρηση από ομάδα</option><?php foreach($teams as $t): if(!$t['active'])continue; ?><option value="<?= e($t['id']) ?>"><?= e($t['name']) ?></option><?php endforeach; ?></select></label><label>Αιτιολογία<textarea name="reason" required minlength="10" maxlength="3000"></textarea></label><button class="button">Καταγραφή αλλαγής</button></form><?php endif; ?>
<?php elseif($tab==='overrides'): ?>
<section class="card form-section"><h2>Πρόσθετη αμοιβή Team Leader</h2><p>10% πάνω στην προμήθεια του μέλους. Δεν αφαιρείται από τον συνεργάτη, δεν υπολογίζεται στην αξία έργου και δεν δημιουργείται για προσωπική πώληση του ίδιου. Ισχύει για νέες προμήθειες μετά την τοποθέτηση στην ομάδα.</p>
<?php $overrideRows=sales_page_query('SELECT o.*,l.lead_reference,u.name beneficiary_name,c.status source_status FROM sales_team_overrides o JOIN lead_commissions c ON c.id=o.source_commission_id JOIN sales_leads l ON l.id=o.lead_id JOIN users u ON u.id=o.beneficiary_user_id'.($manager?'':' WHERE o.beneficiary_user_id=?').' ORDER BY o.earned_at DESC,o.id DESC',$manager?[]:[$user['id']],'overrides');sales_page_controls('overrides');foreach($overrideRows as $o): ?><article class="card"><h3><?= e($o['lead_reference'].' · '.$o['beneficiary_name']) ?></h3><p>€<?= e($o['amount']) ?> · <?= e($o['status']==='paid'?'Πληρωμένη':(in_array($o['source_status'],['payable','paid'],true)?'Πληρωτέα':'Δεδουλευμένη')) ?></p>
<?php if($manager&&$o['status']!=='paid'): ?><form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="pay_override"><input type="hidden" name="override_id" value="<?= e($o['id']) ?>"><label>Ημερομηνία πραγματικής πληρωμής<input type="date" name="payout_date" required max="<?= e(date('Y-m-d')) ?>"></label><label>Αναφορά πληρωμής<input name="payout_reference" required maxlength="255"></label><button class="button">Καταγραφή εξόφλησης</button></form><?php endif; ?></article><?php endforeach; ?></section>
<?php elseif($tab==='applicants'&&$manager): ?>
<section class="card form-section"><h2>Υποψηφιότητες και συνεντεύξεις</h2><p>Έρευνα 10–15 λεπτών, σύντομο role-play, αξιολόγηση επαγγελματισμού και πλάνο πρώτης εβδομάδας. Η έγκριση αίτησης δεν δημιουργεί λογαριασμό χωρίς ενέργεια του διαχειριστή.</p><a class="button" href="<?= e(crm_url('partner-apply.php')) ?>">Δημόσια φόρμα αίτησης</a><a class="button" href="<?= e(crm_url('accounts.php')) ?>">Δημιουργία λογαριασμού με 3 πεδία</a></section>
<?php $applicantRows=sales_page_query('SELECT id,name,email,region,experience,status,interview_notes,review_at,created_at,(cv_pdf IS NOT NULL) has_cv FROM sales_applicants ORDER BY created_at DESC,id DESC',[],'applicants');sales_page_controls('applicants');foreach($applicantRows as $candidate): ?><section class="card form-section"><h2><?= e($candidate['name']) ?></h2><p><?= e($candidate['email'].' · '.$candidate['region'].' · '.$candidate['status']) ?></p><p><?= nl2br(e($candidate['experience'])) ?></p><?php if($candidate['status']==='training_approved'): ?><p><a class="button primary" href="<?= e(crm_url('accounts.php?new=1&applicant='.$candidate['id'])) ?>">Δημιουργία χρήστη από την αίτηση</a></p><?php endif; ?><?php if($candidate['has_cv']): ?><a class="button" href="<?= e(crm_url('applicant-cv.php?id='.$candidate['id'])) ?>">Λήψη PDF βιογραφικού</a><?php endif; ?><form class="stack" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="review_applicant"><input type="hidden" name="applicant_id" value="<?= e($candidate['id']) ?>"><label>Στάδιο<select name="stage"><?php foreach(['candidate'=>'Υποψήφιος','screening'=>'Αρχικός έλεγχος','interview'=>'Συνέντευξη','training_approved'=>'Έγκριση εκπαίδευσης','declined'=>'Δεν προχωρά','closed'=>'Κλειστή αίτηση'] as $key=>$label): ?><option value="<?= e($key) ?>" <?= $candidate['status']===$key?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label>Αξιολόγηση / role-play / επόμενο βήμα<textarea name="notes" minlength="20" maxlength="5000" required><?= e($candidate['interview_notes']??'') ?></textarea></label><label>Ημερομηνία επόμενου βήματος<input name="review_at" type="date" value="<?= e($candidate['review_at']??'') ?>"></label><button class="button">Αποθήκευση αξιολόγησης</button></form></section><?php endforeach; ?>
<?php elseif($tab==='recurring'): ?>
<section class="card form-section"><h2>Επαναλαμβανόμενες υπηρεσίες</h2><p>Εγκεκριμένη βάση ανά συμφωνημένη περίοδο χωρίς ΦΠΑ/εξαιρούμενα κόστη, σταθερός δικαιούχος και ποσοστό συμφωνίας. Προμήθεια μόνο με πραγματική επιλέξιμη είσπραξη. Δεν δημιουργείται νέο qualified fee ανά περίοδο. Για άλλο αντικείμενο απαιτείται νέα έγκριση με το αντίστοιχο ποσοστό.</p></section>
<?php $q=db()->prepare('SELECT c.*,l.lead_reference,u.name beneficiary_name FROM sales_recurring_contracts c JOIN sales_leads l ON l.id=c.lead_id JOIN users u ON u.id=c.beneficiary_user_id'.($manager?'':' WHERE c.beneficiary_user_id=?').' ORDER BY c.created_at DESC');$q->execute($manager?[]:[$user['id']]);foreach($q->fetchAll() as $contract): ?><section class="card form-section"><h2><?= e($contract['lead_reference'].' · '.$contract['beneficiary_name']) ?></h2><p>Υπηρεσία <?= e($contract['service_code']) ?> · <?= (int)$contract['rate'] ?>% · βάση / περίοδο <?= (int)$contract['interval_months'] ?> μηνών €<?= e($contract['period_base']) ?> · <?= $contract['active']?'Ενεργή':'Κλειστή — επιτρέπονται εισπράξεις ήδη καλυμμένων περιόδων' ?></p><p><?= e($contract['starts_on'].' — '.($contract['ends_on']??'ανοικτή διάρκεια')) ?></p>
<?php $aq=db()->prepare('SELECT reference FROM sales_recurring_agreements WHERE contract_id=?');$aq->execute([$contract['id']]);$agreement=$aq->fetchColumn();if($agreement): ?><p><a href="<?= e(crm_url('recurring-agreement.php?id='.$contract['id'])) ?>">Υπογεγραμμένη συμφωνία: <?= e($agreement) ?></a></p><?php else: ?><p>Προϋπάρχουσα συμφωνία — δεν δημιουργήθηκε αναδρομικά δήλωση υπογραφής.</p><?php endif; ?><?php if($manager): ?><form class="stack" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="recurring_receipt"><input type="hidden" name="contract_id" value="<?= e($contract['id']) ?>"><label>Μήνας έναρξης της περιόδου<input name="period_month" type="month" required></label><label>Πραγματική είσπραξη (€)<input name="received_amount" type="number" min="0.01" step="0.01" required></label><label>Επιλέξιμο μέρος χωρίς ΦΠΑ/εξαιρούμενα (€)<input name="eligible_base_amount" type="number" min="0.01" step="0.01" required></label><label>Ημερομηνία είσπραξης<input name="received_at" type="date" max="<?= e(date('Y-m-d')) ?>" required></label><label>Μοναδική αναφορά / παραστατικό<input name="receipt_reference" required maxlength="255"></label><button class="button">Καταγραφή είσπραξης</button></form><?php if($contract['active']): ?><details><summary>Λήξη συμφωνίας</summary><form class="stack" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="close_recurring"><input type="hidden" name="contract_id" value="<?= e($contract['id']) ?>"><label>Αιτιολογία<textarea name="reason" required minlength="20" maxlength="3000"></textarea></label><button class="button">Διακοπή νέων προμηθειών — διατήρηση παλαιών</button></form></details><?php endif; ?><?php endif; ?></section><?php endforeach; ?>
<?php if($manager): ?><form method="post" enctype="multipart/form-data" class="card form-section stack"><?= csrf_field() ?><input type="hidden" name="action" value="create_recurring"><h2>Νέα επαναλαμβανόμενη συμφωνία</h2><p>Προηγείται έγγραφη συμφωνία ανά πελάτη, με συγκεκριμένο δικαιούχο, αντικείμενο, βάση/ποσοστό και διάρκεια. Οι παλιές συμφωνίες και οι αρχικές δόσεις δεν αλλάζουν αναδρομικά.</p><label>Πλήρες υπογεγραμμένο PDF<input type="file" name="agreement_pdf" accept="application/pdf" required></label><label>Αναφορά συμφωνίας<input name="agreement_reference" minlength="5" maxlength="200" required></label><label>Ημερομηνία υπογραφής<input name="signed_on" type="date" max="<?= e(date('Y-m-d')) ?>" required></label><label class="checkbox-row"><input type="checkbox" name="signed_confirmed" value="1" required> Έλεγξα την υπογραφή του Μελά, την αποδοχή του δικαιούχου και ότι οι όροι του αρχείου συμφωνούν με τα παρακάτω πεδία.</label><label>Ο κωδικός μου<input type="password" name="actor_password" required autocomplete="current-password"></label><label>Ήδη εγκεκριμένο αντικείμενο<select name="component_id"><?php foreach(db()->query("SELECT c.id,c.description,l.lead_reference FROM lead_service_components c JOIN sales_leads l ON l.id=c.lead_id WHERE c.policy_version<>'recurring-v26' ORDER BY c.approved_at DESC")->fetchAll() as $component): ?><option value="<?= e($component['id']) ?>"><?= e($component['lead_reference'].' · '.$component['description']) ?></option><?php endforeach; ?></select></label><label>Καθαρή επιλέξιμη βάση ολόκληρης περιόδου (€)<input name="period_base" type="number" min="0.01" step="0.01" required></label><label>Συχνότητα που ορίζει η υπογεγραμμένη συμφωνία<select name="interval_months"><option value="1">Κάθε μήνα</option><option value="2">Κάθε 2 μήνες</option><option value="3">Κάθε 3 μήνες</option><option value="6">Κάθε 6 μήνες</option><option value="12">Κάθε έτος</option></select></label><p>Η πρώτη περίοδος αρχίζει στον μήνα έναρξης της σύμβασης. Μερική είσπραξη καταχωρίζεται στην ίδια περίοδο, όχι σε νέο μήνα. Δεν γίνεται αυτόματη ανανέωση ή δημιουργία αμοιβής.</p><label>Έναρξη<input name="starts_on" type="date" required></label><label>Λήξη (προαιρετικά)<input name="ends_on" type="date"></label><label>Όροι, εξαιρούμενα ποσά και τεκμηρίωση<textarea name="note" required minlength="20" maxlength="3000"></textarea></label><button class="button">Έγκριση επαναλαμβανόμενης συμφωνίας</button></form><?php endif; ?>
<?php elseif($tab==='development'): ?>
<?php $q=db()->prepare('SELECT u.id,u.name,p.stage,p.notes,p.review_at FROM users u JOIN sales_partner_profiles p ON p.user_id=u.id'.($manager?'':' WHERE u.id=?').' ORDER BY u.name');$q->execute($manager?[]:[$user['id']]);foreach($q->fetchAll() as $person): ?>
<section class="card form-section"><h2><?= e($person['name']) ?></h2><p><?= e(sales_partner_stages()[$person['stage']]??$person['stage']) ?> · Ανασκόπηση: <?= e($person['review_at']??'—') ?></p><p><?= nl2br(e($person['notes']??'')) ?></p>
<?php if($manager): ?><form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="partner_stage"><input type="hidden" name="user_id" value="<?= e($person['id']) ?>"><label>Επόμενο στάδιο<select name="stage"><?php foreach(sales_partner_stages() as $key=>$label): ?><option value="<?= e($key) ?>" <?= $person['stage']===$key?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label>Συνέντευξη / πρώτη εβδομάδα / coaching / αιτιολογία<textarea name="notes" minlength="20" maxlength="5000" required><?= e($person['notes']??'') ?></textarea></label><label>Επόμενη ανασκόπηση<input type="date" name="review_at" value="<?= e($person['review_at']??'') ?>"></label><button class="button">Καταγραφή εξέλιξης</button></form><?php endif; ?></section><?php endforeach; ?>
<section class="card form-section"><h2>Πρόσβαση και ετοιμότητα</h2><p>Οι υπάρχοντες χρήστες διατηρούν τα δικαιώματά τους. Οι νέοι ξεκινούν αμέσως στην Academy με τα στοιχεία Melas CRM. Μετά τα μαθήματα, την τελική εξέταση, τουλάχιστον τρία διαφορετικά επιτυχή σενάρια αυτόματων εικονικών κλήσεων από τις δύο εταιρείες και την εκπαιδευτική αξιολόγηση, περνούν στο στάδιο «Έγγραφα &amp; υπογραφές». Αυτό δεν ενεργοποιεί το CRM. Μόνο η αλλαγή σε εγκεκριμένο ή ενεργό συνεργάτη ελέγχει ξανά εκπαίδευση, προέγκριση, τελικά υπογεγραμμένα έγγραφα και αποδοχές των δύο πολιτικών και ενεργοποιεί το CRM με τον ήδη καθορισμένο ρόλο. Για διακοπή σύνδεσης χρησιμοποιούνται οι Λογαριασμοί.</p></section>
<?php elseif($tab==='ownership'): ?>
<section class="card form-section"><h2>Υπεύθυνος πελάτη ≠ δικαιούχος κάθε lead</h2><p>Η ανάθεση λογαριασμού οργανώνει την εξυπηρέτηση. Δεν αλλάζει τον αρχικό δημιουργό ευκαιρίας και δεν μεταφέρει προηγούμενες προμήθειες.</p>
<?php $q=db()->prepare('SELECT o.*,c.name company_name,u.name owner_name FROM sales_account_owners o JOIN companies c ON c.id=o.company_id JOIN users u ON u.id=o.owner_id'.($manager?'':' WHERE o.owner_id=?').' ORDER BY c.name');$q->execute($manager?[]:[$user['id']]);foreach($q->fetchAll() as $owner): ?><p><?= e($owner['company_name'].' · '.$owner['owner_name']) ?> · <?= e(format_datetime($owner['assigned_at'])) ?></p><?php endforeach; ?></section>
<?php if($manager): ?><form method="post" class="card form-section stack"><?= csrf_field() ?><input type="hidden" name="action" value="account_owner"><h2>Ανάθεση λογαριασμού με ιστορικό</h2><label>Εταιρεία<select name="company_id"><?php foreach(db()->query('SELECT id,name FROM companies WHERE deleted_at IS NULL ORDER BY name')->fetchAll() as $company): ?><option value="<?= (int)$company['id'] ?>"><?= e($company['name']) ?></option><?php endforeach; ?></select></label><label>Υπεύθυνος<select name="owner_id"><?php foreach($users as $person): ?><option value="<?= e($person['id']) ?>"><?= e($person['name']) ?></option><?php endforeach; ?></select></label><label>Αιτιολογία<textarea name="reason" minlength="20" maxlength="3000" required></textarea></label><button class="button">Καταγραφή ανάθεσης</button></form><?php endif; ?>
<?php else: ?>
<section class="card form-section"><h2>Βιβλιοθήκη πωλήσεων</h2><p>Χρησιμοποίησε την τρέχουσα εγκεκριμένη ύλη και όχι αποθηκευμένα παλιά ποσά.</p><div class="actions"><a class="button" href="<?= e(crm_url('sales-guide.php')) ?>">Οδηγός συνεργατών</a><a class="button" href="/academy/">Μαθήματα & ασκήσεις</a><a class="button" href="<?= e(crm_url('sales-portal.php?tab=requests')) ?>">Ζήτησε τεχνική / εμπορική έγκριση</a></div></section>
<?php if(sales_partner_ready($user)||$manager): ?>
<?php foreach(db()->query('SELECT * FROM sales_toolkit_versions ORDER BY created_at DESC')->fetchAll() as $item): ?><section class="card form-section"><h2><?= e($item['title']) ?></h2><p>Έκδοση <?= e($item['version_label']) ?> · <?= e(format_datetime($item['created_at'])) ?></p><p><?= nl2br(e($item['body'])) ?></p><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="acknowledge"><input type="hidden" name="version_id" value="<?= e($item['id']) ?>"><button class="button">Το διάβασα</button></form><small>Απλή καταγραφή παραλαβής ενημέρωσης. Δεν αποτελεί ψηφιακή υπογραφή ή προϋπόθεση πρόσβασης.</small></section><?php endforeach; ?>
<?php else: ?><p class="alert">Τα έτοιμα εμπορικά πρότυπα ξεκλειδώνουν στο εποπτευόμενο / εγκεκριμένο στάδιο. Η εκπαιδευτική ύλη παραμένει διαθέσιμη στην Academy.</p><?php endif; ?>
<?php if($manager): ?><form class="card form-section stack" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="publish_toolkit"><h2>Δημοσίευση νέας έκδοσης</h2><label>Κατηγορία<select name="category"><?php foreach(['script','email','linkedin','policy','presentation','checklist'] as $key): ?><option><?= e($key) ?></option><?php endforeach; ?></select></label><label>Τίτλος<input name="title" required minlength="5" maxlength="180"></label><label>Έκδοση<input name="version_label" required maxlength="50"></label><label>Εγκεκριμένο περιεχόμενο<textarea name="body" rows="10" required minlength="40" maxlength="30000"></textarea></label><button class="button">Δημοσίευση χωρίς αντικατάσταση ιστορικού</button></form><?php endif; ?>
<?php endif;render_footer(); ?>
