<?php
declare(strict_types=1);

return [
    "CREATE TABLE IF NOT EXISTS users (
      id CHAR(36) PRIMARY KEY,
      name VARCHAR(150) NOT NULL,
      email VARCHAR(320) NOT NULL,
      role ENUM('employee','manager','technical','admin') NOT NULL DEFAULT 'employee',
      active TINYINT(1) NOT NULL DEFAULT 1,
      password_hash VARCHAR(255) NOT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      UNIQUE KEY users_email_unique (email)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

    "CREATE TABLE IF NOT EXISTS corporate_documents (
      id CHAR(36) PRIMARY KEY,
      uploaded_by CHAR(36) NULL,
      title VARCHAR(255) NOT NULL,
      document_reference VARCHAR(100) NULL,
      category VARCHAR(100) NOT NULL DEFAULT 'other',
      access_level VARCHAR(30) NOT NULL DEFAULT 'all',
      description TEXT NULL,
      version_label VARCHAR(50) NULL,
      document_date DATE NULL,
      file_name VARCHAR(255) NOT NULL,
      mime_type VARCHAR(150) NOT NULL,
      size_bytes BIGINT UNSIGNED NOT NULL,
      content LONGBLOB NOT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      CONSTRAINT corporate_documents_user_fk FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL,
      UNIQUE KEY corporate_documents_reference_unique (document_reference),
      KEY corporate_documents_category_idx (category, created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

    "CREATE TABLE IF NOT EXISTS engineering_profiles (
      id CHAR(36) PRIMARY KEY,
      created_by CHAR(36) NULL,
      profile_id VARCHAR(100) NOT NULL,
      internal_name VARCHAR(180) NOT NULL,
      primary_role VARCHAR(180) NOT NULL,
      seniority VARCHAR(60) NOT NULL,
      profile_status ENUM('draft','verified','shareable') NOT NULL DEFAULT 'draft',
      data_json LONGTEXT NOT NULL,
      content LONGBLOB NOT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      CONSTRAINT engineering_profiles_user_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
      UNIQUE KEY engineering_profiles_profile_id_unique (profile_id),
      KEY engineering_profiles_status_idx (profile_status, updated_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

    "CREATE TABLE IF NOT EXISTS companies (
      id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      legal_name VARCHAR(255) NULL,
      trading_name VARCHAR(255) NULL,
      legal_form VARCHAR(120) NULL,
      name_key VARCHAR(255) NOT NULL,
      email VARCHAR(255) NULL,
      phone VARCHAR(40) NULL,
      industry VARCHAR(120) NULL,
      website VARCHAR(255) NULL,
      address VARCHAR(255) NULL,
      city VARCHAR(120) NULL,
      country VARCHAR(120) NULL,
      postal_code VARCHAR(30) NULL,
      registration_number VARCHAR(120) NULL,
      vat_number VARCHAR(120) NULL,
      contact_name VARCHAR(150) NULL,
      contact_title VARCHAR(150) NULL,
      notes TEXT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at DATETIME NULL,
      UNIQUE KEY companies_name_key_unique (name_key),
      KEY companies_deleted_at_idx (deleted_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

    "CREATE TABLE IF NOT EXISTS company_documents (
      id CHAR(36) PRIMARY KEY,
      company_id BIGINT UNSIGNED NOT NULL,
      created_by CHAR(36) NULL,
      document_type VARCHAR(40) NOT NULL,
      document_status VARCHAR(40) NOT NULL DEFAULT 'draft',
      document_reference VARCHAR(80) NOT NULL,
      title VARCHAR(255) NOT NULL,
      file_name VARCHAR(255) NOT NULL,
      mime_type VARCHAR(150) NOT NULL DEFAULT 'text/html; charset=UTF-8',
      content LONGBLOB NOT NULL,
      client_signed_file_name VARCHAR(255) NULL,
      client_signed_pdf LONGBLOB NULL,
      client_signed_at DATETIME NULL,
      approval_code_hash VARCHAR(255) NULL,
      approval_code_expires_at DATETIME NULL,
      approval_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
      approval_requested_at DATETIME NULL,
      approval_requested_by CHAR(36) NULL,
      approved_at DATETIME NULL,
      approval_confirmed_by CHAR(36) NULL,
      final_signed_file_name VARCHAR(255) NULL,
      final_signed_pdf LONGBLOB NULL,
      final_signed_at DATETIME NULL,
      data_json LONGTEXT NULL,
      effective_date DATE NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      CONSTRAINT company_documents_company_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
      CONSTRAINT company_documents_user_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
      UNIQUE KEY company_documents_reference_unique (document_reference),
      KEY company_documents_company_idx (company_id, created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

    "CREATE TABLE IF NOT EXISTS company_document_deliveries (
      id CHAR(36) PRIMARY KEY,
      document_id CHAR(36) NOT NULL,
      requested_by CHAR(36) NULL,
      recipient_email VARCHAR(320) NOT NULL,
      recipient_role VARCHAR(40) NOT NULL,
      delivery_status VARCHAR(30) NOT NULL DEFAULT 'pending',
      sent_at DATETIME NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      CONSTRAINT document_deliveries_document_fk FOREIGN KEY (document_id) REFERENCES company_documents(id) ON DELETE CASCADE,
      CONSTRAINT document_deliveries_user_fk FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET NULL,
      UNIQUE KEY document_deliveries_recipient_unique (document_id, recipient_email),
      KEY document_deliveries_status_idx (document_id, delivery_status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

    "CREATE TABLE IF NOT EXISTS communications (
      id CHAR(36) PRIMARY KEY,
      company_id BIGINT UNSIGNED NOT NULL,
      user_id CHAR(36) NULL,
      assigned_user_id CHAR(36) NULL,
      source ENUM('website','telephone') NOT NULL DEFAULT 'telephone',
      status ENUM('new','contacted','qualified','proposal','won','lost','archived') NOT NULL DEFAULT 'new',
      contact_name VARCHAR(150) NULL,
      contact_role VARCHAR(120) NULL,
      outcome ENUM('no_answer','callback','interested','not_interested') NULL,
      interest_level TINYINT UNSIGNED NULL,
      notes TEXT NULL,
      next_action VARCHAR(255) NULL,
      next_action_at DATETIME NULL,
      archived_at DATETIME NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at DATETIME NULL,
      CONSTRAINT communications_company_fk FOREIGN KEY (company_id) REFERENCES companies(id),
      CONSTRAINT communications_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
      CONSTRAINT communications_assigned_fk FOREIGN KEY (assigned_user_id) REFERENCES users(id) ON DELETE SET NULL,
      KEY communications_source_status_idx (source, status),
      KEY communications_next_action_idx (next_action_at),
      KEY communications_company_idx (company_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

    "CREATE TABLE IF NOT EXISTS communication_project_briefs (
      communication_id CHAR(36) PRIMARY KEY,
      country VARCHAR(100) NULL,
      service VARCHAR(80) NULL,
      project_title VARCHAR(180) NULL,
      requirement TEXT NULL,
      technologies TEXT NULL,
      project_stage VARCHAR(80) NULL,
      engagement VARCHAR(80) NULL,
      timeline VARCHAR(80) NULL,
      request_nda TINYINT(1) NOT NULL DEFAULT 0,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      CONSTRAINT project_brief_communication_fk FOREIGN KEY (communication_id) REFERENCES communications(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

    "CREATE TABLE IF NOT EXISTS website_enquiries (
      id CHAR(36) PRIMARY KEY,
      reference VARCHAR(20) NOT NULL,
      communication_id CHAR(36) NOT NULL,
      business_email VARCHAR(255) NOT NULL,
      language ENUM('en','el') NOT NULL DEFAULT 'en',
      source_page VARCHAR(300) NULL,
      submitted_at DATETIME NOT NULL,
      request_ip_hash CHAR(64) NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE KEY website_reference_unique (reference),
      UNIQUE KEY website_communication_unique (communication_id),
      CONSTRAINT website_enquiry_communication_fk FOREIGN KEY (communication_id) REFERENCES communications(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

    "CREATE TABLE IF NOT EXISTS website_enquiry_documents (
      id CHAR(36) PRIMARY KEY,
      website_enquiry_id CHAR(36) NOT NULL,
      file_name VARCHAR(255) NOT NULL,
      mime_type VARCHAR(150) NOT NULL,
      size_bytes BIGINT UNSIGNED NOT NULL,
      content LONGBLOB NOT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT website_document_enquiry_fk FOREIGN KEY (website_enquiry_id) REFERENCES website_enquiries(id) ON DELETE CASCADE,
      KEY website_document_enquiry_idx (website_enquiry_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

    "CREATE TABLE IF NOT EXISTS notifications (
      id CHAR(36) PRIMARY KEY,
      user_id CHAR(36) NOT NULL,
      title VARCHAR(160) NOT NULL,
      body TEXT NOT NULL,
      action_url VARCHAR(255) NULL,
      read_at DATETIME NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT notifications_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      KEY notifications_user_created_idx (user_id, created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

    "CREATE TABLE IF NOT EXISTS crm_settings (
      setting_key VARCHAR(100) PRIMARY KEY,
      setting_value TEXT NOT NULL,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

    "CREATE TABLE IF NOT EXISTS request_limits (
      limit_key CHAR(64) PRIMARY KEY,
      attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
      window_started DATETIME NOT NULL,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      KEY request_limits_window_idx (window_started)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
];
