<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';$user=require_login();ensure_lead_schema();require_once __DIR__.'/settlement-workflow.php';sales_settlement_schema();$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();try{$id=sales_settlement_close($user,$_POST);flash('success','Η εκκαθάριση κλειδώθηκε. Δεν έγινε τραπεζική πληρωμή.');redirect_to('settlements.php?id='.$id);}catch(Throwable $e){$error=$e instanceof InvalidArgumentException?$e->getMessage():'Η εκκαθάριση δεν αποθηκεύτηκε.';}
}
$id=is_string($_GET['id']??null)?$_GET['id']:'';$rows=[];$batch=null;
if($id!==''){try{[$batch,$rows]=sales_settlement_read($user,$id);}catch(InvalidArgumentException){http_response_code(404);exit('Δεν βρέθηκε διαθέσιμη εκκαθάριση.');}}
if(isset($_GET['csv'])&&$batch){header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="melas-settlement-'.$batch['period_month'].'.csv"');$out=fopen('php://output','wb');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,['Περίοδος','Δικαιούχος','Email','Χειρισμός','Τύπος προμήθειας','Κωδικός εγγραφής','Ημερομηνία δικαιώματος','Κλειδωμένο ποσό','Προθεσμία','Τρέχουσα κατάσταση','Ημερομηνία καταβολής','Αναφορά καταβολής'],',','"','');foreach($rows as $r)fputcsv($out,array_map('sales_csv_cell',[$batch['period_month'],$r['name'],$r['email'],sales_settlement_relationship($r['relationship']),$r['source_type'],$r['source_id'],$r['earned_at'],$r['amount'],$r['due_on'],$r['current_status'],$r['payout_date'],$r['payout_reference']]),',','"','');fclose($out);exit;}
render_header('Μηνιαίες εκκαθαρίσεις',$user);
?>
<div class="page-heading"><div><h1>Μηνιαίες εκκαθαρίσεις</h1><p>Κλειδωμένη κατάσταση δικαιωμάτων, προθεσμία και πραγματικές εξοφλήσεις. Η δημιουργία κατάστασης δεν πληρώνει τον συνεργάτη.</p></div><a class="button" href="<?= e(crm_url('commissions.php')) ?>">Προμήθειες</a></div>
<?php if($error): ?><p class="alert error"><?= e($error) ?></p><?php endif; ?>
<section class="card form-section"><p>Πληρωμή έως το τέλος του επόμενου μήνα ή νωρίτερα αν υπάρχει υποχρεωτική προθεσμία. Για μισθωτούς: πρόσθετες μικτές αποδοχές μέσω μισθοδοσίας, χωρίς καθυστέρηση βασικού μισθού. Για εξωτερικούς: επαγγελματική αμοιβή με το απαιτούμενο παραστατικό. Οι κρατήσεις και ο ΦΠΑ ελέγχονται από το λογιστήριο· δεν υπολογίζονται εδώ.</p>
<?php if(can_view_all_sales_financials($user)): ?><form method="post" class="stack"><?= csrf_field() ?><label>Κλεισμένος ημερολογιακός μήνας<input type="month" name="period_month" required max="<?= e((new DateTimeImmutable('first day of last month'))->format('Y-m')) ?>"></label><label>Νωρίτερη υποχρεωτική προθεσμία (αν υπάρχει)<input type="date" name="earlier_due_on"></label><label>Σημείωση λογιστηρίου<textarea name="note" required minlength="10" maxlength="2000"></textarea></label><label class="checkbox-row"><input type="checkbox" name="reviewed" value="1" required> Ελέγχθηκαν οι πληρωτέες αμοιβές, οι σχέσεις και οι προθεσμίες. Δεν δηλώνω ότι πληρώθηκαν.</label><label>Ο κωδικός μου<input type="password" name="actor_password" required autocomplete="current-password"></label><button class="button primary">Κλείδωμα νέας εκκαθάρισης</button></form><p>Συμπληρωματική εκκαθάριση του ίδιου μήνα επιτρέπεται για αμοιβές που δεν είχαν συμπεριληφθεί. Κάθε δικαίωμα μπαίνει μόνο μία φορά. Παλαιότερα ασυμπερίληπτα ποσά μεταφέρονται χωρίς αλλαγή της αρχικής γένεσης.</p><?php endif; ?></section>
<?php if($batch): ?><section class="card form-section"><h2><?= e($batch['period_month']) ?> · έως <?= e($batch['due_on']) ?></h2><p><?= e($batch['note']) ?></p><a class="button" href="<?= e(crm_url('settlements.php?id='.$batch['id'].'&csv=1')) ?>">CSV λογιστηρίου — επιτρεπόμενα στοιχεία</a><div class="table-wrap"><table><thead><tr><th>Δικαιούχος</th><th>Χειρισμός</th><th>Ποσό κλειδώματος</th><th>Προθεσμία εγγραφής</th><th>Εξόφληση</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= e($r['name']) ?></td><td><?= e(sales_settlement_relationship($r['relationship'])) ?></td><td>€<?= e($r['amount']) ?></td><td><?= e($r['due_on']) ?></td><td><?= e($r['current_status']==='paid'?'Πληρωμένο '.$r['payout_date']:($r['due_on']<date('Y-m-d')?'Εκπρόθεσμο / προς έλεγχο':'Εκκρεμεί')) ?><?php if($r['current_status']==='cancelled'): ?> · Ακύρωση στην αρχική εγγραφή — απαιτείται λογιστική συμφωνία<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><p>Τα κλειδωμένα ποσά είναι ιστορικό στιγμιότυπο. Η τρέχουσα εξόφληση διαβάζεται από τις αρχικές προμήθειες και δεν ξανακαταχωρίζεται εδώ.</p></section><?php endif; ?>
<section class="card form-section"><h2>Διαθέσιμες καταστάσεις</h2><?php foreach(sales_settlement_list($user) as $b): ?><p><a href="<?= e(crm_url('settlements.php?id='.$b['id'])) ?>"><?= e($b['period_month'].' · κλείδωμα '.$b['closed_at'].' · έως '.$b['due_on']) ?></a></p><?php endforeach; ?></section><?php render_footer(); ?>
