<?php
declare(strict_types=1);

function sow_document_html(array $data): string
{
    $v = static fn(string $key, string $fallback = ''): string => e(trim((string)($data[$key] ?? $fallback)));
    $raw = static fn(string $key, string $fallback = ''): string => trim((string)($data[$key] ?? $fallback));
    $selected = array_map('intval', is_array($data['selected_sections'] ?? null) ? $data['selected_sections'] : range(1, 48));
    $show = static fn(int $number): bool => in_array($number, $selected, true);
    $items = static fn(string $value): array => array_values(array_filter(array_map('trim', preg_split('/\R/u', $value) ?: [])));
    $rows = static function (string $value, int $columns): array {
        $result = [];
        foreach (preg_split('/\R/u', $value) ?: [] as $line) {
            if (trim($line) === '') continue;
            $result[] = array_pad(array_slice(array_map('trim', explode('|', $line)), 0, $columns), $columns, '—');
        }
        return $result;
    };
    $list = static function (array $values): void { if (!$values) return; echo '<ul>'; foreach ($values as $value) echo '<li>'.e($value).'</li>'; echo '</ul>'; };
    $table = static function (array $headers, array $values): void { if (!$values) return; echo '<table><thead><tr>'; foreach ($headers as $header) echo '<th>'.e($header).'</th>'; echo '</tr></thead><tbody>'; foreach ($values as $row) { echo '<tr>'; foreach ($row as $cell) echo '<td>'.e($cell).'</td>'; echo '</tr>'; } echo '</tbody></table>'; };
    $section = static function (int $number, string $title, callable $content) use ($show): void { if (!$show($number)) return; echo '<section class="sow-section"><h2>'.$number.'. '.e($title).'</h2>'; $content(); echo '</section>'; };
    ob_start();
    ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><title><?= $v('sow_reference') ?> — Statement of Work</title><style>
@page{size:A4;margin:17mm 16mm 18mm}*{box-sizing:border-box}body{margin:0;color:#132238;background:#fff;font:9.7pt/1.46 Arial,Helvetica,sans-serif}.document{max-width:178mm;margin:auto}.brand{display:flex;align-items:center;justify-content:space-between;gap:18px;border-bottom:3px solid #176afc;padding:0 0 12px;margin-bottom:20px}.brand img{width:245px;max-width:58%;height:auto}.brand-meta{text-align:right;color:#5b6b80;font-size:8.5pt}.classification{color:#176afc;font-weight:800;letter-spacing:.12em}.cover{min-height:255mm;display:flex;flex-direction:column}.cover h1{font-size:31pt;line-height:1.04;margin:39mm 0 8px;color:#071426}.cover h3{font-size:15pt;color:#176afc;margin:0}.cover-card{margin-top:24mm;padding:20px;border:1px solid #cbd8e8;border-radius:12px;background:#f5f8fd}.cover-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px 24px}.cover-grid strong{display:block;font-size:8pt;text-transform:uppercase;letter-spacing:.08em;color:#607086}.cover-note{margin-top:auto;border-top:1px solid #cbd8e8;padding-top:12px;color:#64748b;font-size:8.5pt}.page-break{break-before:page}.sow-section{margin:0 0 13px;break-inside:auto;page-break-inside:auto}.sow-section h2{margin:0 0 7px;padding:8px 10px;background:#071426;color:#fff;font-size:10.8pt;break-after:avoid;page-break-after:avoid}.sow-section h3{margin:9px 0 4px;color:#176afc;font-size:9.8pt;break-after:avoid;page-break-after:avoid}.sow-section p{margin:0 0 7px;text-align:justify;orphans:3;widows:3}.sow-section ul{margin:4px 0 8px;padding-left:20px}.sow-section li{margin:2px 0}table{width:100%;border-collapse:collapse;margin:7px 0 11px;font-size:8.5pt;break-inside:auto;page-break-inside:auto}thead{display:table-header-group}tr{break-inside:avoid;page-break-inside:avoid}th{background:#071426;color:#fff;text-align:left;padding:7px}td{border:1px solid #cbd8e8;padding:7px;vertical-align:top}tr:nth-child(even) td{background:#f3f7fd}.highlight,.flow,.signatures,.signature-card{break-inside:avoid;page-break-inside:avoid}.highlight{padding:12px 14px;border-left:4px solid #176afc;background:#f3f7fd;margin:8px 0}.flow{text-align:center;font-weight:700;color:#176afc;padding:12px;border:1px solid #bfd1eb;border-radius:8px}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:18px}.signature-card{border:1px solid #afbed0;border-radius:10px;padding:16px;min-height:108mm}.signature-card h3{background:#071426;color:#fff;margin:-16px -16px 18px;padding:11px 16px;border-radius:9px 9px 0 0}.line{height:38px;border-bottom:1px solid #596b80;margin:5px 0 12px}.appendix{min-height:0;padding:12px;border:1px dashed #9db3d1;border-radius:8px;margin:7px 0 13px;break-inside:auto}.doc-footer{margin-top:16px;text-align:center;color:#64748b;font-size:8.3pt}@media print{.document{max-width:none}.sow-section h2,th,.signature-card h3{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style></head><body><main class="document">
<section class="cover"><div class="brand"><img src="<?= $v('logo_url') ?>" alt="DISTILLOGIC TECHNOLOGIES"><div class="brand-meta"><span class="classification">COMMERCIAL CONFIDENTIAL</span><br><?= $v('sow_reference') ?><br>Version <?= $v('version','1.0') ?> · <?= $v('effective_date_display') ?></div></div><h1>STATEMENT<br>OF WORK</h1><h3><?= $v('project_name') ?></h3><div class="cover-card"><div class="cover-grid"><div><strong>Client</strong><?= $v('client_legal_name') ?></div><div><strong>Delivery model</strong><?= $v('delivery_model') ?></div><div><strong>Effective date</strong><?= $v('effective_date_display') ?></div><div><strong>Duration</strong><?= $v('duration','To be confirmed') ?></div><div><strong>Planned start</strong><?= $v('start_date_display','To be confirmed') ?></div><div><strong>Planned completion</strong><?= $v('completion_date_display','To be confirmed') ?></div></div></div><div class="cover-note"><strong>DISTILLOGIC TECHNOLOGIES</strong><br>Software Engineering &amp; Technology Delivery<br>Patras, Greece · European Union</div></section>
<div class="page-break"><div class="brand"><img src="<?= $v('logo_url') ?>" alt="DISTILLOGIC TECHNOLOGIES"><div class="brand-meta"><span class="classification">COMMERCIAL CONFIDENTIAL</span><br><?= $v('sow_reference') ?></div></div>
<?php
    $section(1,'INTRODUCTION',function()use($v):void{?><p>This Statement of Work (“SOW”) defines the scope, deliverables, responsibilities, delivery approach, timeline and commercial terms between <strong>S. D. MELAS TRADING BUSINESS</strong>, trading as DISTILLOGIC TECHNOLOGIES, and <strong><?= $v('client_legal_name') ?></strong> for <?= $v('project_name') ?>.</p><p>This SOW shall be read with the applicable MSA, Commercial Proposal, Purchase Order, NDA, DPA where applicable, and other agreed contractual documents. The order of precedence in the applicable MSA shall govern inconsistencies.</p><?php });
    $section(2,'ENGAGEMENT OBJECTIVE',function()use($raw):void{?><p><?= nl2br(e($raw('objective'))) ?></p><h3>Expected outcome</h3><p><?= nl2br(e($raw('expected_outcome'))) ?></p><?php });
    $section(3,'BACKGROUND',function()use($raw,$items,$list):void{$list($items($raw('background')));?><p>DISTILLOGIC has been engaged to provide the engineering capability and delivery services described in this SOW.</p><?php });
    $section(4,'SCOPE OF SERVICES',function()use($raw,$items,$list):void{$list($items($raw('scope')));});
    $section(5,'DELIVERABLES',function()use($raw,$rows,$table):void{$table(['ID','Deliverable','Description','Target Date','Acceptance Criteria'],$rows($raw('deliverables'),5));?><p>Deliverables are complete when they satisfy the agreed acceptance criteria, subject to the acceptance process in this SOW.</p><?php });
    $section(6,'OUT OF SCOPE',function()use($raw,$items,$list):void{$list($items($raw('out_of_scope',"Additional functionality not described in scope\nUnidentified integrations or material redesign\nAdditional data migration or third-party remediation\nThird-party licences and hardware\nSupport outside the agreed window\nOnsite work unless agreed\nWork arising from material requirement changes")));?><p>Out-of-scope work may be evaluated through Change Control.</p><?php });
    $section(7,'DELIVERY MODEL',function()use($v):void{?><div class="highlight"><strong><?= $v('delivery_model') ?></strong></div><p>The selected model defines resourcing, delivery responsibility and billing.</p><?php });
    $section(8,'DELIVERY APPROACH',function():void{?><p>Requirements &amp; Confirmation → Architecture &amp; Technical Design → Engineering → Code Review → Quality Assurance → Deployment → Acceptance → Transition.</p><?php });
    $section(9,'PROJECT PHASES',function()use($raw,$rows,$table):void{$table(['Phase','Description','Indicative Duration'],$rows($raw('phases'),3));});
    $section(10,'PROJECT TIMELINE',function()use($v):void{?><table><tbody><tr><th>Planned Start</th><td><?= $v('start_date_display','To be confirmed') ?></td><th>Planned Completion</th><td><?= $v('completion_date_display','To be confirmed') ?></td></tr><tr><th>Indicative Duration</th><td colspan="3"><?= $v('duration','To be confirmed') ?></td></tr></tbody></table><p>The schedule assumes timely fulfilment of Client dependencies. Material external delays may require adjustment.</p><?php });
    $section(11,'MILESTONES',function()use($raw,$rows,$table):void{$table(['Milestone','Description','Planned Date','Commercial Trigger'],$rows($raw('milestones'),4));});
    $section(12,'TEAM STRUCTURE',function()use($raw,$rows,$table):void{$table(['Role','Seniority','Allocation','Main Responsibility'],$rows($raw('team'),4));?><p>Assignments may change subject to availability, with reasonably equivalent replacement capability.</p><?php });
    $section(13,'DISTILLOGIC RESPONSIBILITIES',function()use($raw,$items,$list):void{$list($items($raw('distillogic_responsibilities',"Deliver the agreed scope\nAssign appropriate resources\nProvide technical coordination and engineering quality\nProvide agreed documentation and status reporting\nEscalate risks and issues\nManage approved project changes")));});
    $section(14,'CLIENT RESPONSIBILITIES',function()use($raw,$items,$list):void{$list($items($raw('client_responsibilities',"Provide timely stakeholder access and accurate requirements\nProvide documentation, environments, credentials and test data\nCoordinate third parties\nProvide reviews, acceptance decisions, Purchase Orders and approvals")));?><p>Delays may affect delivery dates and effort.</p><?php });
    $section(15,'GOVERNANCE',function()use($raw):void{?><p><?= nl2br(e($raw('governance','Commercial, delivery and technical owners shall be nominated by both Parties. Project status, technical and executive reviews shall occur at the agreed cadence.'))) ?></p><?php });
    $section(16,'STATUS REPORTING',function():void{?><p>Status may cover completed work, work in progress, upcoming activities, milestones, risks, issues, dependencies, decisions, Change Requests and commercial impact.</p><?php });
    $section(17,'RISK MANAGEMENT',function():void{?><p>Material risks shall be identified, assigned an owner, assessed for impact and likelihood, and tracked with mitigation and target resolution.</p><?php });
    $section(18,'ISSUES & ESCALATION',function():void{?><p>Level 1: project or technical team. Level 2: Delivery Manager or Technical Lead. Level 3: management or authorised Client representative. Urgent production, security or commercial matters may be escalated directly.</p><?php });
    $section(19,'TECHNICAL ENVIRONMENT',function()use($raw):void{?><p><?= nl2br(e($raw('technical_environment'))) ?></p><?php });
    $section(20,'DEVELOPMENT PRACTICES',function():void{?><p>Practices may include private repositories, version control, branching, pull requests, peer review, coding standards, automated builds and tests, CI/CD, documentation and controlled releases.</p><?php });
    $section(21,'ENVIRONMENTS',function():void{?><div class="flow">Development → Test / QA → Staging / UAT → Production</div><p>Production access is governed by Client policy.</p><?php });
    $section(22,'QUALITY ASSURANCE',function():void{?><p>Quality activities may include unit, integration, API, functional, regression, automated, performance and release-validation testing.</p><?php });
    $section(23,'ACCEPTANCE PROCESS',function()use($v,$raw):void{?><p>The Client shall normally have <strong><?= $v('acceptance_days','5-10') ?> business days</strong> from formal delivery to accept or provide written rejection identifying unmet criteria. DISTILLOGIC shall address valid in-scope non-conformities.</p><p><?= nl2br(e($raw('acceptance_criteria'))) ?></p><?php });
    $section(24,'DEEMED ACCEPTANCE',function():void{?><p>Where contractually agreed, acceptance may be deemed when the review period expires without material rejection, the Client deploys or commercially uses the deliverable, or proceeds to a dependent milestone.</p><?php });
    $section(25,'DEFECT CLASSIFICATION',function():void{?><p><strong>Critical:</strong> prevents critical operation or creates material security/production risk. <strong>High:</strong> material function unavailable without workaround. <strong>Medium:</strong> impaired with workaround. <strong>Low:</strong> minor impact. Formal SLA targets require separate agreement.</p><?php });
    $section(26,'CHANGE CONTROL',function():void{?><p>A Change Request shall describe the request, reason, technical, delivery, timeline, resource and commercial impact. No material additional scope is included without written approval.</p><?php });
    $section(27,'CHANGE REQUEST APPROVAL',function():void{?><p>Approval may be through a signed Change Request, PO amendment, new PO, SOW amendment or other authorised written agreement.</p><?php });
    $section(28,'COMMERCIAL MODEL',function()use($v):void{?><div class="highlight"><strong><?= $v('commercial_model') ?></strong></div><?php });
    $section(29,'COMMERCIAL VALUE',function()use($v,$raw,$rows,$table):void{?><div class="highlight"><strong>Total Engagement Value:</strong> EUR <?= $v('total_value','To be confirmed') ?> — exclusive of VAT and applicable taxes.</div><?php $table(['Role / Item','Rate','Estimated Capacity'],$rows($raw('rates'),3));});
    $section(30,'PAYMENT SCHEDULE',function()use($raw,$rows,$table):void{$table(['Payment Trigger','Percentage','Amount'],$rows($raw('payment_schedule'),3));?><p>T&amp;M and dedicated-team engagements are normally billed monthly.</p><?php });
    $section(31,'PAYMENT TERMS',function()use($raw):void{?><p><?= nl2br(e($raw('payment_terms','Unless otherwise agreed in writing, payment is due Net 30 from a valid and undisputed invoice. Alternative terms require commercial approval.'))) ?></p><?php });
    $section(32,'INVOICING',function():void{?><p>Invoices may reference the PO, SOW, project, milestone, billing period, approved timesheets, rates and taxes. The undisputed portion remains payable on the agreed due date.</p><?php });
    $section(33,'PURCHASE ORDER',function()use($raw):void{?><p><?= nl2br(e($raw('purchase_order',"Where required, DISTILLOGIC shall normally require a valid Purchase Order or equivalent authorisation before material billable work begins. Authorised PO value shall not knowingly be exceeded without written approval."))) ?></p><?php });
    $section(34,'PROJECT EXPENSES',function():void{?><p>Unless included, approved travel, accommodation, local transport, visas, licences, project cloud services and specialised external services may be billed separately.</p><?php });
    $section(35,'INTELLECTUAL PROPERTY',function():void{?><p>Each Party retains pre-existing IP. Project-specific deliverables are governed by the agreed contract. DISTILLOGIC retains its methodologies, templates, frameworks, know-how and reusable tools. Transfer may be subject to full payment.</p><?php });
    $section(36,'CONFIDENTIALITY',function():void{?><p>Confidential information is protected under the applicable NDA, MSA and law. This SOW is Commercial Confidential.</p><?php });
    $section(37,'DATA PROTECTION',function():void{?><p>Where personal data is processed, the Parties shall comply with applicable requirements and enter an appropriate DPA where necessary.</p><?php });
    $section(38,'SECURITY',function():void{?><p>Reasonable practices may include role-based access, controlled authentication, secrets management, secure API design, dependency management, secure development, logging and auditability.</p><?php });
    $section(39,'THIRD-PARTY SERVICES',function():void{?><p>DISTILLOGIC is not responsible for failures caused solely by third-party systems outside its reasonable control. The Parties shall cooperate on mitigation.</p><?php });
    $section(40,'RESOURCE CHANGES',function():void{?><p>Personnel may be replaced where necessary due to availability, resignation, illness, performance or operations, with reasonably equivalent capability where practicable.</p><?php });
    $section(41,'RESOURCE NON-SOLICITATION',function():void{?><p>Personnel profiles are confidential. Direct-hire, conversion, non-solicitation and non-circumvention provisions are governed by the MSA.</p><?php });
    $section(42,'PROJECT SUSPENSION',function():void{?><p>Where permitted, material delivery may be suspended for overdue payment, material breach, missing essential access, unresolved security risk or legal restriction, normally after reasonable written notice.</p><?php });
    $section(43,'TERMINATION',function():void{?><p>Termination is governed primarily by the MSA. Accepted and authorised completed work, committed costs where applicable, approved third-party expenses and other properly due amounts remain payable.</p><?php });
    $section(44,'TRANSITION & HANDOVER',function()use($raw,$items,$list):void{$list($items($raw('handover',"Source-code handover\nTechnical documentation\nDeployment instructions\nKnowledge transfer\nOutstanding issue list\nOperational handover\nAgreed transition support")));});
    $section(45,'ASSUMPTIONS',function()use($raw,$items,$list):void{$list($items($raw('assumptions',"Requirements are materially accurate\nStakeholders remain available\nDependencies and access are provided on time\nThird-party systems behave as documented\nNo material undisclosed constraints exist\nApprovals are provided within agreed periods")));?><p>Materially incorrect assumptions may require Change Control.</p><?php });
    $section(46,'DOCUMENT VALIDITY',function():void{?><p>This SOW becomes effective upon authorised signature or other agreed written acceptance. Resource availability and dates remain subject to mobilisation confirmation.</p><?php });
    $section(47,'AUTHORISED COMMERCIAL CHANGES',function():void{?><p>No project-team member may independently modify scope, commercial value, payment terms, contractual obligations or milestones. Material changes require authorised agreement.</p><?php });
?>
</div>
<?php if($show(48)): ?><style>.signatures.bilateral-signatures .signature-card{height:160mm;min-height:160mm;display:flex;flex-direction:column}.signature-identity{min-height:64mm}.signature-controls{margin-top:auto}.signature-controls strong{display:block;margin:0 0 5px}.signature-space{height:68px;border:1px dashed #8aa8ce;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#718399;font-weight:bold}.date-space{height:34px;border-bottom:1px solid #596b80;display:flex;align-items:center;color:#176afc;font-weight:bold}.stamp-space{height:66px;border:1px dashed #8aa8ce;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#718399;font-weight:bold}</style><section class="page-break"><div class="brand"><img src="<?= $v('logo_url') ?>" alt="DISTILLOGIC TECHNOLOGIES"><div class="brand-meta"><span class="classification">COMMERCIAL CONFIDENTIAL</span><br><?= $v('sow_reference') ?></div></div><section class="sow-section"><h2>48. SIGNATURES</h2><p>Signed by authorised representatives of the Parties.</p></section><div class="signatures bilateral-signatures"><div class="signature-card"><h3>For DISTILLOGIC</h3><div class="signature-identity"><strong>Legal Entity</strong><div>S. D. MELAS TRADING BUSINESS</div><br><strong>Trading Name</strong><div>DISTILLOGIC TECHNOLOGIES</div><br><strong>Name</strong><div>Spiros Melas</div><br><strong>Title</strong><div>Managing Director</div></div><div class="signature-controls"><strong>Signature</strong><div class="signature-space">AUTHORISED SIGNATURE PLACEHOLDER</div><strong>Date</strong><div class="date-space"></div><strong>Stamp</strong><div class="stamp-space">COMPANY STAMP PLACEHOLDER</div></div></div><div class="signature-card"><h3>For the Client</h3><div class="signature-identity"><strong>Company</strong><div><?= $v('client_legal_name') ?></div><br><strong>Name</strong><div><?= $v('client_contact_name','—') ?></div><br><strong>Title</strong><div><?= $v('client_contact_title','—') ?></div></div><div class="signature-controls"><strong>Signature</strong><div class="signature-space">AUTHORISED SIGNATURE PLACEHOLDER</div><strong>Date</strong><div class="date-space"></div><strong>Stamp</strong><div class="stamp-space">COMPANY STAMP PLACEHOLDER</div></div></div></div></section><?php endif; ?>
<?php if($raw('appendix_a')||$raw('appendix_b')||$raw('appendix_c')||$raw('appendix_d')): ?><section class="page-break"><div class="brand"><img src="<?= $v('logo_url') ?>" alt="DISTILLOGIC TECHNOLOGIES"><div class="brand-meta"><span class="classification">APPENDICES</span><br><?= $v('sow_reference') ?></div></div><?php foreach(['appendix_a'=>'APPENDIX A — DELIVERABLES','appendix_b'=>'APPENDIX B — PROJECT PLAN','appendix_c'=>'APPENDIX C — TEAM & COMMERCIAL RATES','appendix_d'=>'APPENDIX D — ACCEPTANCE CRITERIA'] as $key=>$title): if($raw($key)==='')continue; ?><section class="sow-section"><h2><?= e($title) ?></h2><div class="appendix"><?= nl2br(e($raw($key))) ?></div></section><?php endforeach; ?></section><?php endif; ?>
<div class="doc-footer">DISTILLOGIC TECHNOLOGIES · Software Engineering &amp; Technology Delivery · <?= $v('sow_reference') ?><br>Legal review recommended before formal execution.</div></main></body></html>
<?php return (string)ob_get_clean();
}
