<?php
declare(strict_types=1);

require __DIR__ . '/bootstrap.php';
$user = require_login();
ensure_customer_workspace_schema();
$id = trim((string)($_GET['id'] ?? $_POST['id'] ?? ''));
$isExisting = preg_match('/^[a-f0-9-]{36}$/i', $id) === 1;
$errors = [];
$approvalEmail = 'melas@distillogic.gr';
$loadSow = static function(string $documentId): array {
    $statement=db()->prepare("SELECT d.*,c.name AS company_name,c.legal_name,c.email AS company_email,c.contact_name,c.contact_title FROM company_documents d JOIN companies c ON c.id=d.company_id WHERE d.id=? AND d.document_type='sow' AND c.deleted_at IS NULL LIMIT 1");
    $statement->execute([$documentId]); $row=$statement->fetch();
    if(!$row){http_response_code(404);exit('Το SOW δεν βρέθηκε.');} return $row;
};
$sow=$isExisting?$loadSow($id):null;
$data=$sow?(json_decode((string)$sow['data_json'],true)?:[]):[];
$companyId=(int)($sow['company_id']??$_GET['company_id']??$_POST['company_id']??0);
$companies=db()->query("SELECT id,name,legal_name,email,contact_name,contact_title FROM companies WHERE deleted_at IS NULL ORDER BY name")->fetchAll();
$companyById=[];foreach($companies as $row)$companyById[(int)$row['id']]=$row;
$sectionLabels=[1=>'Introduction',2=>'Engagement Objective',3=>'Background',4=>'Scope of Services',5=>'Deliverables',6=>'Out of Scope',7=>'Delivery Model',8=>'Delivery Approach',9=>'Project Phases',10=>'Project Timeline',11=>'Milestones',12=>'Team Structure',13=>'DISTILLOGIC Responsibilities',14=>'Client Responsibilities',15=>'Governance',16=>'Status Reporting',17=>'Risk Management',18=>'Issues & Escalation',19=>'Technical Environment',20=>'Development Practices',21=>'Environments',22=>'Quality Assurance',23=>'Acceptance Process',24=>'Deemed Acceptance',25=>'Defect Classification',26=>'Change Control',27=>'Change Request Approval',28=>'Commercial Model',29=>'Commercial Value',30=>'Payment Schedule',31=>'Payment Terms',32=>'Invoicing',33=>'Purchase Order',34=>'Project Expenses',35=>'Intellectual Property',36=>'Confidentiality',37=>'Data Protection',38=>'Security',39=>'Third-Party Services',40=>'Resource Changes',41=>'Resource Non-Solicitation',42=>'Project Suspension',43=>'Termination',44=>'Transition & Handover',45=>'Assumptions',46=>'Document Validity',47=>'Authorised Commercial Changes',48=>'Signatures'];
$coreSections=[1,2,4,5,6,7,10,11,12,13,14,15,23,26,28,29,30,31,33,35,36,45,46,47,48];
$fullSections=range(1,48);
$logo=static function():string{$site=rtrim((string)(crm_config()['app']['site_url']??'https://www.distillogic.gr'),'/');$path=dirname(__DIR__).'/assets/logo/distillogic-logo-light.svg';$content=is_file($path)?file_get_contents($path):false;return $content===false?$site.'/assets/logo/distillogic-logo-light.svg':'data:image/svg+xml;base64,'.base64_encode($content);};

if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$action=(string)($_POST['action']??'save');
    contract_post_preflight($action,$errors,$sow,'sow',$user);
    if($sow&&contract_action_requires_prerequisites($action)){$prerequisiteErrors=contract_prerequisite_errors((int)$sow['company_id'],'sow');if($prerequisiteErrors){$errors=array_merge($errors,$prerequisiteErrors);$action='blocked_by_contract_flow';}}
    if($action==='save'){
        $companyId=(int)($_POST['company_id']??0);$client=$companyById[$companyId]??null;
        $project=trim(mb_substr((string)($_POST['project_name']??''),0,220));
        $email=trim(mb_substr((string)($_POST['client_email']??''),0,320));$confirm=trim((string)($_POST['client_email_confirm']??''));
        $effective=(string)($_POST['effective_date']??date('Y-m-d'));
        $selected=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['selected_sections']??[])),static fn(int $n):bool=>$n>=1&&$n<=48)));sort($selected);
        $mandatory=[1,4,5,10,12,23,26,28,29,30,48];
        if(!$client)$errors[]='Επιλέξτε πελάτη.';if($project==='')$errors[]='Το project είναι υποχρεωτικό.';
        if(!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Το email του πελάτη δεν είναι έγκυρο.';
        if(mb_strtolower($email)!==mb_strtolower($confirm))$errors[]='Τα δύο email του πελάτη δεν είναι ίδια.';
        if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$effective))$errors[]='Η ημερομηνία δεν είναι έγκυρη.';
        if(array_diff($mandatory,$selected))$errors[]='Τα βασικά sections του SOW πρέπει να παραμείνουν επιλεγμένα.';
        if(!$errors&&$client){
            $bufferLevel=ob_get_level();
            $saveStage='prepare';
            try {
            $reference=$sow?(string)$sow['document_reference']:'DL-SOW-'.date('Ymd').'-'.$companyId.'-'.strtoupper(bin2hex(random_bytes(2)));
            $dateDisplay=static fn(string $date):string=>$date&&preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)?(new DateTimeImmutable($date))->format('d/m/Y'):'To be confirmed';
            $keys=['objective','expected_outcome','background','scope','deliverables','out_of_scope','phases','milestones','team','distillogic_responsibilities','client_responsibilities','governance','technical_environment','acceptance_criteria','rates','payment_schedule','payment_terms','purchase_order','handover','assumptions','appendix_a','appendix_b','appendix_c','appendix_d'];
            $documentData=['sow_reference'=>$reference,'version'=>trim((string)($_POST['version']??'1.0'))?:'1.0','effective_date'=>$effective,'effective_date_display'=>$dateDisplay($effective),'project_name'=>$project,'client_legal_name'=>trim((string)($_POST['client_legal_name']??''))?:((string)($client['legal_name']?:$client['name'])),'client_email'=>$email,'client_contact_name'=>trim((string)($_POST['client_contact_name']??'')),'client_contact_title'=>trim((string)($_POST['client_contact_title']??'')),'delivery_model'=>trim((string)($_POST['delivery_model']??'')),'commercial_model'=>trim((string)($_POST['commercial_model']??'')),'total_value'=>trim((string)($_POST['total_value']??'')),'start_date'=>(string)($_POST['start_date']??''),'start_date_display'=>$dateDisplay((string)($_POST['start_date']??'')),'completion_date'=>(string)($_POST['completion_date']??''),'completion_date_display'=>$dateDisplay((string)($_POST['completion_date']??'')),'duration'=>trim((string)($_POST['duration']??'')),'acceptance_days'=>trim((string)($_POST['acceptance_days']??'5-10')),'selected_sections'=>$selected,'profile'=>(string)($_POST['profile']??'core'),'logo_url'=>$logo()];
            foreach($keys as $key)$documentData[$key]=trim((string)($_POST[$key]??''));
            $saveStage='template';
            if(!is_file(__DIR__.'/sow-template.php'))throw new RuntimeException('Missing sow-template.php');
            require_once __DIR__ . '/sow-template.php';
            $html=sow_document_html($documentData);$fileName=preg_replace('/[^A-Za-z0-9._-]/','-',$reference).'.doc';
            $saveStage='database';
            db()->beginTransaction();
            if($sow){$update=db()->prepare("UPDATE company_documents SET company_id=?,document_status='draft',title=?,file_name=?,mime_type='application/msword; charset=UTF-8',content=?,data_json=?,effective_date=?,client_signed_file_name=NULL,client_signed_pdf=NULL,client_signed_at=NULL,approval_code_hash=NULL,approval_code_expires_at=NULL,approval_attempts=0,approval_requested_at=NULL,approval_requested_by=NULL,approved_at=NULL,approval_confirmed_by=NULL,final_signed_file_name=NULL,final_signed_pdf=NULL,final_signed_at=NULL WHERE id=? AND document_type='sow'");$update->execute([$companyId,'Statement of Work — '.$project,$fileName,$html,json_encode($documentData,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$effective,$id]);}
            else{$id=uuid_v4();$insert=db()->prepare("INSERT INTO company_documents(id,company_id,created_by,document_type,document_status,document_reference,title,file_name,mime_type,content,data_json,effective_date) VALUES(?,?,?,'sow','draft',?,?,?,'application/msword; charset=UTF-8',?,?,?)");$insert->execute([$id,$companyId,$user['id'],$reference,'Statement of Work — '.$project,$fileName,$html,json_encode($documentData,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$effective]);}
            db()->prepare('UPDATE companies SET legal_name=?,email=?,contact_name=?,contact_title=? WHERE id=?')->execute([$documentData['client_legal_name'],$email,$documentData['client_contact_name']?:null,$documentData['client_contact_title']?:null,$companyId]);
            db()->commit();
            flash('success','Το SOW αποθηκεύτηκε ως draft. Κάθε αλλαγή ακυρώνει προηγούμενο PDF και έγκριση.');redirect_to('sow.php?id='.urlencode($id));
            }catch(Throwable $error){
                if(db()->inTransaction())db()->rollBack();
                while(ob_get_level()>$bufferLevel)ob_end_clean();
                $failureReference='SOW-'.date('Ymd-His').'-'.bin2hex(random_bytes(3));
                error_log('['.$failureReference.'] stage='.$saveStage.' '.get_class($error).': '.$error->getMessage().' at '.$error->getFile().':'.$error->getLine());
                $errors[]='Το SOW δεν αποθηκεύτηκε. Τα πεδία παραμένουν στη φόρμα. Κωδικός ελέγχου: '.$failureReference.'.';
            }
        }$data=$_POST;$data['selected_sections']=$selected;
    }
    if($sow&&$action==='upload_client_signed'){
        $file=$_FILES['client_signed_pdf']??null;
        if($sow['approved_at'])$errors[]='Το εγκεκριμένο SOW είναι κλειδωμένο. Αποθηκεύστε νέα draft έκδοση για αλλαγές.';
        elseif(!is_array($file)||(int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)$errors[]='Επιλέξτε το SOW που υπέγραψε ο πελάτης.';
        elseif((int)$file['size']<100||(int)$file['size']>12*1024*1024)$errors[]='Το PDF πρέπει να είναι έως 12 MB.';
        else{$tmp=(string)$file['tmp_name'];$content=is_uploaded_file($tmp)?file_get_contents($tmp):false;$mime=$content===false?'':(new finfo(FILEINFO_MIME_TYPE))->file($tmp);if($content===false||$mime!=='application/pdf'||!str_starts_with($content,'%PDF-'))$errors[]='Το αρχείο πρέπει να είναι πραγματικό PDF.';else{$name=preg_replace('/[^A-Za-z0-9._-]/','-',basename((string)$file['name']))?:'client-signed-sow.pdf';db()->prepare("UPDATE company_documents SET document_status='client_signed',client_signed_file_name=?,client_signed_pdf=?,client_signed_at=NOW(),final_signed_file_name=NULL,final_signed_pdf=NULL,final_signed_at=NULL,approved_at=NULL,approval_confirmed_by=NULL,approval_code_hash=NULL,approval_code_expires_at=NULL,approval_attempts=0,approval_requested_at=NULL,approval_requested_by=NULL WHERE id=?")->execute([$name,$content,$id]);flash('success','Το client-signed SOW αποθηκεύτηκε. Ζητήστε CEO approval.');redirect_to('sow.php?id='.urlencode($id));}}
    }
    if($sow&&$action==='request_approval'){
        if(!$sow['client_signed_pdf'])$errors[]='Ανεβάστε πρώτα το SOW που υπέγραψε ο πελάτης.';elseif($sow['approved_at'])$errors[]='Το SOW έχει ήδη εγκριθεί.';elseif($sow['approval_requested_at']&&strtotime((string)$sow['approval_requested_at'])>time()-60)$errors[]='Περιμένετε ένα λεπτό πριν ζητήσετε νέο κωδικό.';else{$code=(string)random_int(100000,999999);$expires=(new DateTimeImmutable('+10 minutes'))->format('Y-m-d H:i:s');$mail='<div style="font-family:Arial;color:#10213a;max-width:620px"><h2 style="color:#176afc">SOW approval</h2><p>Ζητήθηκε έγκριση του client-signed PDF για <strong>'.e($sow['document_reference']).'</strong> προς <strong>'.e($sow['company_name']).'</strong>.</p><p style="font-size:32px;font-weight:800;letter-spacing:8px;background:#eef5ff;padding:18px;text-align:center;border-radius:10px">'.e($code).'</p><p>Ο κωδικός λήγει σε 10 λεπτά.</p></div>';if(send_crm_email($approvalEmail,'SOW approval code — '.$sow['document_reference'],$mail)){db()->prepare("UPDATE company_documents SET document_status='approval_pending',approval_code_hash=?,approval_code_expires_at=?,approval_attempts=0,approval_requested_at=NOW(),approval_requested_by=? WHERE id=?")->execute([password_hash($code,PASSWORD_DEFAULT),$expires,$user['id'],$id]);flash('success','Ο κωδικός στάλθηκε στο melas@distillogic.gr.');redirect_to('sow.php?id='.urlencode($id));}$errors[]='Δεν ήταν δυνατή η αποστολή του κωδικού.';}
    }
    if($sow&&$action==='verify_approval'){
        $code=preg_replace('/\D/','',(string)($_POST['approval_code']??''));
        if(strlen((string)$code)!==6)$errors[]='Ο κωδικός πρέπει να έχει 6 ψηφία.';elseif(!$sow['approval_code_hash']||!$sow['approval_code_expires_at'])$errors[]='Ζητήστε πρώτα κωδικό.';elseif((int)$sow['approval_attempts']>=5)$errors[]='Έγιναν πολλές προσπάθειες.';elseif(new DateTimeImmutable((string)$sow['approval_code_expires_at'])<new DateTimeImmutable())$errors[]='Ο κωδικός έληξε.';elseif(!password_verify((string)$code,(string)$sow['approval_code_hash'])){db()->prepare('UPDATE company_documents SET approval_attempts=approval_attempts+1 WHERE id=?')->execute([$id]);$errors[]='Ο κωδικός δεν είναι σωστός.';}else{db()->prepare("UPDATE company_documents SET document_status='approval_pending',approved_at=NOW(),approval_confirmed_by=?,approval_code_hash=NULL,approval_code_expires_at=NULL,approval_attempts=0 WHERE id=?")->execute([$user['id'],$id]);flash('success','Η έγκριση CEO επιβεβαιώθηκε. Δημιουργήστε τώρα την πλήρως υπογεγραμμένη έκδοση.');redirect_to('document-finalize.php?id='.urlencode($id));}
    }
    if($sow&&$action==='send_final'){
        $documentData=json_decode((string)$sow['data_json'],true)?:[];$email=trim((string)($documentData['client_email']??''));$confirm=trim((string)($_POST['send_email_confirm']??''));
        if(!$sow['approved_at']||!$sow['final_signed_pdf'])$errors[]='Δεν υπάρχει CEO-approved PDF.';elseif(!filter_var($email,FILTER_VALIDATE_EMAIL)||mb_strtolower($email)!==mb_strtolower($confirm))$errors[]='Πληκτρολογήστε ξανά σωστά το email του πελάτη.';else{$mail='<div style="font-family:Arial;color:#10213a;max-width:640px"><h2 style="color:#176afc">Statement of Work</h2><p>Dear '.e((string)($documentData['client_contact_name']??'Client')).',</p><p>Please find attached the Statement of Work for <strong>'.e((string)($documentData['project_name']??'the engagement')).'</strong>.</p><p>Reference: <strong>'.e($sow['document_reference']).'</strong></p><p>DISTILLOGIC TECHNOLOGIES<br>Software Engineering &amp; Technology Delivery</p></div>';$sent=send_crm_email($email,'DISTILLOGIC Statement of Work — '.$sow['document_reference'],$mail,[['filename'=>(string)$sow['final_signed_file_name'],'mime'=>'application/pdf','content'=>(string)$sow['final_signed_pdf']]]);db()->prepare("INSERT INTO company_document_deliveries(id,document_id,requested_by,recipient_email,recipient_role,delivery_status,sent_at) VALUES(?,?,?,?,'client',?,?) ON DUPLICATE KEY UPDATE requested_by=VALUES(requested_by),delivery_status=VALUES(delivery_status),sent_at=VALUES(sent_at)")->execute([uuid_v4(),$id,$user['id'],$email,$sent?'sent':'failed',$sent?date('Y-m-d H:i:s'):null]);if($sent){db()->prepare("UPDATE company_documents SET document_status='sent' WHERE id=?")->execute([$id]);flash('success','Το εγκεκριμένο SOW στάλθηκε στο '.$email.'.');redirect_to('sow.php?id='.urlencode($id));}$errors[]='Η αποστολή απέτυχε.';}
    }
    if($sow&&$action==='mark_accepted'&&(!$sow['approved_at']||!$sow['final_signed_pdf'])){$errors[]='Το SOW μπορεί να γίνει Accepted μόνο αφού εγκριθεί η τελική έκδοση από τον CEO.';}
    elseif($sow&&in_array($action,['mark_accepted','mark_rejected','mark_expired'],true)){$status=['mark_accepted'=>'accepted','mark_rejected'=>'rejected','mark_expired'=>'expired'][$action];db()->prepare('UPDATE company_documents SET document_status=? WHERE id=?')->execute([$status,$id]);flash('success','Η κατάσταση του SOW ενημερώθηκε.');redirect_to('sow.php?id='.urlencode($id));}
    if($isExisting&&!$errors){$sow=$loadSow($id);$data=json_decode((string)$sow['data_json'],true)?:[];}
}
if(!$data){$client=$companyById[$companyId]??null;$profile=(string)($_GET['profile']??'core');$data=['profile'=>$profile,'effective_date'=>date('Y-m-d'),'version'=>'1.0','client_legal_name'=>$client?(string)($client['legal_name']?:$client['name']):'','client_email'=>$client['email']??'','client_contact_name'=>$client['contact_name']??'','client_contact_title'=>$client['contact_title']??'','delivery_model'=>'Fixed Price / Work Package','commercial_model'=>'Fixed Price','acceptance_days'=>'5-10','payment_terms'=>'Unless otherwise agreed in writing, payment is due Net 30 from the date of a valid and undisputed invoice.','selected_sections'=>$profile==='full'?$fullSections:$coreSections];}
$selected=array_map('intval',(array)($data['selected_sections']??$coreSections));$contractPrerequisites=$sow?contract_prerequisite_errors((int)$sow['company_id'],'sow'):[];$statusLabels=['draft'=>'Draft','pdf_ready'=>'PDF ready for approval','approval_pending'=>'Pending CEO approval','approved_pdf'=>'CEO-approved PDF','sent'=>'Sent','accepted'=>'Accepted','rejected'=>'Rejected','expired'=>'Expired'];
render_header($sow?'SOW '.$sow['document_reference']:'Νέο SOW',$user);
?>
<div class="page-heading"><div><p class="eyebrow">STATEMENTS OF WORK</p><h1><?= $sow?e($sow['document_reference']):'Νέο Statement of Work' ?></h1><p>Client-specific SOW που κλειδώνει scope, deliverables, timeline, team, acceptance και commercials.</p></div><div class="actions"><a class="button" href="<?= e(crm_url('sows.php')) ?>">Όλα τα SOW</a><?php if($sow): ?><a class="button primary" target="_blank" href="<?= e(crm_url('sow-view.php?id='.urlencode($id))) ?>">Προβολή / Save PDF</a><?php endif; ?></div></div>
<?php if($errors): ?><div class="alert error"><?= e(implode(' ',array_unique($errors))) ?></div><?php endif; ?>
<?php if($contractPrerequisites): ?><div class="alert warning"><strong>Το signing flow είναι κλειδωμένο.</strong> <?= e(implode(' ',$contractPrerequisites)) ?> Μπορείτε μόνο να προετοιμάσετε το draft.</div><?php endif; ?>
<?php if($sow&&$sow['approved_at']&&$sow['client_signed_pdf']&&!$sow['final_signed_pdf']): ?><div class="alert info"><strong>Η CEO έγκριση ολοκληρώθηκε.</strong> Απομένει η τοποθέτηση της υπογραφής, της ημερομηνίας έγκρισης CEO και της σφραγίδας της DISTILLOGIC. <a class="button compact primary" href="<?= e(crm_url('document-finalize.php?id='.urlencode($id))) ?>">Δημιουργία Fully Signed PDF</a></div><?php endif; ?>
<?php if($sow): ?><section class="card proposal-status-card"><div><span class="proposal-status proposal-status-<?= e($sow['document_status']) ?>"><?= e($statusLabels[$sow['document_status']]??$sow['document_status']) ?></span><h2><?= e($sow['title']) ?></h2><p><?= e($sow['company_name']) ?> · <?= e(format_datetime($sow['updated_at'])) ?></p></div><div class="actions"><a class="button" href="<?= e(crm_url('customer.php?id='.(int)$sow['company_id'])) ?>">Καρτέλα πελάτη</a><?php if($sow['final_signed_pdf']): ?><a class="button primary" href="<?= e(crm_url('sow-download.php?id='.urlencode($id).'&pdf=1')) ?>">Λήψη PDF</a><?php endif; ?></div></section><?php endif; ?>
<form method="post" class="stack proposal-editor"><?= csrf_field() ?><input type="hidden" name="action" value="save"><?php if($sow): ?><input type="hidden" name="id" value="<?= e($id) ?>"><?php endif; ?>
<section class="card form-section"><header><h2>1. Document control & πελάτης</h2></header><div class="form-grid"><label>Πελάτης *<select name="company_id" required><?php foreach($companies as $company): ?><option value="<?= (int)$company['id'] ?>" <?= $companyId===(int)$company['id']?'selected':'' ?>><?= e($company['name']) ?></option><?php endforeach; ?></select></label><label>Project / Work Package *<input name="project_name" maxlength="220" required value="<?= e($data['project_name']??'') ?>"></label><label>Νομική επωνυμία *<input name="client_legal_name" required value="<?= e($data['client_legal_name']??'') ?>"></label><label>Effective date *<input type="date" name="effective_date" required value="<?= e($data['effective_date']??date('Y-m-d')) ?>"></label><label>Version<input name="version" value="<?= e($data['version']??'1.0') ?>"></label><label>Profile<select name="profile"><option value="core" <?= ($data['profile']??'')==='core'?'selected':'' ?>>Core project SOW</option><option value="full" <?= ($data['profile']??'')==='full'?'selected':'' ?>>Full framework</option></select></label><label>Email πελάτη *<input type="email" name="client_email" required value="<?= e($data['client_email']??'') ?>"></label><label>Επιβεβαίωση email *<input type="email" name="client_email_confirm" required autocomplete="off" placeholder="Γράψτε ξανά το email"></label><label>Εκπρόσωπος<input name="client_contact_name" value="<?= e($data['client_contact_name']??'') ?>"></label><label>Ιδιότητα<input name="client_contact_title" value="<?= e($data['client_contact_title']??'') ?>"></label><label>Delivery model<input name="delivery_model" value="<?= e($data['delivery_model']??'') ?>"></label><label>Duration<input name="duration" value="<?= e($data['duration']??'') ?>"></label><label>Planned start<input type="date" name="start_date" value="<?= e($data['start_date']??'') ?>"></label><label>Planned completion<input type="date" name="completion_date" value="<?= e($data['completion_date']??'') ?>"></label></div></section>
<section class="card form-section"><header><h2>2. Objective → Scope → Deliverables</h2><p>Συμπληρώστε το αντικείμενο του έργου και οργανώστε τα παραδοτέα σε ξεχωριστές γραμμές.</p></header><div class="form-grid"><label class="field-full">Engagement objective<textarea name="objective"><?= e($data['objective']??'') ?></textarea></label><label class="field-full">Expected outcome<textarea name="expected_outcome"><?= e($data['expected_outcome']??'') ?></textarea></label><label class="field-full">Background<textarea name="background"><?= e($data['background']??'') ?></textarea></label><label class="field-full">Scope of services<textarea name="scope"><?= e($data['scope']??'') ?></textarea></label><label class="field-full">Deliverables — ID | Deliverable | Description | Target Date | Acceptance Criteria<textarea data-document-rows name="deliverables"><?= e($data['deliverables']??'') ?></textarea></label><label class="field-full">Out of scope<textarea name="out_of_scope"><?= e($data['out_of_scope']??'') ?></textarea></label></div></section>
<section class="card form-section"><header><h2>3. Timeline → Team → Governance</h2></header><div class="form-grid"><label class="field-full">Project phases — Phase | Description | Duration<textarea data-document-rows name="phases"><?= e($data['phases']??'') ?></textarea></label><label class="field-full">Milestones — Milestone | Description | Date | Commercial Trigger<textarea data-document-rows name="milestones"><?= e($data['milestones']??'') ?></textarea></label><label class="field-full">Team — Role | Seniority | Allocation | Responsibility<textarea data-document-rows name="team"><?= e($data['team']??'') ?></textarea></label><label class="field-full">DISTILLOGIC responsibilities<textarea name="distillogic_responsibilities"><?= e($data['distillogic_responsibilities']??'') ?></textarea></label><label class="field-full">Client responsibilities<textarea name="client_responsibilities"><?= e($data['client_responsibilities']??'') ?></textarea></label><label class="field-full">Governance<textarea name="governance"><?= e($data['governance']??'') ?></textarea></label><label class="field-full">Technical environment<textarea name="technical_environment"><?= e($data['technical_environment']??'') ?></textarea></label></div></section>
<section class="card form-section"><header><h2>4. Acceptance → Commercials → Change Control</h2></header><div class="form-grid"><label>Acceptance period<input name="acceptance_days" value="<?= e($data['acceptance_days']??'5-10') ?>"></label><label>Commercial model<input name="commercial_model" value="<?= e($data['commercial_model']??'') ?>"></label><label>Total engagement value (EUR)<input name="total_value" value="<?= e($data['total_value']??'') ?>"></label><label class="field-full">Acceptance criteria<textarea name="acceptance_criteria"><?= e($data['acceptance_criteria']??'') ?></textarea></label><label class="field-full">T&M rates — Role | Rate | Capacity<textarea data-document-rows name="rates"><?= e($data['rates']??'') ?></textarea></label><label class="field-full">Payment schedule — Trigger | Percentage | Amount<textarea data-document-rows name="payment_schedule"><?= e($data['payment_schedule']??'') ?></textarea></label><label class="field-full">Payment terms<textarea name="payment_terms"><?= e($data['payment_terms']??'') ?></textarea></label><label class="field-full">Purchase Order<textarea name="purchase_order"><?= e($data['purchase_order']??'') ?></textarea></label><label class="field-full">Assumptions<textarea name="assumptions"><?= e($data['assumptions']??'') ?></textarea></label><label class="field-full">Transition & handover<textarea name="handover"><?= e($data['handover']??'') ?></textarea></label></div></section>
<section class="card form-section"><header><h2>5. Optional appendices</h2></header><div class="form-grid"><label class="field-full">Appendix A — Deliverables<textarea name="appendix_a"><?= e($data['appendix_a']??'') ?></textarea></label><label class="field-full">Appendix B — Project Plan<textarea name="appendix_b"><?= e($data['appendix_b']??'') ?></textarea></label><label class="field-full">Appendix C — Team & Rates<textarea name="appendix_c"><?= e($data['appendix_c']??'') ?></textarea></label><label class="field-full">Appendix D — Acceptance Tests<textarea name="appendix_d"><?= e($data['appendix_d']??'') ?></textarea></label></div></section>
<section class="card form-section"><header><h2>6. Sections τελικού SOW</h2><p>Τα κρίσιμα sections είναι κλειδωμένα ως υποχρεωτικά.</p></header><div class="proposal-section-picker"><?php foreach($sectionLabels as $number=>$label): ?><label><input type="checkbox" name="selected_sections[]" value="<?= $number ?>" <?= in_array($number,$selected,true)?'checked':'' ?> <?= in_array($number,[1,4,5,10,12,23,26,28,29,30,48],true)?'required':'' ?>><span><?= $number ?>. <?= e($label) ?></span></label><?php endforeach; ?></div><div class="actions"><button class="button primary"><?= $sow?'Αποθήκευση νέας draft έκδοσης':'Δημιουργία SOW' ?></button></div></section></form>
<?php if($sow): ?><section class="proposal-workflow <?= $contractPrerequisites?'contract-flow-locked':'' ?>">
<article class="card signing-step <?= $sow['client_signed_pdf']?'is-complete':'is-current' ?>"><div class="step-number">1</div><div><h2>Υπογραφή πελάτη</h2><p>Ανεβάστε το PDF που επέστρεψε υπογεγραμμένο και σφραγισμένο ο πελάτης.</p><form method="post" enctype="multipart/form-data"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($id) ?>"><input type="hidden" name="action" value="upload_client_signed"><input type="file" name="client_signed_pdf" accept="application/pdf,.pdf" required><button class="button primary" <?= $sow['approved_at']?'disabled':'' ?>>Αποθήκευση client-signed SOW</button></form></div></article>
<article class="card signing-step <?= $sow['approved_at']?'is-complete':($sow['client_signed_pdf']?'is-current':'is-locked') ?>"><div class="step-number">2</div><div><h2>CEO Approval</h2><p>Ο κωδικός αποστέλλεται αποκλειστικά στο <strong>melas@distillogic.gr</strong>.</p><?php if(!$sow['approved_at']): ?><form method="post"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($id) ?>"><button class="button primary" name="action" value="request_approval" <?= !$sow['client_signed_pdf']?'disabled':'' ?>>Αποστολή κωδικού</button></form><form method="post" class="otp-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($id) ?>"><input type="hidden" name="action" value="verify_approval"><input name="approval_code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="000000" required><button class="button primary" <?= !$sow['client_signed_pdf']?'disabled':'' ?>>Επιβεβαίωση CEO</button></form><?php else: ?><div class="step-success">✓ Εγκρίθηκε <?= e(format_datetime($sow['approved_at'])) ?></div><?php endif; ?></div></article>
<article class="card signing-step <?= $sow['final_signed_pdf']?'is-complete':($sow['approved_at']?'is-current':'is-locked') ?>"><div class="step-number">3</div><div><h2>Fully Signed PDF</h2><p>Τοποθέτηση υπογραφής, ημερομηνίας έγκρισης CEO και σφραγίδας DISTILLOGIC μέσα στα προκαθορισμένα πλαίσια.</p><a class="button primary <?= $sow['approved_at']?'':'disabled' ?>" href="<?= $sow['approved_at']?e(crm_url('document-finalize.php?id='.urlencode($id))):'#' ?>"><?= $sow['final_signed_pdf']?'Ολοκληρώθηκε':'Δημιουργία τελικής έκδοσης' ?></a></div></article>
<article class="card signing-step <?= $sow['document_status']==='sent'?'is-complete':($sow['final_signed_pdf']?'is-current':'is-locked') ?>"><div class="step-number">4</div><div><h2>Αποστολή και στους δύο συμβαλλομένους</h2><p>Πληκτρολογήστε ξανά το email: <strong><?= e($data['client_email']??'') ?></strong></p><form method="post"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($id) ?>"><input type="hidden" name="action" value="send_final"><input type="email" name="send_email_confirm" required placeholder="Επιβεβαίωση email"><button class="button primary" <?= !$sow['final_signed_pdf']?'disabled':'' ?>>Αποστολή Fully Signed SOW</button></form></div></article>
<article class="card signing-step"><div class="step-number">5</div><div><h2>Κατάσταση</h2><form method="post"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($id) ?>"><button class="button primary" name="action" value="mark_accepted" <?= !$sow['final_signed_pdf']?'disabled':'' ?>>Accepted</button><button class="button" name="action" value="mark_rejected">Rejected</button><button class="button" name="action" value="mark_expired">Expired</button></form></div></article>
</section><?php endif; ?>
<link rel="stylesheet" href="<?= e(crm_url('assets/document-rows.css?v=20260916')) ?>">
<script src="<?= e(crm_url('assets/document-rows.js?v=20260916')) ?>" defer></script>
<?php render_footer(); ?>
