<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';$user=require_login();
if(!can_view_all_sales_financials($user)){http_response_code(403);exit('Απαιτείται εξουσιοδοτημένος διαχειριστής Melas.');}
require __DIR__.'/test-data-cleanup-workflow.php';ensure_lead_schema();test_cleanup_schema();$error=null;$result=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();try{
        personnel_reauth($user,$_POST);$action=sales_text($_POST,'action',1,20);
        if($action==='preview'){$plan=test_cleanup_plan();$_SESSION['cleanup_v36_plan']=['hash'=>test_cleanup_hash($plan),'until'=>time()+900];$result=$plan;}
        elseif($action==='execute'){
            if(($_POST['confirm']??'')!=='ΔΙΑΓΡΑΦΗ ΔΟΚΙΜΩΝ MELAS'||($_POST['backup_confirmed']??'')!=='1')throw new InvalidArgumentException('Προηγείται έλεγχος λίστας και επιβεβαίωση αντιγράφου βάσης από Plesk.');
            $permit=$_SESSION['cleanup_v36_plan']??[];if(($permit['until']??0)<time())throw new InvalidArgumentException('Η προεπισκόπηση έληξε. Ανοίξτε νέα λίστα.');
            $backup=test_cleanup_execute($user,(string)($permit['hash']??''));unset($_SESSION['cleanup_v36_plan']);flash('success','Τα ελεγμένα δοκιμαστικά δεδομένα αφαιρέθηκαν. Αντίγραφο επαναφοράς: '.$backup);redirect_to('test-data-cleanup.php');
        }elseif($action==='restore'){
            if(($_POST['confirm']??'')!=='ΕΠΑΝΑΦΟΡΑ ΔΟΚΙΜΩΝ MELAS')throw new InvalidArgumentException('Επιβεβαιώστε την επαναφορά.');test_cleanup_restore($user,sales_text($_POST,'backup_id',1,36));flash('success','Επαναφέρθηκαν τα δεδομένα του αντιγράφου χωρίς αντικατάσταση άλλων εγγραφών.');redirect_to('test-data-cleanup.php');
        }else throw new InvalidArgumentException('Μη έγκυρη ενέργεια.');
    }catch(Throwable $e){$error=$e instanceof InvalidArgumentException?$e->getMessage():'Δεν έγινε καθάρισμα. Ο έλεγχος εξαρτήσεων ή το αντίγραφο απέτυχε· ελέγξτε τα Logs.';if(!($e instanceof InvalidArgumentException))error_log('Melas test cleanup: '.$e->getMessage());}
}
render_header('Καθάρισμα δοκιμών Melas',$user);
?><section class="card form-section"><h1>Καθάρισμα δοκιμαστικών επαφών και leads</h1><p>Αποκλειστικά Melas CRM, μόνο εγγραφές που δημιουργήθηκαν έως <?= e(TEST_CLEANUP_CUTOFF) ?> (ώρα εφαρμογής). Η επιλογή είναι κλειδωμένη στην ημερομηνία της δικής σας επιβεβαίωσης ότι όλα τα τότε δεδομένα είναι τεστ. Νεότερα δεδομένα δεν περιλαμβάνονται.</p><p>Δεν διαγράφονται χρήστες, πρόοδος Academy, έγγραφα προσωπικού, εταιρικά έγγραφα της βιβλιοθήκης, ρυθμίσεις ή Distillogic. Τα συνδεδεμένα δοκιμαστικά ποσά και οι σχέσεις τους περιλαμβάνονται στη λίστα. Υπογεγραμμένα έγγραφα πελάτη και νέες εγγραφές που συνδέθηκαν αργότερα στα τεστ εμποδίζουν τη διαγραφή μέχρι χωριστό έλεγχο. Η λίστα αποκλεισμού επικοινωνίας διατηρείται.</p>
<?php if($error): ?><p class="alert error"><?= e($error) ?></p><?php endif; ?>
<form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="preview"><label>Ο κωδικός μου<input type="password" name="actor_password" required autocomplete="current-password"></label><button class="button">Έλεγχος ακριβούς λίστας — χωρίς διαγραφή</button></form>
<?php if($result): ?><h2>Τι θα αφαιρεθεί</h2><?php foreach($result['tables'] as $table=>$rows): ?><p><strong><?= e($table) ?></strong>: <?= count($rows) ?> εγγραφές</p><?php endforeach; ?><h3>Leads</h3><?php foreach($result['tables']['sales_leads']??[] as $r): ?><p><?= e($r['lead_reference'].' · '.$r['company_name']) ?></p><?php endforeach; ?><h3>Εταιρείες / επαφές</h3><?php foreach($result['tables']['companies']??[] as $r): ?><p><?= e($r['name']) ?></p><?php endforeach; ?><form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="execute"><label class="checkbox-row"><input type="checkbox" name="backup_confirmed" value="1" required> Έχω πλήρες αντίγραφο βάσης από το Plesk και επιβεβαιώνω ότι όλες οι παραπάνω εγγραφές και τα συνδεδεμένα ποσά είναι δοκιμαστικά.</label><label>Πληκτρολόγησε ΔΙΑΓΡΑΦΗ ΔΟΚΙΜΩΝ MELAS<input name="confirm" required autocomplete="off"></label><label>Ο κωδικός μου<input name="actor_password" type="password" required autocomplete="current-password"></label><button class="button">Αντίγραφο επαναφοράς και καθάρισμα ελεγμένης λίστας</button></form><?php endif; ?></section>
<section class="card form-section"><h2>Αντίγραφα επαναφοράς</h2><p>Φυλάσσονται προστατευμένα μέσα στην ίδια βάση και δεν αποτελούν υποκατάστατο του πλήρους backup Plesk. Η επαναφορά γίνεται ολόκληρη ή καθόλου και δεν αντικαθιστά υπάρχοντα IDs.</p><?php foreach(db()->query('SELECT id,created_at,restored_at,summary_json FROM crm_test_cleanup_backups ORDER BY created_at DESC')->fetchAll() as $b): ?><article class="card"><h3><?= e($b['created_at']) ?></h3><p><?= e($b['id']) ?> · <?= $b['restored_at']?'Επαναφέρθηκε':'Διαθέσιμο' ?></p><?php if(!$b['restored_at']): ?><form method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="restore"><input type="hidden" name="backup_id" value="<?= e($b['id']) ?>"><label>Πληκτρολόγησε ΕΠΑΝΑΦΟΡΑ ΔΟΚΙΜΩΝ MELAS<input name="confirm" required autocomplete="off"></label><label>Ο κωδικός μου<input name="actor_password" type="password" required autocomplete="current-password"></label><button class="button">Επαναφορά αυτού του αντιγράφου</button></form><?php endif; ?></article><?php endforeach; ?></section><?php render_footer(); ?>
